// Code generated by GoDj. DO NOT EDIT.

package models

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
	"reflect"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v2"
const GoDjRelationObjectSchemaSHA256 = "4fa123e921aa78201a337e5945f6f956cefe19130d6b23f86933bb47f7252480"

var _ orm.RelationObjectDescriptor[Note] = NoteDescriptor{}

func (NoteDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Note] {
	return NoteDescriptor{}
}

func (NoteDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Note], bool) {
	switch {
	case reflect.DeepEqual(field, (noteOwnerIDRelationStorage{}).Field()):
		return noteOwnerIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type noteOwnerIDRelationStorage struct{}

var _ orm.RelationStorage[Note] = noteOwnerIDRelationStorage{}

func (noteOwnerIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "owner",
		GoName: "OwnerID",
		Column: "owner_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "godj_identity", ModelName: "user"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "notes"},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (noteOwnerIDRelationStorage) Value(value Note) (query.Value, bool) {
	return query.Integer(value.OwnerID), true
}

var _ orm.RelationObjectDescriptor[Guard] = GuardDescriptor{}

func (GuardDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Guard] {
	return GuardDescriptor{}
}

func (GuardDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Guard], bool) {
	switch {
	case reflect.DeepEqual(field, (guardOwnerIDRelationStorage{}).Field()):
		return guardOwnerIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type guardOwnerIDRelationStorage struct{}

var _ orm.RelationStorage[Guard] = guardOwnerIDRelationStorage{}

func (guardOwnerIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "owner",
		GoName: "OwnerID",
		Column: "owner_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "godj_identity", ModelName: "user"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "guards"},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (guardOwnerIDRelationStorage) Value(value Guard) (query.Value, bool) {
	return query.Integer(value.OwnerID), true
}

type GoDjAppPart2_53765baf7a9d8cc5ba2a3ae23005087d275bf5f67f3f0ef93bae11ebaaf800c1 struct{}

var _ GoDjProjectSnapshot_27398e24a4392aa9d885b989748a3722732a8294e69376cfeedc4edacb120f03
