package consumer

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"example.com/godj-single-object-reference/models"
	"github.com/jackc/pgx/v5"
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/db/postgres"
	"github.com/progresshans/godj/db/sqlite"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
)

type singleRaceBackend interface {
	db.Session
	db.Atomic
	Close() error
}
type singleRaceProbe struct {
	commands []string
	singleRaceBackend
	reads, inserts, uniqueFailures, rolledBack atomic.Int64
	beforeInsert                               func(context.Context) error
	afterInsert                                func(context.Context) error
}

func (probe *singleRaceProbe) Query(ctx context.Context, plan query.Plan) (db.Rows, error) {
	probe.reads.Add(1)
	return probe.singleRaceBackend.Query(ctx, plan)
}
func (probe *singleRaceProbe) Atomic(ctx context.Context, callback func(db.Session) error) error {
	err := probe.singleRaceBackend.Atomic(ctx, func(session db.Session) error {
		probe.commands = append(probe.commands, "BEGIN")
		return callback(singleRaceSession{Session: session, probe: probe})
	})
	if err == nil {
		probe.commands = append(probe.commands, "COMMIT")
	} else {
		probe.commands = append(probe.commands, "ROLLBACK")
	}
	if err != nil && errors.Is(err, &query.Error{Category: query.CategoryIntegrity, Code: query.CodeUniqueConstraint}) && !errors.Is(err, &query.Error{Category: query.CategoryBackend}) {
		probe.rolledBack.Add(1)
	}
	return err
}

type singleRaceSession struct {
	db.Session
	probe *singleRaceProbe
}

func (session singleRaceSession) ValidateSession(ctx context.Context) error {
	return session.Session.(db.SessionValidator).ValidateSession(ctx)
}
func (session singleRaceSession) Insert(ctx context.Context, plan query.InsertPlan) (int64, error) {
	session.probe.inserts.Add(1)
	if hook := session.probe.beforeInsert; hook != nil {
		if err := hook(ctx); err != nil {
			return 0, err
		}
	}
	key, err := session.Session.Insert(ctx, plan)
	if errors.Is(err, &query.Error{Category: query.CategoryIntegrity, Code: query.CodeUniqueConstraint}) {
		session.probe.uniqueFailures.Add(1)
	}
	if err == nil {
		if hook := session.probe.afterInsert; hook != nil {
			err = hook(ctx)
		}
	}
	return key, err
}

func TestSingleObjectCreationRace(t *testing.T) {
	t.Run("sqlite", func(t *testing.T) {
		dsn := "file:" + filepath.ToSlash(filepath.Join(t.TempDir(), "single-race.sqlite3")) + "?mode=rwc&_pragma=busy_timeout(15000)"
		bootstrap, err := sqlite.Open(t.Context(), dsn)
		check(t, err)
		_, err = bootstrap.ExecContext(t.Context(), `CREATE TABLE gdj_single_object_race_label (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(32) NOT NULL UNIQUE, detail VARCHAR(32) NOT NULL)`)
		check(t, err)
		check(t, bootstrap.Close())
		open := func(string) (singleRaceBackend, error) { return sqlite.Open(t.Context(), dsn) }
		runSingleCreationRace(t, open, nil, "sqlite")
	})
	raw := strings.TrimSpace(os.Getenv("GODJ_TEST_POSTGRES_URL"))
	if raw == "" {
		if os.Getenv("GODJ_REQUIRE_POSTGRES") == "1" {
			t.Fatal("required PostgreSQL is absent")
		}
		return
	}
	t.Run("postgres", func(t *testing.T) {
		admin, err := pgx.Connect(t.Context(), raw)
		check(t, err)
		schema := fmt.Sprintf("godj_single_race_%d_%d", os.Getpid(), time.Now().UnixNano())
		quoted := pgx.Identifier{schema}.Sanitize()
		_, err = admin.Exec(t.Context(), "CREATE SCHEMA "+quoted)
		check(t, err)
		t.Cleanup(func() {
			ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
			defer cancel()
			_, err := admin.Exec(ctx, "DROP SCHEMA "+quoted+" CASCADE")
			if err != nil {
				t.Error(err)
			}
			if err := admin.Close(ctx); err != nil {
				t.Error(err)
			}
		})
		_, err = admin.Exec(t.Context(), "CREATE TABLE "+quoted+`.gdj_single_object_race_label (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(32) COLLATE "C" NOT NULL UNIQUE, detail VARCHAR(32) NOT NULL)`)
		check(t, err)
		open := func(role string) (singleRaceBackend, error) {
			parsed, err := url.Parse(raw)
			if err != nil {
				return nil, errors.New("invalid PostgreSQL test URL")
			}
			values := parsed.Query()
			values.Set("application_name", schema+"-"+role)
			parsed.RawQuery = values.Encode()
			return postgres.Open(t.Context(), postgres.Config{URL: parsed.String(), Schema: schema})
		}
		blocked := func(ctx context.Context) error {
			ticker := time.NewTicker(10 * time.Millisecond)
			defer ticker.Stop()
			for {
				var observed bool
				err := admin.QueryRow(ctx, `SELECT EXISTS (
 SELECT 1 FROM pg_stat_activity loser JOIN pg_stat_activity leader ON leader.pid=ANY(pg_blocking_pids(loser.pid))
 WHERE loser.application_name=$1 AND leader.application_name=$2 AND loser.wait_event_type='Lock')`, schema+"-follower", schema+"-leader").Scan(&observed)
				if err != nil {
					return err
				}
				if observed {
					return nil
				}
				select {
				case <-ctx.Done():
					return ctx.Err()
				case <-ticker.C:
				}
			}
		}
		runSingleCreationRace(t, open, blocked, "postgres")
	})
}

func runSingleCreationRace(t *testing.T, open func(string) (singleRaceBackend, error), waitForNativeLock func(context.Context) error, kind string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), 45*time.Second)
	defer cancel()
	var backends [3]singleRaceBackend
	for index, role := range []string{"leader", "follower", "reader"} {
		var err error
		backends[index], err = open(role)
		check(t, err)
		backend := backends[index]
		t.Cleanup(func() { check(t, backend.Close()) })
	}
	entered := make(chan int, 2)
	allowLeader, insertedLeader, followerAttempt, allowCommit := make(chan struct{}), make(chan struct{}), make(chan struct{}), make(chan struct{})
	wait := func(ctx context.Context, signal <-chan struct{}) error {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-signal:
			return nil
		}
	}
	probes := [2]*singleRaceProbe{{singleRaceBackend: backends[0]}, {singleRaceBackend: backends[1]}}
	probes[0].afterInsert = func(ctx context.Context) error { close(insertedLeader); return wait(ctx, allowCommit) }
	probes[1].beforeInsert = func(context.Context) error { close(followerAttempt); return nil }
	type result struct {
		index   int
		value   models.RaceLabel
		created bool
		err     error
	}
	results := make(chan result, 2)
	var workers sync.WaitGroup
	var builds [2]atomic.Int64
	for index, probe := range probes {
		workers.Go(func() {
			input := singleCreate[models.RaceLabel](func() orm.Mutation[models.RaceLabel] {
				builds[index].Add(1)
				entered <- index
				gate := insertedLeader
				if index == 0 {
					gate = allowLeader
				}
				if err := wait(ctx, gate); err != nil {
					return orm.InvalidMutation[models.RaceLabel](err)
				}
				return models.NewRaceLabelCreate("shared", []string{"leader", "follower"}[index]).BuildCreate()
			})
			value, created, err := models.RaceLabelObjects.Using(probe).Filter(models.RaceLabelFields.Name.Exact("shared")).GetOrCreate(ctx, input)
			results <- result{index: index, value: value, created: created, err: err}
		})
	}
	defer func() { cancel(); workers.Wait() }()
	seen := map[int]bool{}
	for range 2 {
		select {
		case <-ctx.Done():
			t.Fatal("initial lookups did not both miss", ctx.Err())
		case index := <-entered:
			seen[index] = true
		}
	}
	if len(seen) != 2 {
		t.Fatal("factory was retried instead of two independent misses")
	}
	close(allowLeader)
	check(t, wait(ctx, insertedLeader))
	check(t, wait(ctx, followerAttempt))
	if waitForNativeLock != nil {
		check(t, waitForNativeLock(ctx))
	}
	// Independent readers cannot observe the leader's uncommitted creation.
	visible, err := models.RaceLabelObjects.Using(backends[2]).Filter(models.RaceLabelFields.Name.Exact("shared")).Count(ctx)
	check(t, err)
	if visible != 0 {
		t.Fatal("uncommitted row was visible", visible)
	}
	close(allowCommit)
	var finished []result
	for range 2 {
		select {
		case <-ctx.Done():
			t.Fatal("creation race did not finish", ctx.Err())
		case result := <-results:
			finished = append(finished, result)
		}
	}
	workers.Wait()
	for _, result := range finished {
		check(t, result.err)
	}
	if finished[0].value.ID == 0 || finished[0].value.ID != finished[1].value.ID || finished[0].created == finished[1].created {
		t.Fatal("unique race did not converge to one row and one creation", finished)
	}
	if builds[0].Load() != 1 || builds[1].Load() != 1 || probes[0].inserts.Load() != 1 || probes[1].inserts.Load() != 1 || probes[0].reads.Load() != 1 || probes[1].reads.Load() != 2 || probes[1].uniqueFailures.Load() != 1 || probes[1].rolledBack.Load() != 1 {
		t.Fatalf("unexpected retry/missing native collision: builds=%d,%d inserts=%d,%d reads=%d,%d unique=%d rollback=%d", builds[0].Load(), builds[1].Load(), probes[0].inserts.Load(), probes[1].inserts.Load(), probes[0].reads.Load(), probes[1].reads.Load(), probes[1].uniqueFailures.Load(), probes[1].rolledBack.Load())
	}
	all, err := models.RaceLabelObjects.Using(backends[2]).Filter(models.RaceLabelFields.Name.Exact("shared")).All(ctx)
	check(t, err)
	if len(all) != 1 || all[0].ID != finished[0].value.ID {
		t.Fatal("race left duplicates", all)
	}
	outcomes := make([]map[string]any, 2)
	for _, result := range finished {
		index := result.index
		outcomes[index] = map[string]any{"created": result.created, "detail": result.value.Detail, "factory_calls": builds[index].Load(), "transaction_commands": probes[index].commands}
	}
	var blocked any
	if waitForNativeLock != nil {
		blocked = true
	}
	compare(t, loadReference(t, kind).Race, map[string]any{
		"insert_attempts":            []int64{probes[0].inserts.Load(), probes[1].inserts.Load()},
		"rows_visible_before_commit": visible, "postgres_blocking_observed": blocked,
		"results": outcomes, "final_rows": []map[string]string{{"name": all[0].Name, "detail": all[0].Detail}},
	})

}
