// Code generated by GoDj. DO NOT EDIT.

package project

import (
	authors "github.com/progresshans/godj/conformance/relationfixture/authors"
	blog "github.com/progresshans/godj/conformance/relationfixture/blog"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		authors.GoDjRelationSchema(),
		blog.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_a691b82718c9cebe7349f77a380daf261bf2b34dceba831806afa27647384fdc struct{}

var _ goDjProjectSnapshot_a691b82718c9cebe7349f77a380daf261bf2b34dceba831806afa27647384fdc
var _ authors.GoDjProjectSnapshot_a691b82718c9cebe7349f77a380daf261bf2b34dceba831806afa27647384fdc
var _ blog.GoDjProjectSnapshot_a691b82718c9cebe7349f77a380daf261bf2b34dceba831806afa27647384fdc
