// Code generated by GoDj. DO NOT EDIT.

package project

import (
	authors "github.com/progresshans/godj/conformance/relationfixture/authors"
	blog "github.com/progresshans/godj/conformance/relationfixture/blog"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		authors.GoDjRelationSchema(),
		blog.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_d7d7eda9a3cc4cb15294c1a33c588069449e9aa33bf0906b7124a1ade01d9077 struct{}

var _ goDjProjectSnapshot_d7d7eda9a3cc4cb15294c1a33c588069449e9aa33bf0906b7124a1ade01d9077
var _ authors.GoDjProjectSnapshot_d7d7eda9a3cc4cb15294c1a33c588069449e9aa33bf0906b7124a1ade01d9077
var _ blog.GoDjProjectSnapshot_d7d7eda9a3cc4cb15294c1a33c588069449e9aa33bf0906b7124a1ade01d9077
