//go:build darwin || linux

package projectgenerate

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/progresshans/godj/codegen"
	relationdeletefixture "github.com/progresshans/godj/conformance/relationdeleteproduct/fixture"
)

func TestRelationDeleteProductNamespaceCollisionAndRecoveryPreserveGeneratedTargets(t *testing.T) {
	ctx := context.Background()
	bundle, productRoot, applicationSource := relationDeleteProductCheckedBundle(t, ctx)
	nextBundle := relationDeleteProductChangedBundle(t, ctx, bundle)

	t.Run("check current product bytes", func(t *testing.T) {
		root := relationDeleteProductExternalRoot(t, productRoot, bundle, applicationSource, true)
		collisionSource := relationDeleteProductCollisionSource(applicationSource)
		writeProjectGenerateTestFile(t, root, "blog/post_methods.go", collisionSource, 0o644)
		before := snapshotProjectGenerateTestTree(t, root)

		report, err := Check(ctx, root, bundle)
		if !errors.Is(err, ErrGeneratedConflict) || errors.Is(err, ErrGeneratedDrift) || errors.Is(err, ErrPublicationInterrupted) {
			t.Fatalf("Check(actual product collision) error = %v, want namespace conflict only", err)
		}
		if !report.Clean() || report.ExpectedSnapshotSHA256 != bundle.SnapshotSHA256() ||
			report.ActualSnapshotSHA256 != bundle.SnapshotSHA256() {
			t.Fatalf("Check(actual product collision) report = %#v, want exact generated bytes and namespace-only conflict", report)
		}
		if !strings.Contains(err.Error(), "github.com/progresshans/godj/conformance/relationdeleteproduct/blog.Post.Save") {
			t.Fatalf("Check(actual product collision) error = %v, want exact current raw receiver", err)
		}
		after := snapshotProjectGenerateTestTree(t, root)
		if strings.Join(before, "\n") != strings.Join(after, "\n") {
			t.Fatal("Check(actual product collision) mutated the repository-external project")
		}
	})

	t.Run("mandatory recovery precedes publication rejection", func(t *testing.T) {
		root := relationDeleteProductExternalRoot(t, productRoot, bundle, applicationSource, false)
		verifier, err := NewGoCandidateVerifier(root, bundle)
		if err != nil {
			t.Fatalf("NewGoCandidateVerifier(actual product) error = %v", err)
		}
		cleanupFault := errors.New("injected actual-product committed cleanup interruption")
		err = publishWithHooks(ctx, root, bundle, verifier, publicationHooks{
			after: func(step publicationStep, _ string, _ int) error {
				if step == publicationStepTransactionClean {
					return cleanupFault
				}
				return nil
			},
		})
		if !errors.Is(err, ErrPublicationRecoveryRequired) || !strings.Contains(err.Error(), cleanupFault.Error()) {
			t.Fatalf("Publish(actual product cleanup interruption) error = %v, want recovery required with injected cause", err)
		}
		assertPublishedBundle(t, root, bundle)

		collisionSource := relationDeleteProductCollisionSource(applicationSource)
		writeProjectGenerateTestFile(t, root, "blog/post_methods.go", collisionSource, 0o644)
		beforeTargets := relationDeleteProductGeneratedTargetSnapshot(t, root, bundle)
		interruptedReport, checkErr := Check(ctx, root, bundle)
		if !errors.Is(checkErr, ErrGeneratedConflict) || !errors.Is(checkErr, ErrGeneratedDrift) ||
			!errors.Is(checkErr, ErrPublicationInterrupted) || !interruptedReport.Interrupted {
			t.Fatalf(
				"Check(actual product interrupted collision) report=%#v error=%v, want interrupted drift plus namespace conflict",
				interruptedReport,
				checkErr,
			)
		}
		if afterCheck := relationDeleteProductGeneratedTargetSnapshot(t, root, bundle); strings.Join(beforeTargets, "\n") != strings.Join(afterCheck, "\n") {
			t.Fatalf("Check(actual product interrupted collision) mutated generated targets\nbefore=%v\nafter=%v", beforeTargets, afterCheck)
		}
		actualVerifier, err := NewGoCandidateVerifier(root, nextBundle)
		if err != nil {
			t.Fatalf("NewGoCandidateVerifier(recovery retry) error = %v", err)
		}
		verifierCalls := 0
		stageWrites := 0
		err = publishWithHooks(ctx, root, nextBundle, CandidateVerifyFunc(func(verifyCtx context.Context, candidateRoot string) error {
			verifierCalls++
			return actualVerifier.Verify(verifyCtx, candidateRoot)
		}), publicationHooks{
			after: func(step publicationStep, _ string, _ int) error {
				switch step {
				case publicationStepStageFileDurable:
					stageWrites++
				}
				return nil
			},
		})
		if !errors.Is(err, ErrGeneratedConflict) || errors.Is(err, ErrCandidateVerification) {
			t.Fatalf("Publish(actual product recovery then collision) error = %v, want namespace conflict before candidate verification", err)
		}
		if stageWrites != 0 || verifierCalls != 0 {
			t.Fatalf("Publish(actual product recovery then collision) stage writes/verifier calls = %d/%d, want 0/0", stageWrites, verifierCalls)
		}
		afterTargets := relationDeleteProductGeneratedTargetSnapshot(t, root, bundle)
		if strings.Join(beforeTargets, "\n") != strings.Join(afterTargets, "\n") {
			t.Fatalf("namespace-rejected actual-product retry mutated generated targets\nbefore=%v\nafter=%v", beforeTargets, afterTargets)
		}
		assertPublishedBundle(t, root, bundle)
		assertPublicationControlClean(t, root)
		recoveredReport, checkErr := Check(ctx, root, bundle)
		if !errors.Is(checkErr, ErrGeneratedConflict) || errors.Is(checkErr, ErrGeneratedDrift) ||
			errors.Is(checkErr, ErrPublicationInterrupted) || !recoveredReport.Clean() {
			t.Fatalf(
				"Check(actual product recovered collision) report=%#v error=%v, want collision-only after mandatory recovery",
				recoveredReport,
				checkErr,
			)
		}
		if got, readErr := os.ReadFile(filepath.Join(root, "blog", "post_methods.go")); readErr != nil || !bytes.Equal(got, collisionSource) {
			t.Fatalf("namespace-rejected actual-product retry changed app source: bytes=%q error=%v", got, readErr)
		}
	})
}

func relationDeleteProductCheckedBundle(
	t *testing.T,
	ctx context.Context,
) (codegen.GeneratedBundle, string, []byte) {
	t.Helper()

	spec, err := relationdeletefixture.ProjectSpec(ctx)
	if err != nil {
		t.Fatalf("load relation-delete product spec: %v", err)
	}
	bundle, err := codegen.GenerateProject(spec)
	if err != nil {
		t.Fatalf("generate relation-delete product bundle: %v", err)
	}
	if len(bundle.Files()) != 16 {
		t.Fatalf("relation-delete product bundle files = %d, want exact current 16", len(bundle.Files()))
	}
	productRoot := filepath.Join(projectGenerateRepositoryRoot(t), "conformance", "relationdeleteproduct")
	for _, file := range bundle.Files() {
		contents, mode, readErr := readRegularProjectFile(productRoot, file.Path)
		if readErr != nil {
			t.Fatalf("read checked relation-delete product file %s: %v", file.Path, readErr)
		}
		if mode != file.Mode || !bytes.Equal(contents, file.Source()) {
			t.Fatalf("checked relation-delete product file %s mode/bytes differ from exact ProjectSpec bundle", file.Path)
		}
	}
	manifest, manifestMode, err := readRegularProjectFileBounded(productRoot, generatedManifestRelativePath, maxCommittedManifestBytes)
	if err != nil {
		t.Fatalf("read checked relation-delete product manifest: %v", err)
	}
	if manifestMode != 0o644 || !bytes.Equal(manifest, bundle.Manifest()) {
		t.Fatal("checked relation-delete product manifest mode/bytes differ from exact ProjectSpec bundle")
	}
	applicationSource, applicationMode, err := readRegularProjectFileBounded(
		productRoot,
		"blog/post_methods.go",
		maxSourceNamespaceFileBytes,
	)
	if err != nil {
		t.Fatalf("read relation-delete app-owned method source: %v", err)
	}
	if applicationMode != 0o644 || !bytes.Contains(applicationSource, []byte("func (post *Post) NormalizeTitle()")) {
		t.Fatal("relation-delete app-owned method source mode/current method differs")
	}
	return bundle, productRoot, applicationSource
}

func relationDeleteProductChangedBundle(
	t *testing.T,
	ctx context.Context,
	current codegen.GeneratedBundle,
) codegen.GeneratedBundle {
	t.Helper()

	spec, err := relationdeletefixture.ProjectSpec(ctx)
	if err != nil {
		t.Fatalf("load changed relation-delete product spec: %v", err)
	}
	changed := false
	for appIndex := range spec.Apps {
		if spec.Apps[appIndex].Schema.AppLabel != "blog" {
			continue
		}
		for modelIndex := range spec.Apps[appIndex].Schema.Models {
			if spec.Apps[appIndex].Schema.Models[modelIndex].Name != "post" {
				continue
			}
			for fieldIndex := range spec.Apps[appIndex].Schema.Models[modelIndex].Fields {
				field := &spec.Apps[appIndex].Schema.Models[modelIndex].Fields[fieldIndex]
				if field.Name == "title" {
					field.MaxLength++
					changed = true
				}
			}
		}
	}
	if !changed {
		t.Fatal("current relation-delete product spec has no blog.Post.title field")
	}
	next, err := codegen.GenerateProject(spec)
	if err != nil {
		t.Fatalf("generate changed relation-delete product bundle: %v", err)
	}
	if next.SnapshotSHA256() == current.SnapshotSHA256() {
		t.Fatal("changed relation-delete product candidate retained the current snapshot")
	}
	return next
}

func relationDeleteProductExternalRoot(
	t *testing.T,
	productRoot string,
	bundle codegen.GeneratedBundle,
	applicationSource []byte,
	includeGenerated bool,
) string {
	t.Helper()

	moduleRoot := t.TempDir()
	repositoryRoot, err := filepath.EvalSymlinks(projectGenerateRepositoryRoot(t))
	if err != nil {
		t.Fatalf("resolve repository root: %v", err)
	}
	for _, relative := range []string{"go.mod", "go.sum"} {
		contents, readErr := os.ReadFile(filepath.Join(repositoryRoot, relative))
		if readErr != nil {
			t.Fatalf("read repository module file %s: %v", relative, readErr)
		}
		writeProjectGenerateTestFile(t, moduleRoot, relative, contents, 0o644)
	}
	for _, directory := range []string{"db", "orm", "query", "schema"} {
		if err := os.Symlink(filepath.Join(repositoryRoot, directory), filepath.Join(moduleRoot, directory)); err != nil {
			t.Fatalf("link repository dependency %s into external module: %v", directory, err)
		}
	}
	root := filepath.Join(moduleRoot, "conformance", "relationdeleteproduct")
	if err := os.MkdirAll(root, 0o755); err != nil {
		t.Fatalf("create repository-external relation-delete root: %v", err)
	}
	physicalRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		t.Fatalf("resolve repository-external test root: %v", err)
	}
	if sameOrDescendantPath(physicalRoot, repositoryRoot) {
		t.Fatalf("actual-product fixture root %q is not repository-external", physicalRoot)
	}
	writeProjectGenerateTestFile(t, root, "blog/post_methods.go", applicationSource, 0o644)
	if !includeGenerated {
		return root
	}
	for _, file := range bundle.Files() {
		contents, mode, err := readRegularProjectFile(productRoot, file.Path)
		if err != nil {
			t.Fatalf("copy checked relation-delete product file %s: %v", file.Path, err)
		}
		if mode != file.Mode {
			t.Fatalf("copy checked relation-delete product file %s mode = %v, want %v", file.Path, mode, file.Mode)
		}
		writeProjectGenerateTestFile(t, root, file.Path, contents, mode)
	}
	manifest, mode, err := readRegularProjectFileBounded(productRoot, generatedManifestRelativePath, maxCommittedManifestBytes)
	if err != nil {
		t.Fatalf("copy checked relation-delete product manifest: %v", err)
	}
	if mode != 0o644 {
		t.Fatalf("copy checked relation-delete product manifest mode = %v, want 0644", mode)
	}
	writeProjectGenerateTestFile(t, root, generatedManifestRelativePath, manifest, mode)
	return root
}

func relationDeleteProductCollisionSource(applicationSource []byte) []byte {
	result := append([]byte(nil), applicationSource...)
	return append(result, []byte("\nfunc (*Post) Save() {}\n")...)
}

func relationDeleteProductGeneratedTargetSnapshot(
	t *testing.T,
	root string,
	bundle codegen.GeneratedBundle,
) []string {
	t.Helper()

	files := bundle.Files()
	result := make([]string, 0, len(files)+1)
	for _, file := range files {
		result = append(result, relationDeleteProductTargetState(t, root, file.Path))
	}
	result = append(result, relationDeleteProductTargetState(t, root, generatedManifestRelativePath))
	return result
}

func relationDeleteProductTargetState(t *testing.T, root, relative string) string {
	t.Helper()

	filename := filepath.Join(root, filepath.FromSlash(relative))
	info, err := os.Lstat(filename)
	if err != nil {
		t.Fatalf("inspect actual-product target %s: %v", relative, err)
	}
	if !info.Mode().IsRegular() {
		t.Fatalf("actual-product target %s mode = %v, want regular", relative, info.Mode())
	}
	contents, err := os.ReadFile(filename)
	if err != nil {
		t.Fatalf("read actual-product target %s: %v", relative, err)
	}
	return fmt.Sprintf("%s:%04o:%s", relative, info.Mode().Perm(), sha256Hex(contents))
}
