// Code generated by GoDj. DO NOT EDIT.

package details

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
	"reflect"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v2"
const GoDjRelationObjectSchemaSHA256 = "c9877bab1bd0fa2f1eeb260816c6660ba29cc178c40bdeb6b0743dbef06dccaf"

var _ orm.RelationObjectDescriptor[Child] = ChildDescriptor{}

func (ChildDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Child] {
	return ChildDescriptor{}
}

func (ChildDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Child], bool) {
	switch {
	case reflect.DeepEqual(field, (childRootIDRelationStorage{}).Field()):
		return childRootIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type childRootIDRelationStorage struct{}

var _ orm.RelationStorage[Child] = childRootIDRelationStorage{}

func (childRootIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "root",
		GoName: "RootID",
		Column: "root_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "children"},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (childRootIDRelationStorage) Value(value Child) (query.Value, bool) {
	return query.Integer(value.RootID), true
}

var _ orm.RelationObjectDescriptor[Grandchild] = GrandchildDescriptor{}

func (GrandchildDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Grandchild] {
	return GrandchildDescriptor{}
}

func (GrandchildDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Grandchild], bool) {
	switch {
	case reflect.DeepEqual(field, (grandchildChildIDRelationStorage{}).Field()):
		return grandchildChildIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type grandchildChildIDRelationStorage struct{}

var _ orm.RelationStorage[Grandchild] = grandchildChildIDRelationStorage{}

func (grandchildChildIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "child",
		GoName: "ChildID",
		Column: "child_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadedetails", ModelName: "child"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "grandchildren"},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (grandchildChildIDRelationStorage) Value(value Grandchild) (query.Value, bool) {
	return query.Integer(value.ChildID), true
}

var _ orm.RelationObjectDescriptor[Watcher] = WatcherDescriptor{}

func (WatcherDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Watcher] {
	return WatcherDescriptor{}
}

func (WatcherDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Watcher], bool) {
	switch {
	case reflect.DeepEqual(field, (watcherChildIDRelationStorage{}).Field()):
		return watcherChildIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type watcherChildIDRelationStorage struct{}

var _ orm.RelationStorage[Watcher] = watcherChildIDRelationStorage{}

func (watcherChildIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:     "child",
		GoName:   "ChildID",
		Column:   "child_id",
		Kind:     ir.FieldForeignKey,
		Nullable: true,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadedetails", ModelName: "child"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteSetNull,
		},
	}
}

func (watcherChildIDRelationStorage) Value(value Watcher) (query.Value, bool) {
	if value.ChildID == nil {
		return query.Null(), true
	}
	return query.Integer(*value.ChildID), true
}

var _ orm.RelationObjectDescriptor[Protected] = ProtectedDescriptor{}

func (ProtectedDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Protected] {
	return ProtectedDescriptor{}
}

func (ProtectedDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Protected], bool) {
	switch {
	case reflect.DeepEqual(field, (protectedGrandchildIDRelationStorage{}).Field()):
		return protectedGrandchildIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type protectedGrandchildIDRelationStorage struct{}

var _ orm.RelationStorage[Protected] = protectedGrandchildIDRelationStorage{}

func (protectedGrandchildIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "grandchild",
		GoName: "GrandchildID",
		Column: "grandchild_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadedetails", ModelName: "grandchild"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (protectedGrandchildIDRelationStorage) Value(value Protected) (query.Value, bool) {
	return query.Integer(value.GrandchildID), true
}

var _ orm.RelationObjectDescriptor[Twin] = TwinDescriptor{}

func (TwinDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Twin] {
	return TwinDescriptor{}
}

func (TwinDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Twin], bool) {
	switch {
	case reflect.DeepEqual(field, (twinFirstIDRelationStorage{}).Field()):
		return twinFirstIDRelationStorage{}, true
	case reflect.DeepEqual(field, (twinSecondIDRelationStorage{}).Field()):
		return twinSecondIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type twinFirstIDRelationStorage struct{}

var _ orm.RelationStorage[Twin] = twinFirstIDRelationStorage{}

func (twinFirstIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "first",
		GoName: "FirstID",
		Column: "first_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (twinFirstIDRelationStorage) Value(value Twin) (query.Value, bool) {
	return query.Integer(value.FirstID), true
}

type twinSecondIDRelationStorage struct{}

var _ orm.RelationStorage[Twin] = twinSecondIDRelationStorage{}

func (twinSecondIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "second",
		GoName: "SecondID",
		Column: "second_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (twinSecondIDRelationStorage) Value(value Twin) (query.Value, bool) {
	return query.Integer(value.SecondID), true
}

func (TwinDescriptor) ManyToManyCreateInput() orm.ManyToManyInput[Twin] { return TwinCreate{} }

var _ orm.ManyToManyDescriptor[Twin] = TwinDescriptor{}

func (input TwinCreate) BuildManyToManyCreate(source, target ir.Field, sourceKey, targetKey int64) orm.Mutation[Twin] {
	invalid := func() orm.Mutation[Twin] {
		return orm.InvalidMutation[Twin](&query.Error{Category: query.CategoryQuery, Code: query.CodeInvalidPlan, Detail: "collection endpoints must be distinct canonical ForeignKeys omitted from through defaults"})
	}
	if source.Name == target.Name {
		return invalid()
	}
	for index, field := range []ir.Field{source, target} {
		key := sourceKey
		if index == 1 {
			key = targetKey
		}
		switch {
		case reflect.DeepEqual(field, (twinFirstIDRelationStorage{}).Field()):
			if _, set := input.firstID.Get(); set {
				return invalid()
			}
			input = input.WithFirstID(key)
		case reflect.DeepEqual(field, (twinSecondIDRelationStorage{}).Field()):
			if _, set := input.secondID.Get(); set {
				return invalid()
			}
			input = input.WithSecondID(key)
		default:
			return invalid()
		}
	}
	return input.BuildCreate()
}

var _ orm.RelationObjectDescriptor[Hidden] = HiddenDescriptor{}

func (HiddenDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Hidden] {
	return HiddenDescriptor{}
}

func (HiddenDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Hidden], bool) {
	switch {
	case reflect.DeepEqual(field, (hiddenRootIDRelationStorage{}).Field()):
		return hiddenRootIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type hiddenRootIDRelationStorage struct{}

var _ orm.RelationStorage[Hidden] = hiddenRootIDRelationStorage{}

func (hiddenRootIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "root",
		GoName: "RootID",
		Column: "root_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (hiddenRootIDRelationStorage) Value(value Hidden) (query.Value, bool) {
	return query.Integer(value.RootID), true
}

var _ orm.RelationObjectDescriptor[Detail] = DetailDescriptor{}

func (DetailDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Detail] {
	return DetailDescriptor{}
}

func (DetailDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Detail], bool) {
	switch {
	case reflect.DeepEqual(field, (detailRootIDRelationStorage{}).Field()):
		return detailRootIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type detailRootIDRelationStorage struct{}

var _ orm.RelationStorage[Detail] = detailRootIDRelationStorage{}

func (detailRootIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "root",
		GoName: "RootID",
		Column: "root_id",
		Kind:   ir.FieldForeignKey,
		Unique: true,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationOneToOne,
			Reverse:     ir.ReverseRelation{Name: "detail"},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (detailRootIDRelationStorage) Value(value Detail) (query.Value, bool) {
	return query.Integer(value.RootID), true
}

var _ orm.RelationObjectDescriptor[Overlap] = OverlapDescriptor{}

func (OverlapDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Overlap] {
	return OverlapDescriptor{}
}

func (OverlapDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Overlap], bool) {
	switch {
	case reflect.DeepEqual(field, (overlapCascadeRootIDRelationStorage{}).Field()):
		return overlapCascadeRootIDRelationStorage{}, true
	case reflect.DeepEqual(field, (overlapProtectedRootIDRelationStorage{}).Field()):
		return overlapProtectedRootIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type overlapCascadeRootIDRelationStorage struct{}

var _ orm.RelationStorage[Overlap] = overlapCascadeRootIDRelationStorage{}

func (overlapCascadeRootIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "cascade_root",
		GoName: "CascadeRootID",
		Column: "cascade_root_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (overlapCascadeRootIDRelationStorage) Value(value Overlap) (query.Value, bool) {
	return query.Integer(value.CascadeRootID), true
}

type overlapProtectedRootIDRelationStorage struct{}

var _ orm.RelationStorage[Overlap] = overlapProtectedRootIDRelationStorage{}

func (overlapProtectedRootIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "protected_root",
		GoName: "ProtectedRootID",
		Column: "protected_root_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (overlapProtectedRootIDRelationStorage) Value(value Overlap) (query.Value, bool) {
	return query.Integer(value.ProtectedRootID), true
}

func (OverlapDescriptor) ManyToManyCreateInput() orm.ManyToManyInput[Overlap] { return OverlapCreate{} }

var _ orm.ManyToManyDescriptor[Overlap] = OverlapDescriptor{}

func (input OverlapCreate) BuildManyToManyCreate(source, target ir.Field, sourceKey, targetKey int64) orm.Mutation[Overlap] {
	invalid := func() orm.Mutation[Overlap] {
		return orm.InvalidMutation[Overlap](&query.Error{Category: query.CategoryQuery, Code: query.CodeInvalidPlan, Detail: "collection endpoints must be distinct canonical ForeignKeys omitted from through defaults"})
	}
	if source.Name == target.Name {
		return invalid()
	}
	for index, field := range []ir.Field{source, target} {
		key := sourceKey
		if index == 1 {
			key = targetKey
		}
		switch {
		case reflect.DeepEqual(field, (overlapCascadeRootIDRelationStorage{}).Field()):
			if _, set := input.cascadeRootID.Get(); set {
				return invalid()
			}
			input = input.WithCascadeRootID(key)
		case reflect.DeepEqual(field, (overlapProtectedRootIDRelationStorage{}).Field()):
			if _, set := input.protectedRootID.Get(); set {
				return invalid()
			}
			input = input.WithProtectedRootID(key)
		default:
			return invalid()
		}
	}
	return input.BuildCreate()
}

var _ orm.RelationObjectDescriptor[Right] = RightDescriptor{}

func (RightDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Right] {
	return RightDescriptor{}
}

func (RightDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Right], bool) {
	switch {
	case reflect.DeepEqual(field, (rightLeftIDRelationStorage{}).Field()):
		return rightLeftIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type rightLeftIDRelationStorage struct{}

var _ orm.RelationStorage[Right] = rightLeftIDRelationStorage{}

func (rightLeftIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "left",
		GoName: "LeftID",
		Column: "left_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "left"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (rightLeftIDRelationStorage) Value(value Right) (query.Value, bool) {
	return query.Integer(value.LeftID), true
}

var _ orm.RelationObjectDescriptor[RequiredRight] = RequiredRightDescriptor{}

func (RequiredRightDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[RequiredRight] {
	return RequiredRightDescriptor{}
}

func (RequiredRightDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[RequiredRight], bool) {
	switch {
	case reflect.DeepEqual(field, (requiredRightLeftIDRelationStorage{}).Field()):
		return requiredRightLeftIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type requiredRightLeftIDRelationStorage struct{}

var _ orm.RelationStorage[RequiredRight] = requiredRightLeftIDRelationStorage{}

func (requiredRightLeftIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "left",
		GoName: "LeftID",
		Column: "left_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "required_left"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Disabled: true},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (requiredRightLeftIDRelationStorage) Value(value RequiredRight) (query.Value, bool) {
	return query.Integer(value.LeftID), true
}

var _ GoDjProjectSnapshot_8227f21f258923139aeffd913eab5feb1d87520915754fb57d74147dcc56ca2e
