// Code generated by GoDj. DO NOT EDIT.

package details

import (
	"database/sql"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
)

const GoDjRelationProjectionGeneratorVersion = "godj-codegen-rel-projection-v1"
const GoDjRelationProjectionSchemaSHA256 = "c9877bab1bd0fa2f1eeb260816c6660ba29cc178c40bdeb6b0743dbef06dccaf"

var _ orm.ProjectionDescriptor[Child] = ChildDescriptor{}

func (ChildDescriptor) NewProjectionScan() orm.ProjectionScan[Child] {
	return &childProjectionScan{}
}

type childProjectionScan struct {
	scanID     sql.NullInt64
	scanRootID sql.NullInt64
}

func (_scan *childProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanRootID,
	}
}

func (_scan *childProjectionScan) Decode() (Child, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Child{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanRootID.Valid {
		return Child{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Child{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanRootID.Valid {
		return Child{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Child{}
	_value.ID = _scan.scanID.Int64
	_value.RootID = _scan.scanRootID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Grandchild] = GrandchildDescriptor{}

func (GrandchildDescriptor) NewProjectionScan() orm.ProjectionScan[Grandchild] {
	return &grandchildProjectionScan{}
}

type grandchildProjectionScan struct {
	scanID      sql.NullInt64
	scanChildID sql.NullInt64
}

func (_scan *grandchildProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanChildID,
	}
}

func (_scan *grandchildProjectionScan) Decode() (Grandchild, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Grandchild{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanChildID.Valid {
		return Grandchild{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Grandchild{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanChildID.Valid {
		return Grandchild{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Grandchild{}
	_value.ID = _scan.scanID.Int64
	_value.ChildID = _scan.scanChildID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Watcher] = WatcherDescriptor{}

func (WatcherDescriptor) NewProjectionScan() orm.ProjectionScan[Watcher] {
	return &watcherProjectionScan{}
}

type watcherProjectionScan struct {
	scanID      sql.NullInt64
	scanChildID sql.NullInt64
}

func (_scan *watcherProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanChildID,
	}
}

func (_scan *watcherProjectionScan) Decode() (Watcher, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Watcher{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanChildID.Valid {
		return Watcher{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Watcher{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Watcher{}
	_value.ID = _scan.scanID.Int64
	if _scan.scanChildID.Valid {
		_scanned := _scan.scanChildID.Int64
		_value.ChildID = &_scanned
	}
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Protected] = ProtectedDescriptor{}

func (ProtectedDescriptor) NewProjectionScan() orm.ProjectionScan[Protected] {
	return &protectedProjectionScan{}
}

type protectedProjectionScan struct {
	scanID           sql.NullInt64
	scanGrandchildID sql.NullInt64
}

func (_scan *protectedProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanGrandchildID,
	}
}

func (_scan *protectedProjectionScan) Decode() (Protected, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Protected{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanGrandchildID.Valid {
		return Protected{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Protected{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanGrandchildID.Valid {
		return Protected{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Protected{}
	_value.ID = _scan.scanID.Int64
	_value.GrandchildID = _scan.scanGrandchildID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Twin] = TwinDescriptor{}

func (TwinDescriptor) NewProjectionScan() orm.ProjectionScan[Twin] {
	return &twinProjectionScan{}
}

type twinProjectionScan struct {
	scanID       sql.NullInt64
	scanFirstID  sql.NullInt64
	scanSecondID sql.NullInt64
}

func (_scan *twinProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanFirstID,
		&_scan.scanSecondID,
	}
}

func (_scan *twinProjectionScan) Decode() (Twin, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Twin{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanFirstID.Valid && !_scan.scanSecondID.Valid {
		return Twin{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Twin{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanFirstID.Valid {
		return Twin{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanSecondID.Valid {
		return Twin{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Twin{}
	_value.ID = _scan.scanID.Int64
	_value.FirstID = _scan.scanFirstID.Int64
	_value.SecondID = _scan.scanSecondID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Hidden] = HiddenDescriptor{}

func (HiddenDescriptor) NewProjectionScan() orm.ProjectionScan[Hidden] {
	return &hiddenProjectionScan{}
}

type hiddenProjectionScan struct {
	scanID     sql.NullInt64
	scanRootID sql.NullInt64
}

func (_scan *hiddenProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanRootID,
	}
}

func (_scan *hiddenProjectionScan) Decode() (Hidden, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Hidden{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanRootID.Valid {
		return Hidden{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Hidden{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanRootID.Valid {
		return Hidden{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Hidden{}
	_value.ID = _scan.scanID.Int64
	_value.RootID = _scan.scanRootID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Detail] = DetailDescriptor{}

func (DetailDescriptor) NewProjectionScan() orm.ProjectionScan[Detail] {
	return &detailProjectionScan{}
}

type detailProjectionScan struct {
	scanID     sql.NullInt64
	scanRootID sql.NullInt64
}

func (_scan *detailProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanRootID,
	}
}

func (_scan *detailProjectionScan) Decode() (Detail, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Detail{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanRootID.Valid {
		return Detail{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Detail{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanRootID.Valid {
		return Detail{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Detail{}
	_value.ID = _scan.scanID.Int64
	_value.RootID = _scan.scanRootID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Overlap] = OverlapDescriptor{}

func (OverlapDescriptor) NewProjectionScan() orm.ProjectionScan[Overlap] {
	return &overlapProjectionScan{}
}

type overlapProjectionScan struct {
	scanID              sql.NullInt64
	scanCascadeRootID   sql.NullInt64
	scanProtectedRootID sql.NullInt64
}

func (_scan *overlapProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanCascadeRootID,
		&_scan.scanProtectedRootID,
	}
}

func (_scan *overlapProjectionScan) Decode() (Overlap, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Overlap{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanCascadeRootID.Valid && !_scan.scanProtectedRootID.Valid {
		return Overlap{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Overlap{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanCascadeRootID.Valid {
		return Overlap{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanProtectedRootID.Valid {
		return Overlap{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Overlap{}
	_value.ID = _scan.scanID.Int64
	_value.CascadeRootID = _scan.scanCascadeRootID.Int64
	_value.ProtectedRootID = _scan.scanProtectedRootID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Right] = RightDescriptor{}

func (RightDescriptor) NewProjectionScan() orm.ProjectionScan[Right] {
	return &rightProjectionScan{}
}

type rightProjectionScan struct {
	scanID     sql.NullInt64
	scanLeftID sql.NullInt64
}

func (_scan *rightProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanLeftID,
	}
}

func (_scan *rightProjectionScan) Decode() (Right, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Right{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanLeftID.Valid {
		return Right{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Right{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanLeftID.Valid {
		return Right{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Right{}
	_value.ID = _scan.scanID.Int64
	_value.LeftID = _scan.scanLeftID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[RequiredRight] = RequiredRightDescriptor{}

func (RequiredRightDescriptor) NewProjectionScan() orm.ProjectionScan[RequiredRight] {
	return &requiredRightProjectionScan{}
}

type requiredRightProjectionScan struct {
	scanID     sql.NullInt64
	scanLeftID sql.NullInt64
}

func (_scan *requiredRightProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanLeftID,
	}
}

func (_scan *requiredRightProjectionScan) Decode() (RequiredRight, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return RequiredRight{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanLeftID.Valid {
		return RequiredRight{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return RequiredRight{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanLeftID.Valid {
		return RequiredRight{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := RequiredRight{}
	_value.ID = _scan.scanID.Int64
	_value.LeftID = _scan.scanLeftID.Int64
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ GoDjProjectSnapshot_8227f21f258923139aeffd913eab5feb1d87520915754fb57d74147dcc56ca2e
