// Code generated by GoDj. DO NOT EDIT.

package models

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/schema/ir"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v1"
const GoDjRelationObjectSchemaSHA256 = "3e6ec104d26c21665690e9d4a20f547ae2f7212b2eb35f5e741d38a85274647d"

var _ orm.RelationObjectDescriptor[Article] = ArticleDescriptor{}

func (ArticleDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Article] {
	return ArticleDescriptor{}
}

func (ArticleDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Article], bool) {
	return nil, false
}

var _ GoDjProjectSnapshot_5fc6ed960616f1b7166478aa2ede39cad36089af6e4469d543436f620c0b57c2
