// Code generated by GoDj. DO NOT EDIT.

package models

import (
	"database/sql"
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
)

const GoDjGeneratorVersion = "godj-codegen-current-v2"
const GoDjSchemaSHA256 = "de0cbfa6d4bb1b194b86de168e3e1c7d5780b971e37068a4f8db23b163c12cdc"

type Article struct {
	ID                    int64
	Title                 string
	Published             bool
	Summary               *string
	Slug                  *string
	godjPrimaryKeyPresent bool
}

type ArticleDescriptor struct{}

var _ orm.ModelDescriptor[Article] = ArticleDescriptor{}

var _ orm.WriteDescriptor[Article] = ArticleDescriptor{}

func (ArticleDescriptor) Metadata() ir.Model {
	return articleMetadata()
}

func (ArticleDescriptor) Scan(row db.Row) (Article, error) {
	var value Article
	var scanSummary sql.NullString
	var scanSlug sql.NullString
	if err := row.Scan(&value.ID, &value.Title, &value.Published, &scanSummary, &scanSlug); err != nil {
		return Article{}, err
	}
	if scanSummary.Valid {
		scanned := scanSummary.String
		value.Summary = &scanned
	}
	if scanSlug.Valid {
		scanned := scanSlug.String
		value.Slug = &scanned
	}
	value.godjPrimaryKeyPresent = true
	return value, nil
}

func (ArticleDescriptor) PrimaryKey(value Article) (query.Value, bool) {
	return query.Integer(value.ID), value.godjPrimaryKeyPresent
}

func (ArticleDescriptor) SetPrimaryKey(value *Article, key int64) {
	value.ID = key
	value.godjPrimaryKeyPresent = true
}

func (ArticleDescriptor) ClearPrimaryKey(value *Article) {
	value.ID = 0
	value.godjPrimaryKeyPresent = false
}

func (ArticleDescriptor) CloneModel(value Article) Article {
	clone := value
	if value.Summary != nil {
		clonedSummary := *value.Summary
		clone.Summary = &clonedSummary
	}
	if value.Slug != nil {
		clonedSlug := *value.Slug
		clone.Slug = &clonedSlug
	}
	return clone
}

func (descriptor ArticleDescriptor) CloneWriteModel(value Article) Article {
	return descriptor.CloneModel(value)
}

func (ArticleDescriptor) WriteFieldValue(value Article, field ir.Field) (query.Value, bool) {
	switch field.Name {
	case "id":
		return query.Integer(value.ID), true
	case "title":
		return query.String(value.Title), true
	case "published":
		return query.Boolean(value.Published), true
	case "summary":
		if value.Summary == nil {
			return query.Null(), true
		}
		return query.String(*value.Summary), true
	case "slug":
		if value.Slug == nil {
			return query.Null(), true
		}
		return query.String(*value.Slug), true
	default:
		return query.Value{}, false
	}
}

func (ArticleDescriptor) SetFieldValue(value *Article, field ir.Field, input query.Value) bool {
	if value == nil {
		return false
	}
	switch field.Name {
	case "title":
		assigned, ok := input.String()
		if !ok {
			return false
		}
		value.Title = assigned
		return true
	case "published":
		assigned, ok := input.Boolean()
		if !ok {
			return false
		}
		value.Published = assigned
		return true
	case "summary":
		if input.IsNull() {
			value.Summary = nil
			return true
		}
		assigned, ok := input.String()
		if !ok {
			return false
		}
		value.Summary = &assigned
		return true
	case "slug":
		if input.IsNull() {
			value.Slug = nil
			return true
		}
		assigned, ok := input.String()
		if !ok {
			return false
		}
		value.Slug = &assigned
		return true
	default:
		return false
	}
}

type ArticleFieldSet struct {
	ID        orm.AutoField[Article]
	Title     orm.StringField[Article]
	Published orm.BooleanField[Article]
	Summary   orm.NullableStringField[Article]
	Slug      orm.NullableStringField[Article]
}

var ArticleFields = func() ArticleFieldSet {
	metadata := articleMetadata()
	return ArticleFieldSet{
		ID:        orm.NewAutoField[Article](metadata.Fields[0]),
		Title:     orm.NewStringField[Article](metadata.Fields[1]),
		Published: orm.NewBooleanField[Article](metadata.Fields[2]),
		Summary:   orm.NewNullableStringField[Article](metadata.Fields[3]),
		Slug:      orm.NewNullableStringField[Article](metadata.Fields[4]),
	}
}()

var ArticleObjects = orm.NewManager[Article](ArticleDescriptor{})

func NewArticleWithID(key int64) Article {
	return Article{ID: key, godjPrimaryKeyPresent: true}
}

func ArticleUpdateFields(fields ...orm.WritableField[Article]) orm.SaveOption[Article] {
	return orm.UpdateFields(fields...)
}

func ArticleUpdateFieldNames(names ...string) orm.SaveOption[Article] {
	return orm.UpdateFieldNames[Article](names...)
}

func ArticleForceInsert() orm.SaveOption[Article] {
	return orm.ForceInsert[Article]()
}

func ArticleForceUpdate() orm.SaveOption[Article] {
	return orm.ForceUpdate[Article]()
}

type ArticleCreate struct {
	title     orm.Change[string]
	published orm.Change[bool]
	summary   orm.NullableChange[string]
	slug      orm.NullableChange[string]
}

func NewArticleCreate(title string) ArticleCreate {
	return ArticleCreate{
		title: orm.Set(title),
	}
}

func (input ArticleCreate) WithTitle(value string) ArticleCreate {
	input.title = orm.Set(value)
	return input
}

func (input ArticleCreate) WithPublished(value bool) ArticleCreate {
	input.published = orm.Set(value)
	return input
}

func (input ArticleCreate) WithSummary(value string) ArticleCreate {
	input.summary = orm.SetNullable(value)
	return input
}

func (input ArticleCreate) WithSummaryNull() ArticleCreate {
	input.summary = orm.SetNull[string]()
	return input
}

func (input ArticleCreate) WithSlug(value string) ArticleCreate {
	input.slug = orm.SetNullable(value)
	return input
}

func (input ArticleCreate) WithSlugNull() ArticleCreate {
	input.slug = orm.SetNull[string]()
	return input
}

func (input ArticleCreate) BuildCreate() orm.Mutation[Article] {
	var value Article
	assignments := make([]query.Assignment, 0, 4)
	changedTitle, changedTitleSet := input.title.Get()
	if !changedTitleSet {
		return orm.InvalidMutation[Article](&query.Error{
			Category: query.CategoryField,
			Code:     query.CodeRequiredField,
			Field:    "title",
			Detail:   "required create field is omitted",
		})
	}
	value.Title = changedTitle
	assignments = append(assignments, query.NewAssignment(query.NewFieldRef("title", "title", query.FieldString, false), query.String(changedTitle)))
	changedPublished, changedPublishedSet := input.published.Get()
	if !changedPublishedSet {
		changedPublished = false
	}
	value.Published = changedPublished
	assignments = append(assignments, query.NewAssignment(query.NewFieldRef("published", "published", query.FieldBoolean, false), query.Boolean(changedPublished)))
	changedSummary, changedSummaryState := input.summary.Get()
	switch changedSummaryState {
	case orm.NullableChangeUnset:
		value.Summary = nil
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("summary", "summary", query.FieldString, true), query.Null()))
	case orm.NullableChangeValue:
		storedSummary := changedSummary
		value.Summary = &storedSummary
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("summary", "summary", query.FieldString, true), query.String(changedSummary)))
	case orm.NullableChangeNull:
		value.Summary = nil
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("summary", "summary", query.FieldString, true), query.Null()))
	default:
		return orm.InvalidMutation[Article](&query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Field:    "summary",
			Detail:   "unknown nullable change state",
		})
	}
	changedSlug, changedSlugState := input.slug.Get()
	switch changedSlugState {
	case orm.NullableChangeUnset:
		value.Slug = nil
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("slug", "slug", query.FieldString, true), query.Null()))
	case orm.NullableChangeValue:
		storedSlug := changedSlug
		value.Slug = &storedSlug
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("slug", "slug", query.FieldString, true), query.String(changedSlug)))
	case orm.NullableChangeNull:
		value.Slug = nil
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("slug", "slug", query.FieldString, true), query.Null()))
	default:
		return orm.InvalidMutation[Article](&query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Field:    "slug",
			Detail:   "unknown nullable change state",
		})
	}
	return orm.NewCreateMutation(value, "godj_conformance_article", assignments)
}

type ArticlePatch struct {
	title     orm.Change[string]
	published orm.Change[bool]
	summary   orm.NullableChange[string]
	slug      orm.NullableChange[string]
}

func (input ArticlePatch) WithTitle(value string) ArticlePatch {
	input.title = orm.Set(value)
	return input
}

func (input ArticlePatch) WithPublished(value bool) ArticlePatch {
	input.published = orm.Set(value)
	return input
}

func (input ArticlePatch) WithSummary(value string) ArticlePatch {
	input.summary = orm.SetNullable(value)
	return input
}

func (input ArticlePatch) WithSummaryNull() ArticlePatch {
	input.summary = orm.SetNull[string]()
	return input
}

func (input ArticlePatch) WithSlug(value string) ArticlePatch {
	input.slug = orm.SetNullable(value)
	return input
}

func (input ArticlePatch) WithSlugNull() ArticlePatch {
	input.slug = orm.SetNull[string]()
	return input
}

func (input ArticlePatch) BuildPatch(current Article) orm.Mutation[Article] {
	value := current
	assignments := make([]query.Assignment, 0, 4)
	if changedTitle, ok := input.title.Get(); ok {
		value.Title = changedTitle
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("title", "title", query.FieldString, false), query.String(changedTitle)))
	}
	if changedPublished, ok := input.published.Get(); ok {
		value.Published = changedPublished
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("published", "published", query.FieldBoolean, false), query.Boolean(changedPublished)))
	}
	changedSummary, changedSummaryState := input.summary.Get()
	switch changedSummaryState {
	case orm.NullableChangeUnset:
	case orm.NullableChangeValue:
		storedSummary := changedSummary
		value.Summary = &storedSummary
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("summary", "summary", query.FieldString, true), query.String(changedSummary)))
	case orm.NullableChangeNull:
		value.Summary = nil
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("summary", "summary", query.FieldString, true), query.Null()))
	default:
		return orm.InvalidMutation[Article](&query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Field:    "summary",
			Detail:   "unknown nullable change state",
		})
	}
	changedSlug, changedSlugState := input.slug.Get()
	switch changedSlugState {
	case orm.NullableChangeUnset:
	case orm.NullableChangeValue:
		storedSlug := changedSlug
		value.Slug = &storedSlug
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("slug", "slug", query.FieldString, true), query.String(changedSlug)))
	case orm.NullableChangeNull:
		value.Slug = nil
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("slug", "slug", query.FieldString, true), query.Null()))
	default:
		return orm.InvalidMutation[Article](&query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Field:    "slug",
			Detail:   "unknown nullable change state",
		})
	}
	return orm.NewPatchMutation(value, "godj_conformance_article", assignments)
}

func articleMetadata() ir.Model {
	return ir.Model{
		Name:    "article",
		GoName:  "Article",
		DBTable: "godj_conformance_article",
		Fields: []ir.Field{
			{
				Name:       "id",
				GoName:     "ID",
				Column:     "id",
				Kind:       ir.FieldAuto,
				PrimaryKey: true,
			},
			{
				Name:      "title",
				GoName:    "Title",
				Column:    "title",
				Kind:      ir.FieldChar,
				MaxLength: 200,
			},
			{
				Name:    "published",
				GoName:  "Published",
				Column:  "published",
				Kind:    ir.FieldBoolean,
				Default: &ir.Scalar{Kind: ir.ScalarBoolean, Boolean: false},
			},
			{
				Name:      "summary",
				GoName:    "Summary",
				Column:    "summary",
				Kind:      ir.FieldChar,
				Blank:     true,
				Nullable:  true,
				MaxLength: 200,
			},
			{
				Name:         "slug",
				GoName:       "Slug",
				Column:       "slug",
				Kind:         ir.FieldSlug,
				Blank:        true,
				Nullable:     true,
				Unique:       true,
				DBIndex:      true,
				AllowUnicode: true,
				MaxLength:    50,
			},
		},
	}
}

type GoDjAppPart0_8e1ee4fcb8b1d2cd7cda05aca0dacf291838324d8f3f6fb4bee54a4860fd3074 struct{}

type GoDjProjectSnapshot_453e0a38ed6351cf8fef6aee0e1fda9e98161f6dfa3e67e07685c6f6966c88b5 struct{}
