// Code generated by GoDj. DO NOT EDIT.

package project

import (
	context "context"
	work "github.com/progresshans/godj/conformance/identityfixture/models"
	db "github.com/progresshans/godj/db"
	accounts "github.com/progresshans/godj/identity/models"
	orm "github.com/progresshans/godj/orm"
)

const GoDjProjectRelationPrefetchGeneratorVersion = "godj-codegen-rel-prefetch-project-v1"

type AccountsGroupReversePrefetches struct {
	objects AccountsGroupReverseObjectFactory
	guards  orm.ReversePrefetch[accounts.Group, work.AccessGuard]
	notes   orm.ReversePrefetch[accounts.Group, work.AccessNote]
}

func (_prefetches AccountsGroupReversePrefetches) Guards(
	_ctx context.Context,
	_backend db.Queryer,
	_owners []accounts.Group,
) ([]*AccountsGroupReverseObject, error) {
	_snapshots := make([]accounts.Group, len(_owners))
	for _index := range _owners {
		_snapshots[_index] = (accounts.GroupDescriptor{}).CloneModel(_owners[_index])
	}
	_sets, _err := _prefetches.guards.Load(_ctx, _backend, _snapshots)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*AccountsGroupReverseObject, len(_snapshots))
	for _index := range _snapshots {
		_object, _err := _prefetches.objects.From(_backend, _snapshots[_index])
		if _err != nil {
			return nil, _err
		}
		_object.guards = _sets[_index]
		_results[_index] = _object
	}
	return _results, nil
}

func (_prefetches AccountsGroupReversePrefetches) Notes(
	_ctx context.Context,
	_backend db.Queryer,
	_owners []accounts.Group,
) ([]*AccountsGroupReverseObject, error) {
	_snapshots := make([]accounts.Group, len(_owners))
	for _index := range _owners {
		_snapshots[_index] = (accounts.GroupDescriptor{}).CloneModel(_owners[_index])
	}
	_sets, _err := _prefetches.notes.Load(_ctx, _backend, _snapshots)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*AccountsGroupReverseObject, len(_snapshots))
	for _index := range _snapshots {
		_object, _err := _prefetches.objects.From(_backend, _snapshots[_index])
		if _err != nil {
			return nil, _err
		}
		_object.notes = _sets[_index]
		_results[_index] = _object
	}
	return _results, nil
}

type AccountsPermissionReversePrefetches struct {
	objects AccountsPermissionReverseObjectFactory
	guards  orm.ReversePrefetch[accounts.Permission, work.AccessGuard]
	notes   orm.ReversePrefetch[accounts.Permission, work.AccessNote]
}

func (_prefetches AccountsPermissionReversePrefetches) Guards(
	_ctx context.Context,
	_backend db.Queryer,
	_owners []accounts.Permission,
) ([]*AccountsPermissionReverseObject, error) {
	_snapshots := make([]accounts.Permission, len(_owners))
	for _index := range _owners {
		_snapshots[_index] = (accounts.PermissionDescriptor{}).CloneModel(_owners[_index])
	}
	_sets, _err := _prefetches.guards.Load(_ctx, _backend, _snapshots)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*AccountsPermissionReverseObject, len(_snapshots))
	for _index := range _snapshots {
		_object, _err := _prefetches.objects.From(_backend, _snapshots[_index])
		if _err != nil {
			return nil, _err
		}
		_object.guards = _sets[_index]
		_results[_index] = _object
	}
	return _results, nil
}

func (_prefetches AccountsPermissionReversePrefetches) Notes(
	_ctx context.Context,
	_backend db.Queryer,
	_owners []accounts.Permission,
) ([]*AccountsPermissionReverseObject, error) {
	_snapshots := make([]accounts.Permission, len(_owners))
	for _index := range _owners {
		_snapshots[_index] = (accounts.PermissionDescriptor{}).CloneModel(_owners[_index])
	}
	_sets, _err := _prefetches.notes.Load(_ctx, _backend, _snapshots)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*AccountsPermissionReverseObject, len(_snapshots))
	for _index := range _snapshots {
		_object, _err := _prefetches.objects.From(_backend, _snapshots[_index])
		if _err != nil {
			return nil, _err
		}
		_object.notes = _sets[_index]
		_results[_index] = _object
	}
	return _results, nil
}

type AccountsUserReversePrefetches struct {
	objects AccountsUserReverseObjectFactory
	guards  orm.ReversePrefetch[accounts.User, work.Guard]
	notes   orm.ReversePrefetch[accounts.User, work.Note]
}

func (_prefetches AccountsUserReversePrefetches) Guards(
	_ctx context.Context,
	_backend db.Queryer,
	_owners []accounts.User,
) ([]*AccountsUserReverseObject, error) {
	_snapshots := make([]accounts.User, len(_owners))
	for _index := range _owners {
		_snapshots[_index] = (accounts.UserDescriptor{}).CloneModel(_owners[_index])
	}
	_sets, _err := _prefetches.guards.Load(_ctx, _backend, _snapshots)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*AccountsUserReverseObject, len(_snapshots))
	for _index := range _snapshots {
		_object, _err := _prefetches.objects.From(_backend, _snapshots[_index])
		if _err != nil {
			return nil, _err
		}
		_object.guards = _sets[_index]
		_results[_index] = _object
	}
	return _results, nil
}

func (_prefetches AccountsUserReversePrefetches) Notes(
	_ctx context.Context,
	_backend db.Queryer,
	_owners []accounts.User,
) ([]*AccountsUserReverseObject, error) {
	_snapshots := make([]accounts.User, len(_owners))
	for _index := range _owners {
		_snapshots[_index] = (accounts.UserDescriptor{}).CloneModel(_owners[_index])
	}
	_sets, _err := _prefetches.notes.Load(_ctx, _backend, _snapshots)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*AccountsUserReverseObject, len(_snapshots))
	for _index := range _snapshots {
		_object, _err := _prefetches.objects.From(_backend, _snapshots[_index])
		if _err != nil {
			return nil, _err
		}
		_object.notes = _sets[_index]
		_results[_index] = _object
	}
	return _results, nil
}

type ReversePrefetches struct {
	AccountsGroup      AccountsGroupReversePrefetches
	AccountsPermission AccountsPermissionReversePrefetches
	AccountsUser       AccountsUserReversePrefetches
}

func BindReversePrefetches() (ReversePrefetches, error) {
	_objects, _err := BindReverseObjects()
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	_prefetch0, _err := orm.BindReversePrefetch(_objects.AccountsGroup.guards)
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	_prefetch1, _err := orm.BindReversePrefetch(_objects.AccountsGroup.notes)
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	_prefetch2, _err := orm.BindReversePrefetch(_objects.AccountsPermission.guards)
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	_prefetch3, _err := orm.BindReversePrefetch(_objects.AccountsPermission.notes)
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	_prefetch4, _err := orm.BindReversePrefetch(_objects.AccountsUser.guards)
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	_prefetch5, _err := orm.BindReversePrefetch(_objects.AccountsUser.notes)
	if _err != nil {
		return ReversePrefetches{}, _err
	}
	return ReversePrefetches{
		AccountsGroup: AccountsGroupReversePrefetches{
			objects: _objects.AccountsGroup,
			guards:  _prefetch0,
			notes:   _prefetch1,
		},
		AccountsPermission: AccountsPermissionReversePrefetches{
			objects: _objects.AccountsPermission,
			guards:  _prefetch2,
			notes:   _prefetch3,
		},
		AccountsUser: AccountsUserReversePrefetches{
			objects: _objects.AccountsUser,
			guards:  _prefetch4,
			notes:   _prefetch5,
		},
	}, nil
}

var _ goDjProjectSnapshot_663a1416e0a7b58b2bb8e760b727e57310c572b5c4e99dd10912fa7ba011fce1
