package codegen

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"strconv"

	"github.com/progresshans/godj/schema/ir"
)

const ProjectRelationFacadeGeneratorVersion = "godj-codegen-rel-facade-project-current-v15"

const projectRelationFacadeInputDomain = "godj-codegen-rel-facade-project-input-current-v4"

type projectRelationFacadeModel struct {
	model       *projectRelationModel
	source      *projectRelationObjectSource
	surface     string
	rawAlias    string
	queryType   string
	collections []projectManyToMany
}

// GenerateProjectRelationFacade renders the application-facing project facade
// over the current app model and project relation surfaces.
func GenerateProjectRelationFacade(
	packageName string,
	packages []RelationObjectPackage,
) ([]byte, error) {
	if !validGeneratedPackageName(packageName) {
		return nil, fmt.Errorf("invalid generated package name %q", packageName)
	}
	canonical, err := canonicalRelationObjectPackages(packages)
	if err != nil {
		return nil, err
	}
	return generateProjectCompanion(packageName, newRelationProjectPlan(canonical), companionFacade)
}

func generateProjectRelationFacade(packageName string, plan *relationProjectPlan) ([]byte, error) {
	canonical := plan.apps
	if err := validateProjectRelationFacadeImports(canonical); err != nil {
		return nil, err
	}
	models, sources, err := plan.objectSurface()
	if err != nil {
		return nil, err
	}
	collections, _, err := buildProjectManyToMany(plan)
	if err != nil {
		return nil, err
	}
	facadeModels := buildProjectRelationFacadeSurface(models, sources, collections)
	hasPrefetch := len(collections) > 0 || projectRelationFacadeHasRelationSources(facadeModels)
	if err := validateProjectRelationFacadeFields(facadeModels); err != nil {
		return nil, err
	}
	inputHash := projectRelationFacadeInputSHA256(packageName, canonical)

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by GoDj. DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	fmt.Fprintln(&output, "import (")
	fmt.Fprintln(&output, "\tcontext \"context\"")
	fmt.Fprintln(&output, "\treflect \"reflect\"")
	if hasPrefetch {
		fmt.Fprintln(&output, "strings \"strings\"")
	}
	for _, app := range canonical {
		fmt.Fprintf(&output, "\t%s %s\n", app.alias, strconv.Quote(app.importPath))
	}
	fmt.Fprintln(&output, "\tdb \"github.com/progresshans/godj/db\"")
	if len(facadeModels) > 0 {
		fmt.Fprintln(&output, "\torm \"github.com/progresshans/godj/orm\"")
		fmt.Fprintln(&output, "ir \"github.com/progresshans/godj/schema/ir\"")
	}
	fmt.Fprintln(&output, "\tquery \"github.com/progresshans/godj/query\"")
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"const GoDjProjectRelationFacadeGeneratorVersion = %s\n",
		strconv.Quote(ProjectRelationFacadeGeneratorVersion),
	)
	fmt.Fprintf(&output, "const GoDjProjectRelationFacadeInputSHA256 = %s\n\n", strconv.Quote(inputHash))

	renderProjectRelationFacadeFoundation(&output, len(facadeModels) > 0, projectRelationFacadeHasRelationSources(facadeModels), len(collections) > 0)
	fmt.Fprintln(&output, "type relationFacadeBindings struct {")
	for _, model := range facadeModels {
		fmt.Fprintf(&output, "%s orm.BoundModel[%s.%s]\n", model.surface, model.model.app.alias, model.model.model.GoName)
	}
	fmt.Fprintln(&output, "}")
	if hasPrefetch {
		renderProjectFacadePrefetchFoundation(&output)
	}
	for index := range facadeModels {
		renderProjectRelationFacadeModel(&output, facadeModels[index])
		if hasPrefetch {
			renderProjectFacadePrefetchPath(&output, facadeModels[index])
		}
	}
	renderProjectRelationFacadeAggregate(&output, facadeModels, len(collections) > 0)

	return output.Bytes(), nil
}

// Promoted fields come from imported model types and are not declarations in
// the project AST. Keep this cross-package check beside the facade renderer;
// direct fields, methods and package names are checked by the common finalizer.
func validateProjectRelationFacadeFields(models []projectRelationFacadeModel) error {
	for _, model := range models {
		methods := map[string]bool{"Unwrap": true, "Save": true, "MarshalJSON": true, "UnmarshalJSON": true}
		if model.source != nil {
			for _, relation := range model.source.selections {
				methods[relation.selector] = true
				if relation.reverse {
					methods["Set"+relation.selector] = true
					continue
				}
				methods["With"+relation.selector] = true
				methods["With"+relation.selector+"ID"] = true
				if relation.field.Nullable || relation.field.Relation.Cardinality == ir.RelationOneToOne {
					methods["Clear"+relation.selector] = true
				}
			}
		}
		for _, collection := range model.collections {
			methods[collection.selector] = true
		}
		for _, field := range model.model.model.Fields {
			if methods[field.GoName] {
				return fmt.Errorf("promoted schema field %s.%s conflicts with wrapper method %s", model.surface, field.Name, field.GoName)
			}
		}
	}
	return nil
}

func validateProjectRelationFacadeImports(apps []normalizedRelationPackage) error {
	if err := validateProjectRelationSelectRelatedImports(apps); err != nil {
		return err
	}
	for _, app := range apps {
		switch app.alias {
		case "int", "int64", "iota", "reflect", "strings", "sync", "true":
			return fmt.Errorf("invalid relation facade package alias %q", app.alias)
		}
		if app.importPath == "context" || app.importPath == "reflect" || app.importPath == "strings" || app.importPath == "sync" ||
			app.importPath == "github.com/progresshans/godj/schema/ir" {
			return fmt.Errorf("reserved relation facade import path %q", app.importPath)
		}
	}
	return nil
}

func buildProjectRelationFacadeSurface(
	models []*projectRelationModel,
	sources []projectRelationObjectSource,
	collections []projectManyToMany,
) []projectRelationFacadeModel {
	sourceByIdentity := make(map[ir.ModelIdentity]*projectRelationObjectSource, len(sources))
	for index := range sources {
		sourceByIdentity[sources[index].model.identity] = &sources[index]
	}
	result := make([]projectRelationFacadeModel, len(models))
	for index, model := range models {
		surface := model.app.prefix + model.model.GoName
		var owned []projectManyToMany
		for _, collection := range collections {
			if collection.owner == model {
				owned = append(owned, collection)
			}
		}
		result[index] = projectRelationFacadeModel{
			model:       model,
			source:      sourceByIdentity[model.identity],
			surface:     surface,
			rawAlias:    lowerFirst(surface) + "Model",
			queryType:   surface + "Query",
			collections: owned,
		}
	}
	return result
}

func projectRelationFacadeInputSHA256(
	packageName string,
	apps []normalizedRelationPackage,
) string {
	values := []string{
		projectRelationFacadeInputDomain,
		ProjectRelationFacadeGeneratorVersion,
		packageName,
		strconv.Itoa(len(apps)),
	}
	for _, app := range apps {
		values = append(values, app.schema.AppLabel, app.alias, app.importPath, app.hash)
	}
	var encoded bytes.Buffer
	var length [8]byte
	for _, value := range values {
		binary.BigEndian.PutUint64(length[:], uint64(len(value)))
		_, _ = encoded.Write(length[:])
		_, _ = encoded.WriteString(value)
	}
	digest := sha256.Sum256(encoded.Bytes())
	return hex.EncodeToString(digest[:])
}

func projectRelationFacadeHasRelationSources(models []projectRelationFacadeModel) bool {
	for _, model := range models {
		if model.source != nil {
			return true
		}
	}
	return false
}

func renderProjectRelationFacadeFoundation(output *bytes.Buffer, hasModels, hasRelationSources, hasCollections bool) {
	fmt.Fprintln(output, "type Backend interface {")
	fmt.Fprintln(output, "\tdb.Queryer")
	fmt.Fprintln(output, "\tdb.Mutator")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "type relationFacadeState struct {")
	fmt.Fprintln(output, "\tbackend Backend")
	fmt.Fprintln(output, "\tobjects Objects")
	fmt.Fprintln(output, "models relationFacadeBindings")
	fmt.Fprintln(output, "\tsessionScope db.SessionValidator")
	if hasCollections {
		fmt.Fprintln(output, "\tcollections Collections")
	}
	fmt.Fprintln(output, "\t_self   *relationFacadeState")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "func (_state *relationFacadeState) validate() error {")
	fmt.Fprintln(output, "\tif _state == nil || _state._self != _state {")
	fmt.Fprintln(output, "\t\treturn relationFacadeQueryInvalid(\"generated project facade state is nil, zero, or copied\")")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\tif relationFacadeNil(_state.backend) {")
	fmt.Fprintln(output, "\t\treturn relationFacadeBackendInvalid(\"backend is nil\")")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\tif _state.sessionScope != nil { return _state.sessionScope.ValidateSession(context.Background()) }")
	fmt.Fprintln(output, "\treturn nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "func relationFacadeNil(_value interface{}) bool {")
	fmt.Fprintln(output, "\tif _value == nil {")
	fmt.Fprintln(output, "\t\treturn true")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\t_reflected := reflect.ValueOf(_value)")
	fmt.Fprintln(output, "\tswitch _reflected.Kind() {")
	fmt.Fprintln(output, "\tcase reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:")
	fmt.Fprintln(output, "\t\treturn _reflected.IsNil()")
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn false")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "func relationFacadeQueryInvalid(_detail string) error {")
	fmt.Fprintln(output, "\treturn &query.Error{Category: query.CategoryQuery, Code: query.CodeInvalidPlan, Detail: _detail}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "func relationFacadeBackendInvalid(_detail string) error {")
	fmt.Fprintln(output, "\treturn &query.Error{Category: query.CategoryBackend, Code: query.CodeInvalidPlan, Detail: _detail}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	if hasModels {
		fmt.Fprintln(output, "func relationFacadeContext(_ctx context.Context) error {")
		fmt.Fprintln(output, "\tif relationFacadeNil(_ctx) {")
		fmt.Fprintln(output, "\t\treturn relationFacadeQueryInvalid(\"context is nil\")")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\treturn _ctx.Err()")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
		fmt.Fprintln(output, "func relationFacadePrimaryKeyUpdate(_field string) error {")
		fmt.Fprintln(output, "\treturn &query.Error{Category: query.CategoryModelState, Code: query.CodePrimaryKeyUpdateField, Field: _field, Detail: \"promoted primary key changed after generated wrapper construction\"}")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}
	if hasRelationSources {
		fmt.Fprint(output, `type relationFacadeSelectionInput[S any] interface {
 relationFacadeSelectionOwner() *relationFacadeState
 relationFacadeSelectionValue() orm.RelatedSelection[S]
}
type relationFacadeSelection[S,T any] struct {
 state *relationFacadeState
 selection orm.RelatedSelect[S,T]
}
func (_selector relationFacadeSelection[S,T]) relationFacadeSelectionOwner()*relationFacadeState{return _selector.state}
func (_selector relationFacadeSelection[S,T]) relationFacadeSelectionValue()orm.RelatedSelection[S]{return _selector.selection}
func (_selector relationFacadeSelection[S,T]) WithChildren(_children ...relationFacadeSelectionInput[T])relationFacadeSelection[S,T]{
 if _err:=_selector.state.validate();_err!=nil{_selector.selection=_selector.selection.WithConfigurationError(_err);return _selector}
 _inputs:=make([]orm.RelatedSelection[T],0,len(_children))
 for _,_child:=range _children{
  if relationFacadeNil(_child)||_child.relationFacadeSelectionOwner()!=_selector.state{_selector.selection=_selector.selection.WithConfigurationError(relationFacadeQueryInvalid("child selection belongs to another facade origin"));return _selector}
  _inputs=append(_inputs,_child.relationFacadeSelectionValue())
 }
 _selector.selection=_selector.selection.WithChildren(_inputs...);return _selector
}
`)
	}
	if hasRelationSources {
		fmt.Fprintln(output, "func relationFacadeUnsavedRelated(_field string) error {")
		fmt.Fprintln(output, "\treturn &query.Error{Category: query.CategoryModelState, Code: query.CodeUnsavedRelatedObject, Field: _field, Detail: \"save prohibited because the assigned related object has no primary key\"}")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
		fmt.Fprintln(output, "func relationFacadeRequiredRelated(_field string) error {")
		fmt.Fprintln(output, "\treturn &query.Error{Category: query.CategoryField, Code: query.CodeRequiredField, Field: _field, Detail: \"required relation has not been assigned\"}")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}
}

func renderProjectRelationFacadeModel(output *bytes.Buffer, model projectRelationFacadeModel) {
	renderProjectRelationFacadeQuery(output, model)
	renderProjectRelationFacadeWrapper(output, model)
	renderProjectFacadeCollections(output, model)
	renderProjectFacadePrefetch(output, model)
	if model.source != nil {
		renderProjectRelationFacadeSelector(output, model)
		renderProjectRelationFacadeEager(output, model)
	}
	renderProjectFacadeMaterialize(output, model)
}

func renderProjectRelationFacadeQuery(output *bytes.Buffer, model projectRelationFacadeModel) {
	rawType := model.model.app.alias + "." + model.model.model.GoName
	if model.source != nil {
		fmt.Fprintf(output, "type %s struct {\n", model.queryType)
		fmt.Fprintf(output, "\tRelated %sRelationSelectors\n", model.surface)
	} else {
		fmt.Fprintf(output, "type %s struct {\n", model.queryType)
	}
	if projectRelationFacadeHasPrefetch(model) {
		fmt.Fprintf(output, "Prefetch %sPrefetchSelectors\n", model.surface)
	}
	fmt.Fprintln(output, "\tstate *relationFacadeState")
	fmt.Fprintf(output, "\tquery orm.QuerySet[%s]\n", rawType)
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(
		output,
		"func new%sQuery(_state *relationFacadeState, _query orm.QuerySet[%s]) %s {\n",
		model.surface,
		rawType,
		model.queryType,
	)
	fmt.Fprintf(output, "\t_result := %s{state: _state, query: _query}\n", model.queryType)
	if model.source != nil {
		fmt.Fprintf(output, "\t_result.Related = %sRelationSelectors{\n", model.surface)
		for _, relation := range model.source.selections {
			targetType := relation.target.app.alias + "." + relation.target.model.GoName
			fmt.Fprintf(output, "%s:relationFacadeSelection[%s,%s]{state:_state},\n", relation.selector, rawType, targetType)
		}

		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "if _state!=nil{")
		for _, relation := range model.source.selections {
			fmt.Fprintf(output, "_result.Related.%s.selection=_state.objects.%s.Select%s()\n", relation.selector, model.source.surface, relation.selector)
		}
		fmt.Fprintln(output, "}")

	}
	if projectRelationFacadeHasPrefetch(model) {
		fmt.Fprintln(output, "if _state != nil {")
		if model.source != nil {
			for _, relation := range model.source.selections {
				fmt.Fprintf(output, "_result.Prefetch.%s = relationFacadeSinglePrefetch[%s,%s.%s]{state:_state,selection:%s}\n", relation.selector, rawType, relation.target.app.alias, relation.target.model.GoName, projectSinglePrefetchExpression(model, relation))
			}
		}
		for _, relation := range model.collections {
			fmt.Fprintf(output, "_result.Prefetch.%s = relationFacadeManyPrefetch[%s,%s.%s,%s.%s]{state:_state,selection:_state.collections.%s.WithChildren()}\n", relation.selector, rawType, relation.target.app.alias, relation.target.model.GoName, relation.through.app.alias, relation.through.model.GoName, relation.surface)
		}
		fmt.Fprintln(output, "}")
	}
	fmt.Fprintln(output, "\treturn _result")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) validate() error {\n", model.queryType)
	fmt.Fprintln(output, "\treturn _query.state.validate()")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) New(_value %s) (*%s, error) {\n", model.queryType, rawType, model.surface)
	fmt.Fprintln(output, "\tif _err := _query.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\treturn _query.state.wrap%s(_value, true)\n", model.surface)
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) Filter(_predicates ...orm.Predicate[%s]) %s {\n", model.queryType, rawType, model.queryType)
	fmt.Fprintln(output, "\t_query.query = _query.query.Filter(_predicates...)")
	fmt.Fprintln(output, "\treturn _query")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) OrderBy(_orderings ...orm.Ordering[%s]) %s {\n", model.queryType, rawType, model.queryType)
	fmt.Fprintln(output, "\t_query.query = _query.query.OrderBy(_orderings...)")
	fmt.Fprintln(output, "\treturn _query")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	for _, method := range []string{"Distinct", "Fresh"} {
		fmt.Fprintf(output, "func (_query %s) %s() %s {\n", model.queryType, method, model.queryType)
		fmt.Fprintf(output, "\t_query.query = _query.query.%s()\n", method)
		fmt.Fprintln(output, "\treturn _query")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}
	fmt.Fprintf(output, "func (_query %s) Limit(_limit int) (%s, error) {\n", model.queryType, model.queryType)
	fmt.Fprintln(output, "\tif _err := _query.validate(); _err != nil {")
	fmt.Fprintf(output, "\t\treturn %s{}, _err\n", model.queryType)
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\t_limited, _err := _query.query.Limit(_limit)")
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintf(output, "\t\treturn %s{}, _err\n", model.queryType)
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\t_query.query = _limited")
	fmt.Fprintln(output, "\treturn _query, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) Offset(_offset int) (%s, error) {\n", model.queryType, model.queryType)
	fmt.Fprintln(output, "\tif _err := _query.validate(); _err != nil {")
	fmt.Fprintf(output, "\t\treturn %s{}, _err\n", model.queryType)
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\t_offsetQuery, _err := _query.query.Offset(_offset)")
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintf(output, "\t\treturn %s{}, _err\n", model.queryType)
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\t_query.query = _offsetQuery")
	fmt.Fprintln(output, "\treturn _query, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) Count(_ctx context.Context) (int64, error) {\n", model.queryType)
	fmt.Fprintln(output, "\tif _err := _query.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn 0, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _query.query.Count(_ctx)")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func Select%sInto[R any](_ctx context.Context, _source %s, _projection orm.Projection[%s, R]) ([]R, error) {\n", model.surface, model.queryType, rawType)
	fmt.Fprintln(output, "\tif _err := _source.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn orm.SelectInto(_ctx, _source.query, _projection)")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func Aggregate%sInto[R any](_ctx context.Context, _source %s, _aggregate orm.Aggregate[%s, R]) (R, error) {\n", model.surface, model.queryType, rawType)
	fmt.Fprintln(output, "\tvar _zero R")
	fmt.Fprintln(output, "\tif _err := _source.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn _zero, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn orm.AggregateInto(_ctx, _source.query, _aggregate)")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) First(_ctx context.Context) (*%s, bool, error) {\n", model.queryType, model.surface)
	fmt.Fprintln(output, "\tif _err := _query.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, false, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_value, _found, _err := orm.MaterializeFirst(_ctx, _query.query, _query.state.models.%s)\n", model.surface)
	fmt.Fprintln(output, "\tif _err != nil || !_found {")
	fmt.Fprintln(output, "\t\treturn nil, _found, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_wrapped, _err := _query.state.materialize%s(_ctx, _value)\n", model.surface)
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, false, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _wrapped, true, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_query %s) All(_ctx context.Context) ([]*%s, error) {\n", model.queryType, model.surface)
	fmt.Fprintln(output, "\tif _err := _query.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_values, _err := orm.Materialize(_ctx, _query.query, _query.state.models.%s)\n", model.surface)
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_results := make([]*%s, len(_values))\n", model.surface)
	fmt.Fprintln(output, "\tfor _index := range _values {")
	fmt.Fprintf(output, "\t\t_wrapped, _err := _query.state.materialize%s(_ctx, _values[_index])\n", model.surface)
	fmt.Fprintln(output, "\t\tif _err != nil {")
	fmt.Fprintln(output, "\t\t\treturn nil, _err")
	fmt.Fprintln(output, "\t\t}")
	fmt.Fprintln(output, "\t\t_results[_index] = _wrapped")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _results, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func renderProjectRelationFacadeWrapper(output *bytes.Buffer, model projectRelationFacadeModel) {
	rawType := model.model.app.alias + "." + model.model.model.GoName
	fmt.Fprintf(output, "type %s = %s\n", model.rawAlias, rawType)
	fmt.Fprintln(output)
	fmt.Fprintf(output, "type %s struct {\n", model.surface)
	fmt.Fprintf(output, "\t%s\n", model.rawAlias)
	fmt.Fprintln(output, "\tstate                     *relationFacadeState")
	fmt.Fprintln(output, "\tprimaryKeySnapshot        int64")
	fmt.Fprintln(output, "\tprimaryKeySnapshotPresent bool")
	if model.source != nil {
		fmt.Fprintf(output, "\tobject *%s\n", model.source.objectType)
		for _, relation := range model.source.selections {
			name := lowerFirst(relation.selector)
			targetSurface := relation.target.app.prefix + relation.target.model.GoName
			fmt.Fprintf(output, "\t%sCache *orm.RelationCache[%s]\n", name, targetSurface)
			if relation.reverse {
				continue
			}
			fmt.Fprintf(output, "\t%sScalarSnapshot int64\n", name)
			fmt.Fprintf(output, "\t%sScalarPresent bool\n", name)
		}
	}
	for index, collection := range model.collections {
		fmt.Fprintf(output, "\t_manyCollection%d *orm.ManyCollectionCache[%s.%s,%s.%s]\n", index, collection.target.app.alias, collection.target.model.GoName, collection.through.app.alias, collection.through.model.GoName)
	}
	fmt.Fprintf(output, "\t_self *%s\n", model.surface)
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	fmt.Fprintf(output, "func (_state *relationFacadeState) wrap%s(_value %s, _new bool) (*%s, error) {\n", model.surface, rawType, model.surface)
	fmt.Fprintln(output, "\tif _err := _state.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_cloned := (%s.%sDescriptor{}).CloneWriteModel(_value)\n", model.model.app.alias, model.model.model.GoName)
	if model.source == nil {
		fmt.Fprintf(output, "\t_result := &%s{state: _state, %s: _cloned}\n", model.surface, model.rawAlias)
	} else {
		fmt.Fprintf(output, "\t_object, _err := _state.objects.%s.From(_state.backend, _cloned)\n", model.source.surface)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_result := &%s{state: _state, %s: _cloned, object: _object}\n", model.surface, model.rawAlias)
	}
	if model.source != nil {
		renderProjectRelationFacadeInitialCaches(output, model, "_value", "_new")
	}
	fmt.Fprintln(output, "\t_result._self = _result")
	fmt.Fprintln(output, "\tif _err := _result.relationFacadeRefreshSnapshots(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _result, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	if model.source != nil {
		fmt.Fprintf(output, "func (_state *relationFacadeState) wrap%sObject(_object *%s) (*%s, error) {\n", model.surface, model.source.objectType, model.surface)
		fmt.Fprintln(output, "\tif _err := _state.validate(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _object == nil {")
		fmt.Fprintln(output, "\t\treturn nil, relationFacadeQueryInvalid(\"generated low-level relation object is nil\")")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\t_model, _err := _object.Model()")
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_cloned := (%s.%sDescriptor{}).CloneWriteModel(_model)\n", model.model.app.alias, model.model.model.GoName)
		fmt.Fprintf(output, "\t_result := &%s{state: _state, %s: _cloned, object: _object}\n", model.surface, model.rawAlias)
		renderProjectRelationFacadeInitialCaches(output, model, "_model", "false")
		fmt.Fprintln(output, "\t_result._self = _result")
		fmt.Fprintln(output, "\tif _err := _result.relationFacadeRefreshSnapshots(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\treturn _result, nil")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}

	fmt.Fprintf(output, "func (_model *%s) validate() error {\n", model.surface)
	fmt.Fprintln(output, "\tif _model == nil || _model._self != _model {")
	fmt.Fprintln(output, "\t\treturn relationFacadeQueryInvalid(\"generated project model wrapper is nil, zero, or copied\")")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _model.state.validate()")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (%s) MarshalJSON() ([]byte, error) {\n", model.surface)
	fmt.Fprintln(output, "\treturn nil, relationFacadeQueryInvalid(\"direct JSON marshal of generated project model wrapper is unsupported\")")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (*%s) UnmarshalJSON([]byte) error {\n", model.surface)
	fmt.Fprintln(output, "\treturn relationFacadeQueryInvalid(\"direct JSON unmarshal of generated project model wrapper is unsupported\")")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	fmt.Fprintf(output, "func (_model *%s) relationFacadeCurrentPrimaryKey() (int64, bool, error) {\n", model.surface)
	fmt.Fprintf(output, "\t_value, _present := (%s.%sDescriptor{}).PrimaryKey(_model.%s)\n", model.model.app.alias, model.model.model.GoName, model.rawAlias)
	fmt.Fprintln(output, "\t_key, _ok := _value.Integer()")
	fmt.Fprintln(output, "\tif !_ok {")
	fmt.Fprintln(output, "\t\treturn 0, false, relationFacadeQueryInvalid(\"generated model descriptor returned a non-integer primary key\")")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _key, _present, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_model *%s) relationFacadePrimaryKey() (int64, bool, error) {\n", model.surface)
	fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn 0, false, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\t_key, _present, _err := _model.relationFacadeCurrentPrimaryKey()")
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn 0, false, _err")
	fmt.Fprintln(output, "\t}")
	primaryKey, _ := primaryKey(model.model.model)
	fmt.Fprintln(output, "\tif _key != _model.primaryKeySnapshot || _present != _model.primaryKeySnapshotPresent {")
	fmt.Fprintf(output, "\t\treturn 0, false, relationFacadePrimaryKeyUpdate(%s)\n", strconv.Quote(primaryKey.Name))
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn _key, _present, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_model *%s) relationFacadeRefreshSnapshots() error {\n", model.surface)
	fmt.Fprintln(output, "\t_key, _present, _err := _model.relationFacadeCurrentPrimaryKey()")
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	for index, collection := range model.collections {
		fmt.Fprintf(output, "if _model._manyCollection%d == nil || _key != _model.primaryKeySnapshot || _present != _model.primaryKeySnapshotPresent { _model._manyCollection%d = &orm.ManyCollectionCache[%s.%s,%s.%s]{} }\n", index, index, collection.target.app.alias, collection.target.model.GoName, collection.through.app.alias, collection.through.model.GoName)
	}
	fmt.Fprintln(output, "\t_model.primaryKeySnapshot = _key")
	fmt.Fprintln(output, "\t_model.primaryKeySnapshotPresent = _present")
	if model.source != nil {
		for _, relation := range model.source.relations {
			name := lowerFirst(relation.selector)
			if relation.field.Nullable {
				fmt.Fprintf(output, "\t_model.%sScalarPresent = _model.%s.%s != nil\n", name, model.rawAlias, relation.field.GoName)
				fmt.Fprintf(output, "\t_model.%sScalarSnapshot = 0\n", name)
				fmt.Fprintf(output, "\tif _model.%sScalarPresent {\n", name)
				fmt.Fprintf(output, "\t\t_model.%sScalarSnapshot = *_model.%s.%s\n", name, model.rawAlias, relation.field.GoName)
				fmt.Fprintln(output, "\t}")
				continue
			}
			fmt.Fprintf(output, "\t_model.%sScalarSnapshot = _model.%s.%s\n", name, model.rawAlias, relation.field.GoName)
		}
	}
	fmt.Fprintln(output, "\treturn nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	fmt.Fprintf(output, "func (_model *%s) Unwrap() (%s, error) {\n", model.surface, rawType)
	fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
	fmt.Fprintf(output, "\t\treturn %s{}, _err\n", rawType)
	fmt.Fprintln(output, "\t}")
	if model.source != nil {
		fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
		fmt.Fprintf(output, "\t\treturn %s{}, _err\n", rawType)
		fmt.Fprintln(output, "\t}")
		// Pass 1 gives every assigned no-PK target precedence over raw
		// required-field state, independent of declaration permutation.
		for _, relation := range model.source.relations {
			name := lowerFirst(relation.selector)
			fmt.Fprintf(output, "\t_, _, _%sPending, _%sErr := _model.%sCache.Snapshot()\n", name, name, name)
			fmt.Fprintf(output, "\tif _%sErr != nil {\n", name)
			fmt.Fprintf(output, "\t\treturn %s{}, _%sErr\n", rawType, name)
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\tif _%sPending {\n", name)
			fmt.Fprintf(output, "\t\treturn %s{}, relationFacadeUnsavedRelated(%s)\n", rawType, strconv.Quote(relation.field.Name))
			fmt.Fprintln(output, "\t}")
		}
		// Pass 2 validates required scalar presence only after all pending
		// relation ownership has been checked.
		for _, relation := range model.source.relations {
			if !relation.field.Nullable {
				name := lowerFirst(relation.selector)
				fmt.Fprintf(output, "\tif !_model.%sScalarPresent {\n", name)
				fmt.Fprintf(output, "\t\treturn %s{}, relationFacadeRequiredRelated(%s)\n", rawType, strconv.Quote(relation.field.Name))
				fmt.Fprintln(output, "\t}")
			}
		}
	} else {
		fmt.Fprintln(output, "\tif _, _, _err := _model.relationFacadePrimaryKey(); _err != nil {")
		fmt.Fprintf(output, "\t\treturn %s{}, _err\n", rawType)
		fmt.Fprintln(output, "\t}")
	}
	fmt.Fprintf(output, "\treturn (%s.%sDescriptor{}).CloneModel(_model.%s), nil\n", model.model.app.alias, model.model.model.GoName, model.rawAlias)
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	fmt.Fprintf(output, "func (_model *%s) Save(_ctx context.Context) error {\n", model.surface)
	fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\tif _err := relationFacadeContext(_ctx); _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	if model.source != nil {
		fmt.Fprintln(output, "\tif _err := _model.relationFacadePrepareSave(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn _err")
		fmt.Fprintln(output, "\t}")
	} else {
		fmt.Fprintln(output, "\tif _, _, _err := _model.relationFacadePrimaryKey(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn _err")
		fmt.Fprintln(output, "\t}")
	}
	fmt.Fprintf(output, "\tif _err := %s.%sObjects.Save(_ctx, _model.state.backend, &_model.%s); _err != nil {\n", model.model.app.alias, model.model.model.GoName, model.rawAlias)
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	if model.source != nil && len(model.source.reverse) > 0 {
		fmt.Fprintln(output, "_key,_present,_err:=_model.relationFacadeCurrentPrimaryKey();if _err!=nil{return _err}")
		fmt.Fprintln(output, "if _key!=_model.primaryKeySnapshot||_present!=_model.primaryKeySnapshotPresent{")
		fmt.Fprintf(output, "_nextObject,_err:=_model.state.objects.%s.From(_model.state.backend,_model.%s);if _err!=nil{return _err}\n", model.source.surface, model.rawAlias)
		fmt.Fprintln(output, "_model.object=_nextObject")
		fmt.Fprintln(output, "}")
	}
	fmt.Fprintln(output, "\treturn _model.relationFacadeRefreshSnapshots()")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	if model.source == nil {
		return
	}
	renderProjectRelationFacadeSourceMutationHelpers(output, model)
	renderProjectRelationFacadeReverseSetters(output, model)
	for _, relation := range model.source.selections {
		name := lowerFirst(relation.selector)
		targetSurface := relation.target.app.prefix + relation.target.model.GoName
		if relation.field.Nullable || relation.reverse {
			fmt.Fprintf(output, "func (_model *%s) %s(_ctx context.Context) (*%s, bool, error) {\n", model.surface, relation.selector, targetSurface)
			fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintln(output, "\tif _err := relationFacadeContext(_ctx); _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\t_state, _target, _, _err := _model.%sCache.Snapshot()\n", name)
			fmt.Fprintln(output, "\tif _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintln(output, "\tswitch _state {")
			fmt.Fprintln(output, "\tcase orm.RelationAssignedPresent:")
			fmt.Fprintln(output, "\t\tif _target == nil || _target.state != _model.state {")
			fmt.Fprintln(output, "\t\t\treturn nil, false, relationFacadeQueryInvalid(\"assigned relation target is nil or belongs to another facade origin\")")
			fmt.Fprintln(output, "\t\t}")
			fmt.Fprintln(output, "\t\tif _, _, _err := _target.relationFacadePrimaryKey(); _err != nil {")
			fmt.Fprintln(output, "\t\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t\t}")
			fmt.Fprintln(output, "\t\treturn _target, true, nil")
			fmt.Fprintln(output, "\tcase orm.RelationAssignedAbsent:")
			fmt.Fprintln(output, "\t\treturn nil, false, nil")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\t_value, _present, _err := _model.object.%s(_ctx)\n", relation.selector)
			fmt.Fprintln(output, "\tif _err != nil || !_present {")
			fmt.Fprintln(output, "\t\tif _err == nil {")
			fmt.Fprintf(output, "\t\t\t_err = _model.%sCache.Store(orm.RelationAssignedAbsent, nil, false)\n", name)
			fmt.Fprintln(output, "\t\t}")
			fmt.Fprintln(output, "\t\treturn nil, _present, _err")
			fmt.Fprintln(output, "\t}")
			renderProjectRelationFacadeLoadedTarget(output, relation, relation.field.Nullable || relation.reverse)
			fmt.Fprintln(output, "\tif _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\tif _err := _model.%sCache.Store(orm.RelationAssignedPresent, _wrapped, false); _err != nil {\n", name)
			fmt.Fprintln(output, "\t\treturn nil, false, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintln(output, "\treturn _wrapped, true, nil")
			fmt.Fprintln(output, "}")
			fmt.Fprintln(output)
			continue
		}
		fmt.Fprintf(output, "func (_model *%s) %s(_ctx context.Context) (*%s, error) {\n", model.surface, relation.selector, targetSurface)
		fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _err := relationFacadeContext(_ctx); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_state, _target, _, _err := _model.%sCache.Snapshot()\n", name)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _state == orm.RelationAssignedPresent {")
		fmt.Fprintln(output, "\t\tif _target == nil || _target.state != _model.state {")
		fmt.Fprintln(output, "\t\t\treturn nil, relationFacadeQueryInvalid(\"assigned relation target is nil or belongs to another facade origin\")")
		fmt.Fprintln(output, "\t\t}")
		fmt.Fprintln(output, "\t\tif _, _, _err := _target.relationFacadePrimaryKey(); _err != nil {")
		fmt.Fprintln(output, "\t\t\treturn nil, _err")
		fmt.Fprintln(output, "\t\t}")
		fmt.Fprintln(output, "\t\treturn _target, nil")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\tif !_model.%sScalarPresent {\n", name)
		fmt.Fprintf(output, "\t\treturn nil, relationFacadeRequiredRelated(%s)\n", strconv.Quote(relation.field.Name))
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_value, _err := _model.object.%s(_ctx)\n", relation.selector)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		renderProjectRelationFacadeLoadedTarget(output, relation, relation.field.Nullable || relation.reverse)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\tif _err := _model.%sCache.Store(orm.RelationAssignedPresent, _wrapped, false); _err != nil {\n", name)
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\treturn _wrapped, nil")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)
	}
}

func renderProjectRelationFacadeInitialCaches(output *bytes.Buffer, model projectRelationFacadeModel, raw, newModel string) {
	for _, relation := range model.source.selections {
		name := lowerFirst(relation.selector)
		targetSurface := relation.target.app.prefix + relation.target.model.GoName
		fmt.Fprintf(output, "\t_result.%sCache = orm.NewRelationCache[%s]()\n", name, targetSurface)
		if relation.reverse {
			continue
		}
		if relation.field.Nullable {
			fmt.Fprintf(output, "\t_result.%sScalarPresent = %s.%s != nil\n", name, raw, relation.field.GoName)
			fmt.Fprintf(output, "\tif %s.%s == nil {\n", raw, relation.field.GoName)
			fmt.Fprintf(output, "\t\t_ = _result.%sCache.Store(orm.RelationAssignedAbsent, nil, false)\n", name)
			fmt.Fprintln(output, "\t}")
			continue
		}
		if newModel != "false" {
			fmt.Fprintf(output, "\t_result.%sScalarPresent = !%s || %s.%s != 0\n", name, newModel, raw, relation.field.GoName)
		} else {
			fmt.Fprintf(output, "\t_result.%sScalarPresent = true\n", name)
		}
	}
}

func renderProjectRelationFacadeSourceMutationHelpers(output *bytes.Buffer, model projectRelationFacadeModel) {
	rawType := model.model.app.alias + "." + model.model.model.GoName
	descriptor := model.model.app.alias + "." + model.model.model.GoName + "Descriptor"

	fmt.Fprintf(output, "func (_model *%s) relationFacadeDerived(_value %s) (*%s, error) {\n", model.surface, rawType, model.surface)
	fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_value = (%s{}).CloneWriteModel(_value)\n", descriptor)
	fmt.Fprintf(output, "\t_object, _err := _model.state.objects.%s.From(_model.state.backend, _value)\n", model.source.surface)
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn nil, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_result := &%s{state: _model.state, %s: _value, object: _object}\n", model.surface, model.rawAlias)
	fmt.Fprintln(output, "\t_result.primaryKeySnapshot = _model.primaryKeySnapshot")
	fmt.Fprintln(output, "\t_result.primaryKeySnapshotPresent = _model.primaryKeySnapshotPresent")
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\t_result.%sScalarSnapshot = _model.%sScalarSnapshot\n", name, name)
		fmt.Fprintf(output, "\t_result.%sScalarPresent = _model.%sScalarPresent\n", name, name)
		fmt.Fprintf(output, "\t_result.%sCache, _err = _model.%sCache.Clone()\n", name, name)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
	}
	for _, relation := range model.source.reverse {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "_result.%sCache,_err=_model.%sCache.Clone();if _err!=nil{return nil,_err}\n", name, name)
	}
	for index, collection := range model.collections {
		fmt.Fprintf(output, "_result._manyCollection%d = &orm.ManyCollectionCache[%s.%s,%s.%s]{}\n", index, collection.target.app.alias, collection.target.model.GoName, collection.through.app.alias, collection.through.model.GoName)
	}
	fmt.Fprintln(output, "\t_result._self = _result")
	fmt.Fprintln(output, "\treturn _result, nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	if len(model.source.relations) == 0 {
		fmt.Fprintf(output, "func (_model *%s) relationFacadeReconcile()error{\n", model.surface)
		fmt.Fprintln(output, "if _,_,_err:=_model.relationFacadePrimaryKey();_err!=nil{return _err}")
		for _, relation := range model.source.reverse {
			fmt.Fprintf(output, "if _,_,_,_err:=_model.%sCache.Snapshot();_err!=nil{return _err}\n", lowerFirst(relation.selector))
		}
		fmt.Fprintln(output, "return nil\n}")
		fmt.Fprintf(output, "func (_model *%s) relationFacadePrepareSave()error{return _model.relationFacadeReconcile()}\n", model.surface)
		return
	}

	fmt.Fprintf(output, "func (_model *%s) relationFacadeReconcile() error {\n", model.surface)
	fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\tif _, _, _err := _model.relationFacadePrimaryKey(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	// Validate every cache tuple before staging any changed edge. A corrupt
	// unrelated edge must not allow a partial snapshot/cache publication.
	for _, relation := range model.source.selections {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\tif _, _, _, _err := _model.%sCache.Snapshot(); _err != nil {\n", name)
		fmt.Fprintln(output, "\t\treturn _err")
		fmt.Fprintln(output, "\t}")
	}
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		if relation.field.Nullable {
			fmt.Fprintf(output, "\t_%sCurrentPresent := _model.%s.%s != nil\n", name, model.rawAlias, relation.field.GoName)
			fmt.Fprintf(output, "\tvar _%sCurrentKey int64\n", name)
			fmt.Fprintf(output, "\tif _%sCurrentPresent {\n", name)
			fmt.Fprintf(output, "\t\t_%sCurrentKey = *_model.%s.%s\n", name, model.rawAlias, relation.field.GoName)
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\t_%sChanged := _%sCurrentPresent != _model.%sScalarPresent || (_%sCurrentPresent && _%sCurrentKey != _model.%sScalarSnapshot)\n", name, name, name, name, name, name)
			continue
		}
		fmt.Fprintf(output, "\t_%sCurrentKey := _model.%s.%s\n", name, model.rawAlias, relation.field.GoName)
		fmt.Fprintf(output, "\t_%sChanged := _%sCurrentKey != _model.%sScalarSnapshot\n", name, name, name)
		fmt.Fprintf(output, "\t_%sCurrentPresent := _model.%sScalarPresent || _%sChanged\n", name, name, name)
	}
	fmt.Fprint(output, "\t_rebuild := false")
	for _, relation := range model.source.relations {
		fmt.Fprintf(output, " || _%sChanged", lowerFirst(relation.selector))
	}
	fmt.Fprintln(output)
	fmt.Fprintln(output, "\tif !_rebuild {")
	fmt.Fprintln(output, "\t\treturn nil")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintf(output, "\t_nextModel := (%s{}).CloneWriteModel(_model.%s)\n", descriptor, model.rawAlias)
	fmt.Fprintf(output, "\t_nextObject, _err := _model.state.objects.%s.From(_model.state.backend, _nextModel)\n", model.source.surface)
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		targetSurface := relation.target.app.prefix + relation.target.model.GoName
		fmt.Fprintf(output, "\t_next%sCache := _model.%sCache\n", relation.selector, name)
		fmt.Fprintf(output, "\tif _%sChanged {\n", name)
		fmt.Fprintf(output, "\t\t_next%sCache = orm.NewRelationCache[%s]()\n", relation.selector, targetSurface)
		if relation.field.Nullable {
			fmt.Fprintf(output, "\t\tif !_%sCurrentPresent {\n", name)
			fmt.Fprintf(output, "\t\t\tif _err := _next%sCache.Store(orm.RelationAssignedAbsent, nil, false); _err != nil { return _err }\n", relation.selector)
			fmt.Fprintln(output, "\t\t}")
		}
		fmt.Fprintln(output, "\t}")
	}
	// Every fallible rebuild/cache step completed. Publish changed edges and
	// their canonical snapshots as one wrapper-state transition.
	fmt.Fprintf(output, "\t_model.%s = _nextModel\n", model.rawAlias)
	fmt.Fprintln(output, "\t_model.object = _nextObject")
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\tif _%sChanged {\n", name)
		fmt.Fprintf(output, "\t\t_model.%sCache = _next%sCache\n", name, relation.selector)
		fmt.Fprintf(output, "\t\t_model.%sScalarSnapshot = _%sCurrentKey\n", name, name)
		fmt.Fprintf(output, "\t\t_model.%sScalarPresent = _%sCurrentPresent\n", name, name)
		fmt.Fprintln(output, "\t}")
	}
	fmt.Fprintln(output, "\treturn nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	fmt.Fprintf(output, "func (_model *%s) relationFacadePrepareSave() error {\n", model.surface)
	fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
	fmt.Fprintln(output, "\t\treturn _err")
	fmt.Fprintln(output, "\t}")
	// Phase 1 validates every relation-cache tuple before target state can
	// produce a semantic error. A canonical earlier unsaved target must never
	// mask structural corruption in a later edge.
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\t_%sState, _%sTarget, _%sPending, _err := _model.%sCache.Snapshot()\n", name, name, name, name)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn _err")
		fmt.Fprintln(output, "\t}")
	}
	// Phase 2 validates every assigned target and snapshots each target key
	// exactly once. Structural target errors across all edges take precedence
	// over the later no-PK semantic pass.
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\tvar _%sKey int64\n", name)
		fmt.Fprintf(output, "\tvar _%sPresent bool\n", name)
		fmt.Fprintf(output, "\tif _%sState == orm.RelationAssignedPresent {\n", name)
		fmt.Fprintf(output, "\t\tif _%sTarget == nil || _%sTarget.state != _model.state {\n", name, name)
		fmt.Fprintln(output, "\t\t\treturn relationFacadeQueryInvalid(\"assigned relation target is nil or belongs to another facade origin\")")
		fmt.Fprintln(output, "\t\t}")
		fmt.Fprintf(output, "\t\t_%sKey, _%sPresent, _err = _%sTarget.relationFacadePrimaryKey()\n", name, name, name)
		fmt.Fprintln(output, "\t\tif _err != nil {")
		fmt.Fprintln(output, "\t\t\treturn _err")
		fmt.Fprintln(output, "\t\t}")
		fmt.Fprintln(output, "\t}")
	}
	// Phase 3 publishes the first no-PK error in canonical relation order only
	// after every assigned target passed structural validation and was sampled.
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\tif _%sState == orm.RelationAssignedPresent && !_%sPresent {\n", name, name)
		fmt.Fprintf(output, "\t\treturn relationFacadeUnsavedRelated(%s)\n", strconv.Quote(relation.field.Name))
		fmt.Fprintln(output, "\t}")
	}
	for _, relation := range model.source.relations {
		if relation.field.Nullable {
			continue
		}
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\tif _%sState == orm.RelationAssignedAbsent || (_%sState == orm.RelationUnassigned && !_model.%sScalarPresent) {\n", name, name, name)
		fmt.Fprintf(output, "\t\treturn relationFacadeRequiredRelated(%s)\n", strconv.Quote(relation.field.Name))
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\tif _%sState == orm.RelationAssignedPresent && !_%sPending && !_model.%sScalarPresent {\n", name, name, name)
		fmt.Fprintln(output, "\t\treturn relationFacadeQueryInvalid(\"assigned relation has no source scalar presence\")")
		fmt.Fprintln(output, "\t}")
	}
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\t_%sReconcile := _%sState == orm.RelationAssignedPresent && _%sPending\n", name, name, name)
	}
	fmt.Fprintf(output, "\t_nextModel := (%s{}).CloneWriteModel(_model.%s)\n", descriptor, model.rawAlias)
	fmt.Fprintln(output, "\t_rebuild := false")
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\tif _%sReconcile {\n", name)
		renderProjectRelationFacadeAssignRawKey(output, relation.field, "_nextModel."+relation.field.GoName, "_"+name+"Key", "\t\t")
		fmt.Fprintln(output, "\t\t_rebuild = true")
		fmt.Fprintln(output, "\t}")
	}
	fmt.Fprintln(output, "\tif _rebuild {")
	fmt.Fprintf(output, "\t\t_nextObject, _err := _model.state.objects.%s.From(_model.state.backend, _nextModel)\n", model.source.surface)
	fmt.Fprintln(output, "\t\tif _err != nil {")
	fmt.Fprintln(output, "\t\t\treturn _err")
	fmt.Fprintln(output, "\t\t}")
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\t\t_next%sCache := _model.%sCache\n", relation.selector, name)
		fmt.Fprintf(output, "\t\tif _%sReconcile {\n", name)
		fmt.Fprintf(output, "\t\t\t_next%sCache, _err = _model.%sCache.Clone()\n", relation.selector, name)
		fmt.Fprintln(output, "\t\t\tif _err != nil { return _err }")
		fmt.Fprintf(output, "\t\t\tif _err := _next%sCache.Store(orm.RelationAssignedPresent, _%sTarget, false); _err != nil { return _err }\n", relation.selector, name)
		fmt.Fprintln(output, "\t\t}")
	}
	fmt.Fprintf(output, "\t\t_model.%s = _nextModel\n", model.rawAlias)
	fmt.Fprintln(output, "\t\t_model.object = _nextObject")
	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, "\t\tif _%sReconcile {\n", name)
		fmt.Fprintf(output, "\t\t\t_model.%sCache = _next%sCache\n", name, relation.selector)
		fmt.Fprintf(output, "\t\t\t_model.%sScalarSnapshot = _%sKey\n", name, name)
		fmt.Fprintf(output, "\t\t\t_model.%sScalarPresent = true\n", name)
		fmt.Fprintln(output, "\t\t}")
	}
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn nil")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)

	for _, relation := range model.source.relations {
		name := lowerFirst(relation.selector)
		targetSurface := relation.target.app.prefix + relation.target.model.GoName
		fmt.Fprintf(output, "func (_model *%s) With%s(_target *%s) (*%s, error) {\n", model.surface, relation.selector, targetSurface, model.surface)
		fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _err := _target.validate(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _target.state != _model.state {")
		fmt.Fprintln(output, "\t\treturn nil, relationFacadeQueryInvalid(\"relation target belongs to another facade origin\")")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\t_key, _present, _err := _target.relationFacadePrimaryKey()")
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_value := (%s{}).CloneWriteModel(_model.%s)\n", descriptor, model.rawAlias)
		fmt.Fprintln(output, "\tif _present {")
		renderProjectRelationFacadeAssignRawKey(output, relation.field, "_value."+relation.field.GoName, "_key", "\t\t")
		fmt.Fprintln(output, "\t} else {")
		renderProjectRelationFacadeClearRawKey(output, relation.field, "_value."+relation.field.GoName, "\t\t")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\t_result, _err := _model.relationFacadeDerived(_value)")
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_result.%sScalarSnapshot = _key\n", name)
		fmt.Fprintf(output, "\t_result.%sScalarPresent = _present\n", name)
		fmt.Fprintf(output, "\tif _err := _result.%sCache.Store(orm.RelationAssignedPresent, _target, !_present); _err != nil {\n", name)
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\treturn _result, nil")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)

		scalarField := relation.field
		scalarField.Nullable = false
		fmt.Fprintf(output, "func (_model *%s) With%sID(_key %s) (*%s, error) {\n", model.surface, relation.selector, goType(scalarField), model.surface)
		fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_value := (%s{}).CloneWriteModel(_model.%s)\n", descriptor, model.rawAlias)
		fmt.Fprintf(output, "\t_, _, _pending, _err := _model.%sCache.Snapshot()\n", name)
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		if relation.field.Nullable {
			fmt.Fprintln(output, "\t_same := !_pending && "+projectRelationFacadeRawKeyEqualExpression(relation.field, "_value."+relation.field.GoName, "_key"))
		} else {
			fmt.Fprintln(output, "\t_same := _model."+name+"ScalarPresent && !_pending && "+projectRelationFacadeRawKeyEqualExpression(relation.field, "_value."+relation.field.GoName, "_key"))
		}
		renderProjectRelationFacadeAssignRawKey(output, relation.field, "_value."+relation.field.GoName, "_key", "\t")
		fmt.Fprintln(output, "\t_result, _err := _model.relationFacadeDerived(_value)")
		fmt.Fprintln(output, "\tif _err != nil {")
		fmt.Fprintln(output, "\t\treturn nil, _err")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintf(output, "\t_result.%sScalarSnapshot = int64(_key)\n", name)
		fmt.Fprintf(output, "\t_result.%sScalarPresent = true\n", name)
		fmt.Fprintln(output, "\tif !_same {")
		fmt.Fprintf(output, "\t\tif _err := _result.%sCache.Store(orm.RelationUnassigned, nil, false); _err != nil {\n", name)
		fmt.Fprintln(output, "\t\t\treturn nil, _err")
		fmt.Fprintln(output, "\t\t}")
		fmt.Fprintln(output, "\t}")
		fmt.Fprintln(output, "\treturn _result, nil")
		fmt.Fprintln(output, "}")
		fmt.Fprintln(output)

		if relation.field.Nullable || relation.field.Relation.Cardinality == ir.RelationOneToOne {
			fmt.Fprintf(output, "func (_model *%s) Clear%s() (*%s, error) {\n", model.surface, relation.selector, model.surface)
			fmt.Fprintln(output, "\tif _err := _model.validate(); _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintln(output, "\tif _err := _model.relationFacadeReconcile(); _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\t_value := (%s{}).CloneWriteModel(_model.%s)\n", descriptor, model.rawAlias)
			renderProjectRelationFacadeClearRawKey(output, relation.field, "_value."+relation.field.GoName, "\t")
			fmt.Fprintln(output, "\t_result, _err := _model.relationFacadeDerived(_value)")
			fmt.Fprintln(output, "\tif _err != nil {")
			fmt.Fprintln(output, "\t\treturn nil, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintf(output, "\t_result.%sScalarSnapshot = 0\n", name)
			fmt.Fprintf(output, "\t_result.%sScalarPresent = false\n", name)
			fmt.Fprintf(output, "\tif _err := _result.%sCache.Store(orm.RelationAssignedAbsent, nil, false); _err != nil {\n", name)
			fmt.Fprintln(output, "\t\treturn nil, _err")
			fmt.Fprintln(output, "\t}")
			fmt.Fprintln(output, "\treturn _result, nil")
			fmt.Fprintln(output, "}")
			fmt.Fprintln(output)
		}
	}
}

// A reverse setter changes the two explicitly supplied wrappers in memory.
// Stage both sides, including raw-field reconciliation, before publishing either
// side. Ordinary forward With/Clear methods retain their value-derivation API.
func renderProjectRelationFacadeReverseSetters(output *bytes.Buffer, model projectRelationFacadeModel) {
	for _, relation := range model.source.reverse {
		targetSurface := relation.target.app.prefix + relation.target.model.GoName
		targetRaw := lowerFirst(targetSurface) + "Model"
		forward, _ := relationQuerySelector(relation.field) // Validated by the forward object surface.
		name := lowerFirst(relation.selector)
		fmt.Fprintf(output, `// Set%[1]s assigns a reverse one-to-one relation without database I/O.
// It changes this wrapper and the supplied child's forward relation in place.
// A nil target clears only an already cached child; an unloaded relation is unchanged.
// Save the affected child explicitly to persist its foreign key.
func (_model *%[2]s) Set%[1]s(_target *%[3]s) error {
 if _err:=_model.validate();_err!=nil{return _err}
 _nextOwner,_err:=_model.relationFacadeDerived(_model.%[4]s);if _err!=nil{return _err}
 if _err=_nextOwner.relationFacadeReconcile();_err!=nil{return _err}
 _changedTarget:=_target
 if _target==nil{
  _state,_cached,_,_err:=_nextOwner.%[5]sCache.Snapshot();if _err!=nil{return _err}
  if _state!=orm.RelationAssignedPresent{return nil}
  _changedTarget=_cached
 }
 var _nextTarget *%[3]s
 if _changedTarget!=nil{
  if _err=_changedTarget.validate();_err!=nil{return _err}
  if _changedTarget.state!=_model.state{return relationFacadeQueryInvalid("relation target belongs to another facade origin")}
  _candidate,_err:=_changedTarget.relationFacadeDerived(_changedTarget.%[6]s);if _err!=nil{return _err}
`, relation.selector, model.surface, targetSurface, model.rawAlias, name, targetRaw)
		if relation.target.identity == model.model.identity {
			fmt.Fprintln(output, "if _changedTarget==_model{_candidate=_nextOwner}")
		}
		fmt.Fprintf(output, `
  if _target==nil{_nextTarget,_err=_candidate.Clear%[1]s()}else{_nextTarget,_err=_candidate.With%[1]s(_model)}
  if _err!=nil{return _err}
 }
`, forward)
		if relation.target.identity == model.model.identity {
			fmt.Fprintln(output, "if _changedTarget==_model{_nextOwner=_nextTarget;_changedTarget=nil}")
		}
		fmt.Fprintf(output, `
 if _target==nil{_err=_nextOwner.%[1]sCache.Store(orm.RelationAssignedAbsent,nil,false)}else{_err=_nextOwner.%[1]sCache.Store(orm.RelationAssignedPresent,_target,false)}
 if _err!=nil{return _err}
 if _changedTarget!=nil{*_changedTarget=*_nextTarget;_changedTarget._self=_changedTarget}
 *_model=*_nextOwner
 _model._self=_model
 return nil
}
`, name)
	}
}

func renderProjectRelationFacadeAssignRawKey(output *bytes.Buffer, field ir.Field, destination, key, indent string) {
	if field.Nullable {
		fmt.Fprintf(output, "%s_relationKeyValue := %s\n", indent, key)
		fmt.Fprintf(output, "%s%s = &_relationKeyValue\n", indent, destination)
		return
	}
	fmt.Fprintf(output, "%s%s = %s\n", indent, destination, key)
}

func renderProjectRelationFacadeClearRawKey(output *bytes.Buffer, field ir.Field, destination, indent string) {
	if field.Nullable {
		fmt.Fprintf(output, "%s%s = nil\n", indent, destination)
		return
	}
	fmt.Fprintf(output, "%s%s = 0\n", indent, destination)
}

func projectRelationFacadeRawKeyEqualExpression(field ir.Field, raw, input string) string {
	if field.Nullable {
		return raw + " != nil && *" + raw + " == " + input
	}
	return raw + " == " + input
}

func renderProjectRelationFacadeSelector(output *bytes.Buffer, model projectRelationFacadeModel) {
	rawType := model.model.app.alias + "." + model.model.model.GoName
	fmt.Fprintf(output, "type %sRelationSelector = relationFacadeSelectionInput[%s]\n", model.surface, rawType)
	fmt.Fprintf(output, "type %sRelationSelectors struct {\n", model.surface)
	for _, relation := range model.source.selections {
		fmt.Fprintf(output, "%s relationFacadeSelection[%s,%s.%s]\n", relation.selector, rawType, relation.target.app.alias, relation.target.model.GoName)
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintf(output, `func (_query %[1]s) SelectRelated(_selectors ...%[2]sRelationSelector)%[2]sEagerQuery{
 if _err:=_query.validate();_err!=nil{return %[2]sEagerQuery{state:_query.state,source:_query.query,configurationErr:_err}}
 _inputs:=make([]orm.RelatedSelection[%[3]s],0,len(_selectors))
 for _,_selector:=range _selectors{
  if relationFacadeNil(_selector)||_selector.relationFacadeSelectionOwner()!=_query.state{return %[2]sEagerQuery{state:_query.state,source:_query.query,configurationErr:relationFacadeQueryInvalid("relation selector does not belong to this query")}}
  _inputs=append(_inputs,_selector.relationFacadeSelectionValue())
 }
 return _query.state.new%[2]sEagerQuery(_query.query,_inputs)
}
func (_query %[1]s) SelectRelatedPaths(_paths ...string)(%[2]sEagerQuery,error){
 if _err:=_query.validate();_err!=nil{return %[2]sEagerQuery{},_err}
 _inputs,_err:=_query.state.objects.%[2]s.selectionInputs(_paths);if _err!=nil{return %[2]sEagerQuery{},_err}
 _result:=_query.state.new%[2]sEagerQuery(_query.query,_inputs);if _result.configurationErr!=nil{return %[2]sEagerQuery{},_result.configurationErr};return _result,nil
}
`, model.queryType, model.surface, rawType)
}

func renderProjectRelationFacadeEager(output *bytes.Buffer, model projectRelationFacadeModel) {
	rawType := model.model.app.alias + "." + model.model.model.GoName
	eagerType := model.surface + "EagerQuery"
	fmt.Fprintf(output, `type %[1]s struct {
 state *relationFacadeState
 source orm.QuerySet[%[2]s]
 selections []orm.RelatedSelection[%[2]s]
 projection relationSelectQuery[%[3]s]
 configurationErr error
}
func (_state *relationFacadeState) new%[4]sEagerQuery(_source orm.QuerySet[%[2]s],_selections []orm.RelatedSelection[%[2]s])%[1]s{
 _result:=%[1]s{state:_state,source:_source}
 if _err:=_state.validate();_err!=nil{_result.configurationErr=_err;return _result}
 if len(_selections)==0{_result.configurationErr=relationFacadeQueryInvalid("relation selection is empty");return _result}
 _result.selections=append([]orm.RelatedSelection[%[2]s](nil),_selections...)
 _projection:=_state.objects.%[4]s.SelectRelated(_source).WithSelections(_result.selections...)
 _result.projection=_projection;_result.configurationErr=_projection.configurationErr;return _result
}
func (_query %[1]s) validate()error{
 if _query.configurationErr!=nil{return _query.configurationErr}
 if _err:=_query.state.validate();_err!=nil{return _err}
 if len(_query.selections)==0||relationFacadeNil(_query.projection){return relationFacadeQueryInvalid("generated eager query is zero or corrupt")}
 return nil
}
`, eagerType, rawType, model.source.objectType, model.surface)
	for _, method := range []string{"Filter", "OrderBy"} {
		paramType := "orm.Predicate[" + rawType + "]"
		if method == "OrderBy" {
			paramType = "orm.Ordering[" + rawType + "]"
		}
		fmt.Fprintf(output, `func (_query %[1]s) %[2]s(_values ...%[3]s)%[1]s{
 if _err:=_query.validate();_err!=nil{_query.configurationErr=_err;return _query}
 return _query.state.new%[4]sEagerQuery(_query.source.%[2]s(_values...),_query.selections)
}
`, eagerType, method, paramType, model.surface)
	}
	for _, method := range []string{"Distinct", "Fresh"} {
		fmt.Fprintf(output, `func (_query %[1]s) %[2]s()%[1]s{
 if _err:=_query.validate();_err!=nil{_query.configurationErr=_err;return _query}
 return _query.state.new%[3]sEagerQuery(_query.source.%[2]s(),_query.selections)
}
`, eagerType, method, model.surface)
	}
	for _, method := range []string{"Limit", "Offset"} {
		fmt.Fprintf(output, `func (_query %[1]s) %[2]s(_value int)(%[1]s,error){
 if _err:=_query.validate();_err!=nil{return %[1]s{},_err}
 _source,_err:=_query.source.%[2]s(_value);if _err!=nil{return %[1]s{},_err};return _query.state.new%[3]sEagerQuery(_source,_query.selections),nil
}
`, eagerType, method, model.surface)
	}
	fmt.Fprintf(output, `func (_query %[1]s) All(_ctx context.Context)([]*%[2]s,error){
 if _err:=_query.validate();_err!=nil{return nil,_err}
 _objects,_err:=_query.projection.All(_ctx);if _err!=nil{return nil,_err}
 _results:=make([]*%[2]s,len(_objects));for _index,_object:=range _objects{_results[_index],_err=_query.state.wrapSelected%[2]sObject(_ctx,_object);if _err!=nil{return nil,_err}};if _err:=_ctx.Err();_err!=nil{return nil,_err};return _results,nil
}
func (_query %[1]s) First(_ctx context.Context)(*%[2]s,bool,error){
 if _err:=_query.validate();_err!=nil{return nil,false,_err}
 _object,_found,_err:=_query.projection.First(_ctx);if _err!=nil||!_found{return nil,false,_err};_wrapped,_err:=_query.state.wrapSelected%[2]sObject(_ctx,_object);return _wrapped,_err==nil,_err
}
func (_query %[1]s) Count(_ctx context.Context)(int64,error){
 if _err:=relationFacadeContext(_ctx);_err!=nil{return 0,_err}
 if _err:=_query.validate();_err!=nil{return 0,_err};return _query.projection.Count(_ctx)
}
func (_state *relationFacadeState) wrapSelected%[2]sObject(_ctx context.Context,_object *%[3]s)(*%[2]s,error){
 _wrapped,_err:=_state.wrap%[2]sObject(_object);if _err!=nil{return nil,_err}
 if _object._selectedGraph==nil{return nil,relationFacadeQueryInvalid("selected object has no graph")}
`, eagerType, model.surface, model.source.objectType)
	renderProjectFacadePrefetchedCollections(output, model, "_object._selectedGraph")
	for _, relation := range model.source.selections {
		fmt.Fprintf(output, "if _has,_err:=_object._selectedGraph.HasSelection(%s);_err!=nil{return nil,_err}else if _has{\n", strconv.Quote(relation.path))
		if relation.field.Nullable || relation.reverse {
			fmt.Fprintf(output, "_,_,_err=_wrapped.%s(_ctx)\n", relation.selector)
		} else {
			fmt.Fprintf(output, "_,_err=_wrapped.%s(_ctx)\n", relation.selector)
		}
		fmt.Fprintln(output, "if _err!=nil{return nil,_err}\n}")
	}
	fmt.Fprintln(output, "if _err:=_ctx.Err();_err!=nil{return nil,_err}\nreturn _wrapped,nil\n}")
}

func renderProjectRelationFacadeAggregate(
	output *bytes.Buffer,
	models []projectRelationFacadeModel,
	hasCollections bool,
) {
	fmt.Fprintln(output, "type Models struct {")
	for _, model := range models {
		fmt.Fprintf(output, "\t%s %s\n", model.surface, model.queryType)
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "func Using(_backend Backend) (Models, error) { return usingModels(_backend, false) }")
	fmt.Fprintln(output, "// UsingSession binds provisional models to the caller-owned transaction. Return errors from its callback and publish results only after confirmed commit.")
	fmt.Fprintln(output, "func UsingSession(_session db.Session) (Models, error) { return usingModels(_session, true) }")
	fmt.Fprintln(output, "func usingModels(_backend Backend, _borrowed bool) (Models, error) {")
	if len(models) == 0 {
		fmt.Fprintln(output, "\t_objects, _err := BindObjects()")
	} else {
		fmt.Fprintln(output, "_binding,_err:=Bind();if _err!=nil{return Models{},_err}")
		fmt.Fprintln(output, "\t_objects, _err := BindObjectsIn(_binding)")
	}
	fmt.Fprintln(output, "\tif _err != nil {")
	fmt.Fprintln(output, "\t\treturn Models{}, _err")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\tif relationFacadeNil(_backend) {")
	fmt.Fprintln(output, "\t\treturn Models{}, relationFacadeBackendInvalid(\"backend is nil\")")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "_scope, _scoped := _backend.(db.SessionValidator)")
	fmt.Fprintln(output, "if _borrowed != _scoped { return Models{}, relationFacadeBackendInvalid(\"root and borrowed backend must use their matching constructor and session lifetime capability\") }")
	fmt.Fprintln(output, "if _scoped { if _err := _scope.ValidateSession(context.Background()); _err != nil { return Models{}, _err } }")
	fmt.Fprintln(output, "\t_state := &relationFacadeState{backend: _backend, objects: _objects, sessionScope: _scope}")
	boundModels := make([]*projectRelationModel, len(models))
	for i, model := range models {
		boundModels[i] = model.model
	}
	renderBoundProjectModelBindings(output, boundModels, "Models", nil)
	for _, model := range models {
		fmt.Fprintf(output, "_state.models.%s = _model%d\n", model.surface, model.model.bind)
	}
	if hasCollections {
		fmt.Fprintln(output, "_collections, _err := BindCollectionsIn(_binding); if _err != nil { return Models{}, _err }; _state.collections = _collections")
	}
	fmt.Fprintln(output, "\t_state._self = _state")
	fmt.Fprintln(output, "\treturn Models{")
	for _, model := range models {
		fmt.Fprintf(
			output,
			"\t\t%s: new%sQuery(_state, %s.%sObjects.Using(_backend)),\n",
			model.surface,
			model.surface,
			model.model.app.alias,
			model.model.model.GoName,
		)
	}
	fmt.Fprintln(output, "\t}, nil")
	fmt.Fprintln(output, "}")
}

func renderProjectRelationFacadeLoadedTarget(output *bytes.Buffer, relation projectRelationObjectEdge, nullable bool) {
	targetSurface := relation.target.app.prefix + relation.target.model.GoName
	failure := "return nil,_err"
	if nullable {
		failure = "return nil,false,_err"
	}
	fmt.Fprintf(output, `var _wrapped *%[1]s
 _graph,_selected,_err:=_model.object.%[2]s.SelectedGraph(_ctx);if _err!=nil{%[3]s}
 if _selected{
  _wrapped,_err=_model.state.materialize%[1]s(_ctx,_graph)
 }else{_wrapped,_err=_model.state.wrap%[1]s(_value,false)}
`, targetSurface, lowerFirst(relation.selector), failure)
}
