package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"

	"github.com/progresshans/godj/schema/ir"
)

const RelationProjectionGeneratorVersion = "godj-codegen-rel-projection-v1"

// GenerateRelationProjection renders the current app-local joined-projection
// scanner against the descriptor published by the main generator.
func GenerateRelationProjection(packageName string, input ir.Schema) ([]byte, error) {
	if !validGeneratedPackageName(packageName) {
		return nil, fmt.Errorf("invalid generated package name %q", packageName)
	}
	schema, err := ir.Normalize(input.Clone())
	if err != nil {
		return nil, fmt.Errorf("normalize relation projection schema: %w", err)
	}
	if err := validateGeneratedNames(schema); err != nil {
		return nil, fmt.Errorf("validate projection prerequisite names: %w", err)
	}
	if err := validateRelationMetadataNames(schema); err != nil {
		return nil, fmt.Errorf("validate projection metadata names: %w", err)
	}
	if err := validateRelationObjectNames(schema); err != nil {
		return nil, fmt.Errorf("validate relation projection object names: %w", err)
	}
	if err := validateRelationProjectionNames(schema); err != nil {
		return nil, fmt.Errorf("validate relation projection names: %w", err)
	}
	hash, err := ir.Hash(schema)
	if err != nil {
		return nil, fmt.Errorf("hash relation projection schema: %w", err)
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by GoDj. DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	fmt.Fprintln(&output, "import (")
	fmt.Fprintln(&output, "\t\"database/sql\"")
	fmt.Fprintln(&output, "\t\"github.com/progresshans/godj/orm\"")
	fmt.Fprintln(&output, "\t\"github.com/progresshans/godj/query\"")
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"const GoDjRelationProjectionGeneratorVersion = %s\n",
		strconv.Quote(RelationProjectionGeneratorVersion),
	)
	fmt.Fprintf(&output, "const GoDjRelationProjectionSchemaSHA256 = %s\n\n", strconv.Quote(hash))

	for _, model := range schema.Models {
		renderRelationProjectionModel(&output, model)
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated relation projection companion: %w", err)
	}
	return formatted, nil
}

func validateRelationProjectionNames(schema ir.Schema) error {
	packageSymbols := map[string]string{}
	add := func(symbol, owner string) error {
		if previous, exists := packageSymbols[symbol]; exists {
			return fmt.Errorf("package symbol %s for %s conflicts with %s", symbol, owner, previous)
		}
		packageSymbols[symbol] = owner
		return nil
	}

	for _, candidate := range []struct {
		symbol string
		owner  string
	}{
		{symbol: "GoDjRelationProjectionGeneratorVersion", owner: "relation projection provenance constant"},
		{symbol: "GoDjRelationProjectionSchemaSHA256", owner: "relation projection schema hash constant"},
	} {
		if err := add(candidate.symbol, candidate.owner); err != nil {
			return err
		}
	}

	for _, model := range schema.Models {
		owner := "model " + model.GoName
		for _, symbol := range []string{
			model.GoName,
			model.GoName + "Descriptor",
			model.GoName + "FieldSet",
			model.GoName + "Fields",
			model.GoName + "Objects",
		} {
			if err := add(symbol, owner); err != nil {
				return err
			}
		}
		scanType := lowerFirst(model.GoName) + "ProjectionScan"
		if err := add(scanType, "projection scan for "+model.GoName); err != nil {
			return err
		}
	}
	return nil
}

func renderRelationProjectionModel(output *bytes.Buffer, model ir.Model) {
	descriptor := model.GoName + "Descriptor"
	scanType := lowerFirst(model.GoName) + "ProjectionScan"
	key, _ := primaryKey(model)

	fmt.Fprintf(output, "var _ orm.ProjectionDescriptor[%s] = %s{}\n\n", model.GoName, descriptor)
	fmt.Fprintf(output, "func (%s) NewProjectionScan() orm.ProjectionScan[%s] {\n", descriptor, model.GoName)
	fmt.Fprintf(output, "\treturn &%s{}\n", scanType)
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "type %s struct {\n", scanType)
	for _, field := range model.Fields {
		fmt.Fprintf(output, "\t%s %s\n", relationProjectionScanField(field), relationProjectionSQLHolder(field))
	}
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "func (_scan *%s) Destinations() []any {\n", scanType)
	fmt.Fprintln(output, "\tif _scan == nil {")
	fmt.Fprintln(output, "\t\treturn nil")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "\treturn []any{")
	for _, field := range model.Fields {
		fmt.Fprintf(output, "\t\t&_scan.%s,\n", relationProjectionScanField(field))
	}
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
	fmt.Fprintf(
		output,
		"func (_scan *%s) Decode() (%s, query.Value, orm.ProjectionPresence) {\n",
		scanType,
		model.GoName,
	)
	fmt.Fprintln(output, "\tif _scan == nil {")
	fmt.Fprintf(output, "\t\treturn %s{}, query.Value{}, orm.ProjectionInvalid\n", model.GoName)
	fmt.Fprintln(output, "\t}")
	fmt.Fprint(output, "\tif ")
	for index, field := range model.Fields {
		if index > 0 {
			fmt.Fprint(output, " && ")
		}
		fmt.Fprintf(output, "!_scan.%s.Valid", relationProjectionScanField(field))
	}
	fmt.Fprintln(output, " {")
	fmt.Fprintf(output, "\t\treturn %s{}, query.Null(), orm.ProjectionAbsent\n", model.GoName)
	fmt.Fprintln(output, "\t}")
	for _, field := range model.Fields {
		if field.Nullable {
			continue
		}
		fmt.Fprintf(output, "\tif !_scan.%s.Valid {\n", relationProjectionScanField(field))
		fmt.Fprintf(output, "\t\treturn %s{}, query.Value{}, orm.ProjectionInvalid\n", model.GoName)
		fmt.Fprintln(output, "\t}")
	}
	fmt.Fprintf(output, "\t_value := %s{}\n", model.GoName)
	for _, field := range model.Fields {
		storage := "_scan." + relationProjectionScanField(field)
		if field.Nullable {
			fmt.Fprintf(output, "\tif %s.Valid {\n", storage)
			fmt.Fprintf(output, "\t\t_scanned := %s.%s\n", storage, relationProjectionSQLHolderValue(field))
			fmt.Fprintf(output, "\t\t_value.%s = &_scanned\n", field.GoName)
			fmt.Fprintln(output, "\t}")
			continue
		}
		fmt.Fprintf(output, "\t_value.%s = %s.%s\n", field.GoName, storage, relationProjectionSQLHolderValue(field))
	}
	fmt.Fprintln(output, "\t_value.godjPrimaryKeyPresent = true")
	fmt.Fprintf(
		output,
		"\treturn _value, query.Integer(_scan.%s.Int64), orm.ProjectionPresent\n",
		relationProjectionScanField(key),
	)
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output)
}

func relationProjectionScanField(field ir.Field) string {
	return "scan" + field.GoName
}

func relationProjectionSQLHolder(field ir.Field) string {
	switch field.Kind {
	case ir.FieldAuto, ir.FieldForeignKey:
		return "sql.NullInt64"
	case ir.FieldChar:
		return "sql.NullString"
	case ir.FieldBoolean:
		return "sql.NullBool"
	default:
		return "struct{}"
	}
}

func relationProjectionSQLHolderValue(field ir.Field) string {
	switch field.Kind {
	case ir.FieldAuto, ir.FieldForeignKey:
		return "Int64"
	case ir.FieldChar:
		return "String"
	case ir.FieldBoolean:
		return "Bool"
	default:
		return ""
	}
}
