package codegen_test

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/progresshans/godj/codegen"
	"github.com/progresshans/godj/schema/ir"
)

func TestGenerateRelationQueryIsDeterministicAndByteLocked(t *testing.T) {
	t.Parallel()

	_, blog := relationQueryGenerationSchemas()
	first, err := codegen.GenerateRelationQuery("blog", blog)
	if err != nil {
		t.Fatalf("GenerateRelationQuery() error = %v", err)
	}
	second, err := codegen.GenerateRelationQuery("blog", blog)
	if err != nil {
		t.Fatalf("GenerateRelationQuery() second error = %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("relation query generation is not byte deterministic")
	}

	want, err := os.ReadFile(filepath.Join("testdata", "relation_query", "blog.golden"))
	if err != nil {
		t.Fatalf("read relation query golden: %v", err)
	}
	if !bytes.Equal(first, want) {
		t.Fatalf("relation query bytes drifted\ngot:\n%s\nwant:\n%s", first, want)
	}

	normalized, err := ir.Normalize(blog)
	if err != nil {
		t.Fatalf("Normalize() error = %v", err)
	}
	hash, err := ir.Hash(normalized)
	if err != nil {
		t.Fatalf("Hash() error = %v", err)
	}
	for _, fragment := range [][]byte{
		[]byte(`const GoDjRelationQueryGeneratorVersion = "godj-codegen-rel-query-v1"`),
		[]byte(hash),
		[]byte(`"database/sql"`),
		[]byte("type PostDescriptor struct{}"),
		[]byte("var _ orm.ModelDescriptor[Post] = PostDescriptor{}"),
		[]byte("var scanReviewerID sql.NullInt64"),
		[]byte("row.Scan(&value.ID, &value.Title, &value.AuthorID, &scanReviewerID)"),
		[]byte("cloned := *value.ReviewerID"),
		[]byte("type PostFieldSet struct"),
		[]byte("ID    orm.IntegerField[Post]"),
		[]byte("Title orm.StringField[Post]"),
		[]byte("var PostObjects = orm.NewManager[Post](PostDescriptor{})"),
	} {
		if !bytes.Contains(first, fragment) {
			t.Fatalf("relation query source does not contain %q:\n%s", fragment, first)
		}
	}
	for _, forbidden := range [][]byte{
		[]byte("AuthorID orm."),
		[]byte("ReviewerID orm."),
		[]byte("WriteDescriptor"),
		[]byte("Create"),
		[]byte("Update"),
		[]byte("Delete"),
		[]byte("Save"),
		[]byte("Cache"),
		[]byte("example.com/"),
	} {
		if bytes.Contains(first, forbidden) {
			t.Fatalf("relation query source contains forbidden %q:\n%s", forbidden, first)
		}
	}

	parsed, err := parser.ParseFile(token.NewFileSet(), "zz_godj_relation_query.go", first, 0)
	if err != nil {
		t.Fatalf("parse relation query output: %v", err)
	}
	exported := make([]string, 0)
	for _, declaration := range parsed.Decls {
		switch declaration := declaration.(type) {
		case *ast.GenDecl:
			for _, specification := range declaration.Specs {
				switch specification := specification.(type) {
				case *ast.ValueSpec:
					for _, name := range specification.Names {
						if name.IsExported() {
							exported = append(exported, name.Name)
						}
					}
				case *ast.TypeSpec:
					if specification.Name.IsExported() {
						exported = append(exported, specification.Name.Name)
					}
				}
			}
		}
	}
	slices.Sort(exported)
	wantExported := []string{
		"GoDjRelationQueryGeneratorVersion",
		"GoDjRelationQuerySchemaSHA256",
		"PostDescriptor",
		"PostFieldSet",
		"PostFields",
		"PostObjects",
	}
	if !slices.Equal(exported, wantExported) {
		t.Fatalf("relation query exported declarations = %v, want %v", exported, wantExported)
	}
}

func TestGenerateRelationQueryRejectsNonV3AndExactNamespaceCollisions(t *testing.T) {
	t.Parallel()

	authors, blog := relationQueryGenerationSchemas()
	for name, input := range map[string]ir.Schema{
		"v2 schema": authors,
		"fixed relation schema symbol": func() ir.Schema {
			candidate := blog.Clone()
			candidate.Models[0].GoName = "GoDjRelationSchema"
			return candidate
		}(),
		"derived descriptor collision": {
			FormatVersion: ir.RelationFormatVersion,
			AppLabel:      "collision",
			Models: []ir.Model{
				{Name: "post", GoName: "Post"},
				{Name: "post_descriptor", GoName: "PostDescriptor"},
			},
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if _, err := codegen.GenerateRelationQuery("models", input); err == nil {
				t.Fatal("GenerateRelationQuery() accepted invalid input")
			}
		})
	}
	for _, packageName := range []string{"bad-package", "_", "for"} {
		if _, err := codegen.GenerateRelationQuery(packageName, blog); err == nil {
			t.Fatalf("GenerateRelationQuery() accepted invalid package %q", packageName)
		}
	}
}

func TestGenerateRelationQuerySnapshotsInputAndNeverWritesOnFailure(t *testing.T) {
	t.Parallel()

	_, blog := relationQueryGenerationSchemas()
	before, err := codegen.GenerateRelationQuery("blog", blog)
	if err != nil {
		t.Fatalf("GenerateRelationQuery() error = %v", err)
	}
	blog.Models[0].Fields[2].Relation.Target.AppLabel = "mutated"
	if bytes.Contains(before, []byte("mutated")) {
		t.Fatal("post-generation input mutation changed generated bytes")
	}

	directory := t.TempDir()
	sentinelPath := filepath.Join(directory, "committed.go")
	sentinel := []byte("package committed\n\nconst LastGood = true\n")
	if err := os.WriteFile(sentinelPath, sentinel, 0o644); err != nil {
		t.Fatalf("write sentinel: %v", err)
	}
	if _, err := codegen.GenerateRelationQuery("bad-package", blog); err == nil {
		t.Fatal("GenerateRelationQuery() accepted invalid package")
	}
	got, err := os.ReadFile(sentinelPath)
	if err != nil {
		t.Fatalf("read sentinel: %v", err)
	}
	if !bytes.Equal(got, sentinel) {
		t.Fatalf("pure-byte validation failure changed sentinel: %q", got)
	}
}

func relationQueryGenerationSchemas() (ir.Schema, ir.Schema) {
	authors, blog := relationGenerationSchemas()
	blog.Models[0].Fields = append(
		blog.Models[0].Fields[:1],
		append(
			[]ir.Field{{Name: "title", GoName: "Title", Kind: ir.FieldChar, MaxLength: 200}},
			blog.Models[0].Fields[1:]...,
		)...,
	)
	return authors, blog
}
