// Code generated by GoDj. DO NOT EDIT.

package project

const GoDjProjectRelationQueryGeneratorVersion = "godj-codegen-rel-query-project-v2"

type Relations struct {
}

func BindRelations() (Relations, error) {
	if _, _err := Bind(); _err != nil {
		return Relations{}, _err
	}
	return Relations{}, nil
}

var _ goDjProjectSnapshot_aee132f0dcc0191b983fdcf1e48e6c3dd902b80682ba832c17461b45941347e3
