// Code generated by GoDj. DO NOT EDIT.

package project

const GoDjProjectRelationQueryGeneratorVersion = "godj-codegen-rel-query-project-v3"

type Relations struct {
}

func BindRelations() (Relations, error) {
	if _, _err := Bind(); _err != nil {
		return Relations{}, _err
	}
	return Relations{}, nil
}

var _ goDjProjectSnapshot_bdbdb8e6f200845055dfcc42ea89f0346653c629c8e35d263b6abc2339120f87
