// Code generated by GoDj. DO NOT EDIT.

package project

import (
	models "github.com/progresshans/godj/examples/article/models"
	orm "github.com/progresshans/godj/orm"
	ir "github.com/progresshans/godj/schema/ir"
)

const GoDjProjectRelationObjectGeneratorVersion = "godj-codegen-rel-object-project-v6"

type Objects struct {
}

func BindObjects() (Objects, error) {
	_binding, _err := Bind()
	if _err != nil {
		return Objects{}, _err
	}
	return BindObjectsIn(_binding)
}

// BindObjectsIn composes typed relation factories in one caller-owned project binding.
func BindObjectsIn(_binding orm.ProjectBinding) (Objects, error) {
	_model0, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "godj_conformance", ModelName: "article"},
		models.ArticleDescriptor{},
	)
	if _err != nil {
		return Objects{}, _err
	}
	_ = _model0
	return Objects{}, nil
}

var _ goDjProjectSnapshot_51a330a205b021cb7e5c495383e0149e725e0d3b6826ece7dc6bb766c6d1f584
