// Code generated by GoDj. DO NOT EDIT.

package project

const GoDjProjectRelationReverseGeneratorVersion = "godj-codegen-rel-reverse-project-v6"

type ReverseObjects struct {
}

func BindReverseObjects() (ReverseObjects, error) {
	if _, _err := Bind(); _err != nil {
		return ReverseObjects{}, _err
	}
	return ReverseObjects{}, nil
}

var _ goDjProjectSnapshot_cce5e7d679b57716fb9756b0ac99499479f468403847f457c3cafa4a8d39670b
