// Code generated by GoDj. DO NOT EDIT.

package project

import (
	query "github.com/progresshans/godj/query"
)

const GoDjProjectRelationDeleteGeneratorVersion = "godj-codegen-rel-delete-project-v1"

type RelationDeleters struct {
}

func BindRelationDeleters() (RelationDeleters, error) {
	_binding, _err := Bind()
	if _err != nil {
		return RelationDeleters{}, _err
	}
	if len(_binding.ForwardRelations()) != 0 {
		return RelationDeleters{}, &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated relation deleter target set does not match project binding",
		}
	}
	return RelationDeleters{}, nil
}

var _ goDjProjectSnapshot_17b9c439336539c8e4c20a0e7dfc1759f669194946507096e21d77ed401506e8
