// Code generated by GoDj. DO NOT EDIT.

package project

import (
	query "github.com/progresshans/godj/query"
)

const GoDjProjectRelationDeleteGeneratorVersion = "godj-codegen-rel-delete-project-v2"

type RelationDeleters struct {
}

func BindRelationDeleters() (RelationDeleters, error) {
	_binding, _err := Bind()
	if _err != nil {
		return RelationDeleters{}, _err
	}
	if len(_binding.ForwardRelations()) != 0 {
		return RelationDeleters{}, &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated relation deleter target set does not match project binding",
		}
	}
	return RelationDeleters{}, nil
}

var _ goDjProjectSnapshot_aee132f0dcc0191b983fdcf1e48e6c3dd902b80682ba832c17461b45941347e3
