// Code generated by GoDj. DO NOT EDIT.

package project

import (
	models "github.com/progresshans/godj/examples/article/models"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		models.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_f7a157707e89563c67a5a464fe2f2a2e80400d434955d8dd72e8754c2897388a struct{}

var _ goDjProjectSnapshot_f7a157707e89563c67a5a464fe2f2a2e80400d434955d8dd72e8754c2897388a
var _ models.GoDjProjectSnapshot_f7a157707e89563c67a5a464fe2f2a2e80400d434955d8dd72e8754c2897388a
