// Code generated by GoDj. DO NOT EDIT.

package project

const GoDjProjectRelationReverseGeneratorVersion = "godj-codegen-rel-reverse-project-v1"

type ReverseRelations struct {
}

func BindReverseRelations() (ReverseRelations, error) {
	if _, _err := Bind(); _err != nil {
		return ReverseRelations{}, _err
	}
	return ReverseRelations{}, nil
}

type ReverseObjects struct {
}

func BindReverseObjects() (ReverseObjects, error) {
	if _, _err := Bind(); _err != nil {
		return ReverseObjects{}, _err
	}
	return ReverseObjects{}, nil
}

var _ goDjProjectSnapshot_6c8d2f01224559e06502d1d03718cf64f80186e76745bf945e8734338db986d5
