// Code generated by GoDj. DO NOT EDIT.

package authors

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "6917458cd4b40e55f3155e604d04508c12cffad5fccc3f8dca76065c38d35e79"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "authors",
		Models: []ir.Model{
			{
				Name:    "author",
				GoName:  "Author",
				DBTable: "authors_author",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
				},
			},
		},
	}
}

type GoDjAppPart1_362b884512259a43e959f506d705c8857543627d0ddbf6f766d74e934ad28d11 struct{}
