// Code generated by GoDj. DO NOT EDIT.

package project

import (
	authors "github.com/progresshans/godj/conformance/relationdeleteproduct/authors"
	blog "github.com/progresshans/godj/conformance/relationdeleteproduct/blog"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		authors.GoDjRelationSchema(),
		blog.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_4b618261fcdec4fb126e8b20714700343543613390d1187439a315455ef5f775 struct{}

var _ goDjProjectSnapshot_4b618261fcdec4fb126e8b20714700343543613390d1187439a315455ef5f775
var _ authors.GoDjProjectSnapshot_4b618261fcdec4fb126e8b20714700343543613390d1187439a315455ef5f775
var _ blog.GoDjProjectSnapshot_4b618261fcdec4fb126e8b20714700343543613390d1187439a315455ef5f775
