// Code generated by GoDj. DO NOT EDIT.

package project

import (
	authors "github.com/progresshans/godj/conformance/relationdeleteproduct/authors"
	blog "github.com/progresshans/godj/conformance/relationdeleteproduct/blog"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		authors.GoDjRelationSchema(),
		blog.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_81534d39046a39c9d515fe4106dfcb01dd2d1ade6b0c41f25dff92ac4c004533 struct{}

var _ goDjProjectSnapshot_81534d39046a39c9d515fe4106dfcb01dd2d1ade6b0c41f25dff92ac4c004533
var _ authors.GoDjProjectSnapshot_81534d39046a39c9d515fe4106dfcb01dd2d1ade6b0c41f25dff92ac4c004533
var _ blog.GoDjProjectSnapshot_81534d39046a39c9d515fe4106dfcb01dd2d1ade6b0c41f25dff92ac4c004533
