package consumer

import (
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"testing"

	"example.com/godj-project-bundle/owners"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
)

// Typed int64 pointers preserve native null versus explicit zero and keys
// above 2^53; decoding fixtures through float64 would hide returning defects.
type bulkReferenceObject struct {
	ID      *int64  `json:"id"`
	Name    *string `json:"name"`
	Amount  int64   `json:"amount"`
	Note    *string `json:"note"`
	GroupID *int64  `json:"group_id"`
}

type bulkReferenceGroup struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
type bulkReferenceCase struct {
	Case  string
	Value struct {
		Error            string
		SQLState         *string `json:"sqlstate"`
		ParentError      *string `json:"parent_error"`
		Returned, Inputs []bulkReferenceObject
	}
	Rows      []bulkReferenceObject
	Groups    []bulkReferenceGroup
	Callbacks []string
	Commands  []string `json:"transaction_commands"`
	Inserts   int      `json:"insert_statements"`
}

func bulkReferenceObjects(values []owners.BulkReferenceItem) []bulkReferenceObject {
	result := make([]bulkReferenceObject, 0, len(values))
	for _, value := range values {
		var key *int64
		if _, present := (owners.BulkReferenceItemDescriptor{}).PrimaryKey(value); present {
			key = new(value.ID)
		}
		result = append(result, bulkReferenceObject{key, new(value.Name), value.Amount, value.Note, value.GroupID})
	}
	return result
}

func bulkReferenceError(t *testing.T, err error) string {
	t.Helper()
	if err == nil {
		return ""
	}
	if errors.Is(err, &query.Error{Code: query.CodeCommitOutcomeUnknown}) {
		return "CommitOutcomeUnknown"
	}
	var postgres *pgconn.PgError
	if errors.As(err, &postgres) {
		if postgres.Code == "21000" {
			return "ProgrammingError"
		}
		if postgres.Code == "23514" {
			return "IntegrityError"
		}
	}
	var sqlite interface{ Code() int }
	if errors.As(err, &sqlite) && sqlite.Code() == 275 {
		return "IntegrityError"
	}
	if errors.Is(err, &query.Error{Category: query.CategoryIntegrity}) {
		return "IntegrityError"
	}
	if errors.Is(err, &query.Error{Code: query.CodeInvalidValue}) || errors.Is(err, &query.Error{Code: query.CodePrimaryKeyUpdateField}) {
		return "ValueError"
	}
	t.Fatalf("unclassified bulk reference error: %v", err)
	return ""
}

func TestBulkCreateReference(t *testing.T) {
	withCollectionBackends(t, func(t *testing.T, backend collectionBackend, _ func() (collectionBackend, error), exec func(string) error, postgres bool) {
		t.Cleanup(func() { check(t, backend.Close()) })
		vendor := "sqlite"
		if postgres {
			vendor = "postgres"
		}
		data, err := os.ReadFile("bulk_create-django61-" + vendor + ".json")
		check(t, err)
		var reference struct{ Cases []bulkReferenceCase }
		check(t, json.Unmarshal(data, &reference))
		if len(reference.Cases) != 23 {
			t.Fatal("incomplete bulk reference")
		}
		for _, native := range reference.Cases {
			t.Run(native.Case, func(t *testing.T) {
				// Authored DDL retains the upstream CHECK and deferred FK. The
				// generated IR still owns model/field/query identity and codecs.
				key := `INTEGER PRIMARY KEY AUTOINCREMENT`
				if postgres {
					key = `BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
				}
				t.Cleanup(func() {
					check(t, exec(`DROP TABLE IF EXISTS "gdj_bulk_item"`))
					check(t, exec(`DROP TABLE IF EXISTS "gdj_bulk_group"`))
				})
				check(t, exec(`CREATE TABLE "gdj_bulk_group" ("id" `+key+`, "name" varchar(32) NOT NULL)`))
				check(t, exec(`CREATE TABLE "gdj_bulk_item" ("id" `+key+`, "name" varchar(32) NOT NULL UNIQUE, "amount" bigint NOT NULL, "note" varchar(32), "group_id" bigint REFERENCES "gdj_bulk_group"("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "bulk_amount_nonnegative" CHECK ("amount" >= 0))`))
				ctx := t.Context()
				group, err := owners.BulkReferenceGroupObjects.Create(ctx, backend, owners.NewBulkReferenceGroupCreate("existing group"))
				check(t, err)
				if group.ID != 1 {
					t.Fatal("reference table sequence did not reset")
				}
				probe := &bulkProbe{collectionBackend: backend}
				manager := owners.BulkReferenceItemObjects
				batch := func() []owners.BulkReferenceItem {
					return []owners.BulkReferenceItem{{Name: "c"}, {Name: "a", Amount: 2}, {Name: "b", Note: new("kept")}}
				}
				var values []owners.BulkReferenceItem
				var options []orm.BulkCreateOption[owners.BulkReferenceItem]
				policy := orm.BulkUpdateConflictNames[owners.BulkReferenceItem]([]string{"name"}, []string{"amount"})
				seed := func(value owners.BulkReferenceItem) {
					_, err := manager.BulkCreate(ctx, probe, []owners.BulkReferenceItem{value})
					check(t, err)
				}
				switch native.Case {
				case "empty":
				case "empty_invalid_conflicts":
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{orm.BulkIgnoreConflicts[owners.BulkReferenceItem](), policy}
				case "empty_invalid_batch":
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{orm.BulkBatchSize[owners.BulkReferenceItem](0)}
				case "one_batch", "batched", "filtered_query_ignores_read_shape":
					values = batch()
					if native.Case == "batched" {
						options = append(options, orm.BulkBatchSize[owners.BulkReferenceItem](2))
					}
				case "mixed_explicit_keys":
					values = []owners.BulkReferenceItem{{Name: "auto-first"}, owners.NewBulkReferenceItemWithID(9007199254740993), owners.NewBulkReferenceItemWithID(0), {Name: "auto-last"}, owners.NewBulkReferenceItemWithID(-9)}
					values[1].Name, values[2].Name, values[4].Name = "large", "zero", "negative"
					options = append(options, orm.BulkBatchSize[owners.BulkReferenceItem](2))
				case "failure_later_batch_unique":
					values = []owners.BulkReferenceItem{{Name: "one"}, {Name: "two"}, {Name: "one"}}
					options = append(options, orm.BulkBatchSize[owners.BulkReferenceItem](1))
				case "ignore_unique":
					seed(owners.BulkReferenceItem{Name: "existing", Amount: 4})
					values = []owners.BulkReferenceItem{{Name: "existing", Amount: 8}, {Name: "new", Amount: 9}}
					options = append(options, orm.BulkIgnoreConflicts[owners.BulkReferenceItem]())
				case "ignore_check":
					values = []owners.BulkReferenceItem{{Name: "invalid", Amount: -1}, {Name: "valid"}}
					options = append(options, orm.BulkIgnoreConflicts[owners.BulkReferenceItem]())
				case "ignore_not_null":
					values = []owners.BulkReferenceItem{{Name: ""}, {Name: "valid"}}
					options = append(options, orm.BulkIgnoreConflicts[owners.BulkReferenceItem]())
				case "invalid_conflict_options":
					values = []owners.BulkReferenceItem{{Name: "a"}}
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{orm.BulkIgnoreConflicts[owners.BulkReferenceItem](), policy}
				case "update_missing_fields":
					values = []owners.BulkReferenceItem{{Name: "a"}}
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{orm.BulkUpdateConflictNames[owners.BulkReferenceItem]([]string{"name"}, nil)}
				case "update_missing_target":
					values = []owners.BulkReferenceItem{{Name: "a"}}
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{orm.BulkUpdateConflictNames[owners.BulkReferenceItem](nil, []string{"amount"})}
				case "update_primary_key":
					values = []owners.BulkReferenceItem{{Name: "a"}}
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{orm.BulkUpdateConflictNames[owners.BulkReferenceItem]([]string{"name"}, []string{"id"})}
				case "update_conflicts":
					seed(owners.BulkReferenceItem{Name: "existing", Amount: 4, Note: new("retained")})
					values = []owners.BulkReferenceItem{{Name: "existing", Amount: 8, Note: new("ignored")}, {Name: "new", Amount: 9}}
					options = append(options, policy)
				case "duplicate_upsert_one_batch", "duplicate_upsert_two_batches":
					values = []owners.BulkReferenceItem{{Name: "same", Amount: 1}, {Name: "same", Amount: 2}}
					size := 2
					if native.Case == "duplicate_upsert_two_batches" {
						size = 1
					}
					options = []orm.BulkCreateOption[owners.BulkReferenceItem]{policy, orm.BulkBatchSize[owners.BulkReferenceItem](size)}
				case "existing_fk":
					values = []owners.BulkReferenceItem{{Name: "child", GroupID: new(group.ID)}}
				case "missing_fk":
					values = []owners.BulkReferenceItem{{Name: "child", GroupID: new(int64(-999))}}
				case "parent_rollback":
					values = []owners.BulkReferenceItem{{Name: "rollback"}}
				case "borrowed_failure":
					seed(owners.BulkReferenceItem{Name: "existing"})
					values = []owners.BulkReferenceItem{{Name: "private"}, {Name: "existing"}}
					options = append(options, orm.BulkBatchSize[owners.BulkReferenceItem](1))
				case "no_model_clean":
					values = []owners.BulkReferenceItem{{Name: ""}}
				default:
					t.Fatal("unhandled native bulk reference case", native.Case)
				}
				before := make([]owners.BulkReferenceItem, len(values))
				for index, value := range values {
					before[index] = (owners.BulkReferenceItemDescriptor{}).CloneWriteModel(value)
				}
				var result orm.BulkCreateResult[owners.BulkReferenceItem]
				var callErr error
				switch native.Case {
				case "ignore_not_null":
					// A non-null Go string cannot carry Python None. The dynamic
					// mutation boundary must reject NULL before any native INSERT.
					invalid := singleCreate[owners.BulkReferenceItem](func() orm.Mutation[owners.BulkReferenceItem] {
						base := owners.NewBulkReferenceItemCreate("").BuildCreate()
						assignments := base.Assignments()
						for index, assignment := range assignments {
							if assignment.Field().Name() == "name" {
								assignments[index] = query.NewAssignment(assignment.Field(), query.Null())
							}
						}
						return orm.NewCreateMutation(values[0], base.Table(), assignments)
					})
					result, callErr = manager.BulkCreateInputs(ctx, probe, []orm.CreateInput[owners.BulkReferenceItem]{invalid, owners.NewBulkReferenceItemCreate("valid")}, options...)
				case "parent_rollback":
					rollback := errors.New("authored bulk parent rollback")
					outer := probe.Atomic(ctx, func(session db.Session) error {
						result, callErr = manager.BulkCreate(ctx, session, values, options...)
						if callErr != nil {
							return callErr
						}
						return rollback
					})
					if !errors.Is(outer, rollback) {
						t.Fatal("unexpected parent outcome", outer)
					}
				case "borrowed_failure":
					check(t, probe.Atomic(ctx, func(session db.Session) error {
						_, err := owners.BulkReferenceGroupObjects.Create(ctx, session, owners.NewBulkReferenceGroupCreate("before failed child"))
						if err != nil {
							return err
						}
						result, callErr = manager.BulkCreate(ctx, session, values, options...)
						if callErr == nil {
							return errors.New("expected borrowed bulk failure")
						}
						_, err = manager.Using(session).Count(ctx)
						return err
					}))
				case "filtered_query_ignores_read_shape":
					source, err := manager.Using(probe).Filter(owners.BulkReferenceItemFields.Name.Exact("outside")).OrderBy(owners.BulkReferenceItemFields.Name.Desc()).Limit(0)
					check(t, err)
					result, callErr = source.BulkCreate(ctx, values, options...)
				default:
					result, callErr = manager.BulkCreate(ctx, probe, values, options...)
				}
				if !reflect.DeepEqual(values, before) && !(len(values) == 0 && len(before) == 0) {
					t.Fatal("bulk mutated original caller models")
				}
				if len(native.Callbacks) != 0 {
					t.Fatal("native bulk unexpectedly invoked model save/clean or signals")
				}

				// Retain native fixtures verbatim. These three different input or
				// integrity contracts are explicit Go policy, not rewritten oracles.
				wantError := native.Value.Error
				sqliteCheckDifference := native.Case == "ignore_check" && !postgres
				if sqliteCheckDifference {
					wantError = "IntegrityError"
					if native.Value.Error != "" || len(native.Rows) != 1 {
						t.Fatal("SQLite native ignore no longer suppresses CHECK")
					}
				}
				if native.Case == "ignore_not_null" {
					wantError = "ValueError"
					if native.Value.Inputs[0].Name != nil {
						t.Fatal("reference lost authored NULL name")
					}
				}
				if native.Case == "empty_invalid_conflicts" {
					wantError = "ValueError"
					if native.Value.Error != "" || len(native.Value.Returned) != 0 {
						t.Fatal("native empty input policy changed")
					}
				}
				if native.Case == "missing_fk" {
					// One native Django statement runs without explicit BEGIN here.
					// Go's owned transaction detects this deferred FK at COMMIT and
					// retains its existing conservative outcome marker and cause.
					wantError = "CommitOutcomeUnknown"
					if native.Value.Error != "IntegrityError" {
						t.Fatal("native FK rejection changed")
					}
					if !postgres {
						var sqlite interface{ Code() int }
						if !errors.As(callErr, &sqlite) || sqlite.Code() != 787 {
							t.Fatal("deferred SQLite FK cause lost", callErr)
						}
					}
				}
				if got := bulkReferenceError(t, callErr); got != wantError {
					t.Fatalf("native error differs: Go=%s Django=%s wanted Go=%s, cause=%v", got, native.Value.Error, wantError, callErr)
				}
				if callErr != nil {
					if result.Objects != nil || result.RowsAffected != 0 || result.ReturnedKeys {
						t.Fatal("failed bulk published a partial result", result)
					}
				} else {
					if got := bulkReferenceObjects(result.Objects); !reflect.DeepEqual(got, native.Value.Returned) {
						t.Fatalf("native ordered returned models differ: Go=%+v Django=%+v", got, native.Value.Returned)
					}
					wantCount := int64(len(native.Value.Returned))
					keys := native.Case != "ignore_unique"
					if native.Case == "ignore_unique" {
						wantCount = 1
					}
					if result.RowsAffected != wantCount || result.ReturnedKeys != keys {
						t.Fatal("wrong affected count or key-availability policy", result)
					}
				}
				if postgres && native.Value.SQLState != nil && native.Case != "ignore_not_null" {
					var pgError *pgconn.PgError
					if !errors.As(callErr, &pgError) || pgError.Code != *native.Value.SQLState {
						t.Fatal("native SQLSTATE cause was lost", callErr, native.Value.SQLState)
					}
				}
				stored, err := manager.Using(backend).OrderBy(owners.BulkReferenceItemFields.Name.Asc()).All(ctx)
				check(t, err)
				wantedRows := native.Rows
				if sqliteCheckDifference || native.Case == "ignore_not_null" {
					wantedRows = []bulkReferenceObject{}
				}
				if got := bulkReferenceObjects(stored); !reflect.DeepEqual(got, wantedRows) {
					t.Fatalf("native final rows differ: Go=%+v Django=%+v", got, wantedRows)
				}
				groups, err := owners.BulkReferenceGroupObjects.Using(backend).OrderBy(owners.BulkReferenceGroupFields.ID.Asc()).All(ctx)
				check(t, err)
				actualGroups := make([]bulkReferenceGroup, 0, len(groups))
				for _, value := range groups {
					actualGroups = append(actualGroups, bulkReferenceGroup{value.ID, value.Name})
				}
				wantedGroups := native.Groups
				if native.Case == "borrowed_failure" {
					if native.Value.ParentError == nil || *native.Value.ParentError != "TransactionManagementError" || len(native.Groups) != 1 {
						t.Fatal("native savepoint-free poisoning changed")
					}
					wantedGroups = append(append([]bulkReferenceGroup(nil), native.Groups...), bulkReferenceGroup{2, "before failed child"})
				}
				if !reflect.DeepEqual(actualGroups, wantedGroups) {
					t.Fatal("bulk parent outcome changed surrounding writes", actualGroups, wantedGroups)
				}
				wantInserts := native.Inserts
				if native.Case == "ignore_not_null" {
					wantInserts = 0
				}
				if native.Case == "borrowed_failure" {
					wantInserts--
				} // the ordinary Group insert is outside the bulk capability
				if len(probe.plans) != wantInserts {
					t.Fatal("native batch statement count differs", len(probe.plans), wantInserts)
				}
				wantTransactions, wantSavepoints := 1, 0
				switch native.Case {
				case "empty", "empty_invalid_conflicts", "empty_invalid_batch", "invalid_conflict_options", "update_missing_fields", "update_missing_target", "update_primary_key":
					wantTransactions = 0
				case "ignore_unique", "update_conflicts":
					wantTransactions = 2
				case "parent_rollback":
					wantSavepoints = 1
				case "borrowed_failure":
					wantTransactions, wantSavepoints = 2, 1
				}
				if probe.transactions != wantTransactions || probe.savepoints != wantSavepoints {
					t.Fatal("Go batch operation lost its explicit write scope", probe.transactions, probe.savepoints)
				}
				for _, command := range native.Commands {
					if command != "BEGIN" && command != "COMMIT" && command != "ROLLBACK" {
						t.Fatal("native bulk unexpectedly used a savepoint", native.Commands)
					}
				}
				if native.Case == "parent_rollback" && (native.Value.Inputs[0].ID == nil || values[0].ID != 0 || result.Objects[0].ID != *native.Value.Inputs[0].ID) {
					t.Fatal("caller ownership difference or provisional parent key lost")
				}
				if native.Case == "failure_later_batch_unique" {
					for _, input := range native.Value.Inputs {
						if input.ID != nil {
							t.Fatal("native failed batch published an automatic key")
						}
					}
				}
			})
		}
	})
}
