package consumer

import (
	"context"
	"errors"
	"testing"

	"example.com/godj-project-bundle/owners"
	"example.com/godj-project-bundle/project"
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/decimal"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
)

type queryUpdateProbe struct {
	collectionBackend
	reads, transactions, savepoints int
	plans                           []query.QueryUpdatePlan
}

func (probe *queryUpdateProbe) Query(ctx context.Context, plan query.Plan) (db.Rows, error) {
	probe.reads++
	return probe.collectionBackend.Query(ctx, plan)
}
func (probe *queryUpdateProbe) CheckQueryUpdate(ctx context.Context, plan query.QueryUpdatePlan) error {
	return probe.collectionBackend.(db.QueryUpdater).CheckQueryUpdate(ctx, plan)
}
func (*queryUpdateProbe) QueryUpdate(context.Context, query.QueryUpdatePlan) (int64, error) {
	return 0, errors.New("uniform update escaped transaction")
}
func (probe *queryUpdateProbe) Atomic(ctx context.Context, callback func(db.Session) error) error {
	probe.transactions++
	return probe.collectionBackend.(db.Atomic).Atomic(ctx, func(session db.Session) error { return callback(queryUpdateObservedSession{session, probe}) })
}

type queryUpdateObservedSession struct {
	db.Session
	probe *queryUpdateProbe
}

func (session queryUpdateObservedSession) ValidateSession(ctx context.Context) error {
	return session.Session.(db.SessionValidator).ValidateSession(ctx)
}
func (session queryUpdateObservedSession) Query(ctx context.Context, plan query.Plan) (db.Rows, error) {
	session.probe.reads++
	return session.Session.Query(ctx, plan)
}
func (session queryUpdateObservedSession) CheckQueryUpdate(ctx context.Context, plan query.QueryUpdatePlan) error {
	return session.Session.(db.QueryUpdater).CheckQueryUpdate(ctx, plan)
}
func (session queryUpdateObservedSession) QueryUpdate(ctx context.Context, plan query.QueryUpdatePlan) (int64, error) {
	session.probe.plans = append(session.probe.plans, plan)
	return session.Session.(db.QueryUpdater).QueryUpdate(ctx, plan)
}
func (session queryUpdateObservedSession) Savepoint(ctx context.Context, callback func(db.Session) error) error {
	session.probe.savepoints++
	return db.WithSavepoint(ctx, session.Session, func(child db.Session) error { return callback(queryUpdateObservedSession{child, session.probe}) })
}

func seedQueryUpdate(t *testing.T, backend collectionBackend, exec func(string) error, postgres bool) {
	t.Helper()
	key, boolean, floating, cost := "INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER", "REAL", "BLOB"
	if postgres {
		key, boolean, floating, cost = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "BOOLEAN", "DOUBLE PRECISION", "NUMERIC(9,2)"
	}
	for _, statement := range []string{
		`CREATE TABLE gdj_query_update_group (id ` + key + `,name varchar(32) NOT NULL)`,
		`CREATE TABLE gdj_query_update_item (id ` + key + `,name varchar(32) NOT NULL UNIQUE,amount bigint NOT NULL,other bigint NOT NULL CHECK(other>=-10),rank bigint,note varchar(32),enabled ` + boolean + ` NOT NULL,score ` + floating + ` NOT NULL,price ` + cost + ` NOT NULL,group_id bigint REFERENCES gdj_query_update_group(id) DEFERRABLE INITIALLY DEFERRED)`,
		`CREATE TABLE gdj_query_update_peer (id ` + key + `,source_id bigint NOT NULL REFERENCES gdj_query_update_item(id),target_id bigint NOT NULL REFERENCES gdj_query_update_item(id),UNIQUE(source_id,target_id))`,
	} {
		check(t, exec(statement))
	}
	t.Cleanup(func() {
		for _, name := range []string{"gdj_query_update_peer", "gdj_query_update_item", "gdj_query_update_group"} {
			check(t, exec("DROP TABLE "+name))
		}
	})
	firstGroup, secondGroup := owners.NewQueryUpdateGroupWithID(1), owners.NewQueryUpdateGroupWithID(2)
	firstGroup.Name, secondGroup.Name = "first", "second"
	_, err := owners.QueryUpdateGroupObjects.BulkCreate(t.Context(), backend, []owners.QueryUpdateGroup{firstGroup, secondGroup})
	check(t, err)
	items := []owners.QueryUpdateItem{owners.NewQueryUpdateItemWithID(1), owners.NewQueryUpdateItemWithID(2), owners.NewQueryUpdateItemWithID(3)}
	for index := range items {
		items[index].Name = []string{"one", "two", "three"}[index]
		items[index].Amount = []int64{7, -7, 0}[index]
		items[index].Other = int64(index + 2)
		items[index].Enabled = index != 1
		items[index].Score = []float64{1.25, -1.25, 0}[index]
		items[index].Price, err = decimal.Parse([]string{"1.25", "-1.25", "0"}[index])
		check(t, err)
	}
	items[0].Rank, items[0].Note, items[0].GroupID = new(int64(1)), new("first"), new(int64(1))
	items[1].Rank, items[1].Note, items[1].GroupID = new(int64(-1)), new(""), new(int64(2))
	_, err = owners.QueryUpdateItemObjects.BulkCreate(t.Context(), backend, items)
	check(t, err)
	check(t, exec(`INSERT INTO gdj_query_update_peer(source_id,target_id) VALUES (1,2),(1,3)`))
}

func TestQueryUpdate(t *testing.T) {
	withCollectionBackends(t, func(t *testing.T, backend collectionBackend, _ func() (collectionBackend, error), exec func(string) error, postgres bool) {
		t.Cleanup(func() { check(t, backend.Close()) })
		for _, name := range []string{"typed_dynamic_and_native_count", "cache_and_eager_ownership", "atomic_failure_and_parent_savepoint", "primary_key_and_empty_shapes", "all_concrete_field_references"} {
			t.Run(name, func(t *testing.T) {
				seedQueryUpdate(t, backend, exec, postgres)
				probe := &queryUpdateProbe{collectionBackend: backend}
				api, err := project.Using(probe)
				check(t, err)
				source := api.OwnersQueryUpdateItem
				fields := owners.QueryUpdateItemFields
				ctx := t.Context()
				switch name {
				case "typed_dynamic_and_native_count":
					count, err := source.Filter(fields.Amount.GreaterThan(0)).Update(ctx, orm.AssignExpression(fields.Amount, orm.Add(orm.F(fields.Amount), 1)))
					check(t, err)
					if count != 1 || probe.reads != 0 || len(probe.plans) != 1 {
						t.Fatal("update read rows or wrote repeatedly", count, probe.reads, len(probe.plans))
					}
					count, err = source.Filter(fields.Amount.LessThan(0)).UpdateDynamic(ctx, orm.DynamicUpdateInput{Field: "amount", Value: orm.DynamicF("amount").Multiply(int64(2))})
					check(t, err)
					if count != 1 {
						t.Fatal(count)
					}
					rows, err := source.OrderBy(fields.ID.Asc()).All(ctx)
					check(t, err)
					if rows[0].Amount != 8 || rows[1].Amount != -14 || rows[2].Amount != 0 {
						t.Fatal(rows)
					}
					count, err = source.Update(ctx, orm.AssignExpression(fields.Amount, orm.F(fields.Amount)))
					check(t, err)
					if count != 3 {
						t.Fatal("unchanged values missing from matched count", count)
					}
				case "cache_and_eager_ownership":
					ordered := source.OrderBy(fields.ID.Asc())
					held, err := ordered.All(ctx)
					check(t, err)
					sibling := ordered.Filter()
					siblingHeld, err := sibling.All(ctx)
					check(t, err)
					count, err := ordered.Update(ctx, orm.AssignExpression(fields.Amount, orm.Add(orm.F(fields.Amount), 1)))
					check(t, err)
					if count != 3 {
						t.Fatal(count)
					}
					after, err := ordered.All(ctx)
					check(t, err)
					again, err := sibling.All(ctx)
					check(t, err)
					if held[0].Amount != 7 || siblingHeld[0].Amount != 7 || again[0].Amount != 7 || after[0].Amount != 8 {
						t.Fatal("query cache ownership changed", held, after, again)
					}
					eager := source.SelectRelated(source.Related.Group)
					warm, err := eager.All(ctx)
					check(t, err)
					count, err = eager.Update(ctx, orm.AssignExpression(fields.Amount, orm.Add(orm.F(fields.Amount), 1)))
					check(t, err)
					if count != 3 {
						t.Fatal(count)
					}
					fresh, err := eager.All(ctx)
					check(t, err)
					if warm[0].Amount+1 != fresh[0].Amount {
						t.Fatal("eager cache was not invalidated")
					}
					prefetch := source.PrefetchRelated(source.Prefetch.Peers)
					prefetched, err := prefetch.All(ctx)
					check(t, err)
					count, err = prefetch.UpdateDynamic(ctx, orm.DynamicUpdateInput{Field: "amount", Value: orm.DynamicF("amount").Add(int64(1))})
					check(t, err)
					if count != 3 {
						t.Fatal(count)
					}
					refreshed, err := prefetch.All(ctx)
					check(t, err)
					if prefetched[0].Amount+1 != refreshed[0].Amount {
						t.Fatal("prefetch cache was not invalidated")
					}
				case "atomic_failure_and_parent_savepoint":
					count, err := source.Update(ctx, orm.AssignExpression(fields.Amount, orm.Add(orm.F(fields.Amount), 1)), orm.AssignExpression(fields.Other, orm.Subtract(orm.F(fields.Amount), 4)))
					if err == nil || count != 0 {
						t.Fatal("partial UPDATE was successful", count, err)
					}
					rows, err := source.OrderBy(fields.ID.Asc()).All(ctx)
					check(t, err)
					if rows[0].Amount != 7 || rows[1].Amount != -7 {
						t.Fatal("constraint failure changed rows", rows)
					}
					err = probe.Atomic(ctx, func(session db.Session) error {
						q := owners.QueryUpdateItemObjects.Using(session)
						if _, err := q.Filter(fields.ID.Exact(1)).Update(ctx, orm.Assign(fields.Amount, int64(99))); err != nil {
							return err
						}
						count, err := q.Update(ctx, orm.Assign(fields.Name, "duplicate"))
						if count != 0 || err == nil {
							t.Fatal(count, err)
						}
						count, err = q.Filter(fields.ID.Exact(2)).Update(ctx, orm.Assign(fields.Amount, int64(101)))
						if count != 1 {
							t.Fatal(count)
						}
						return err
					})
					check(t, err)
					rows, err = source.OrderBy(fields.ID.Asc()).All(ctx)
					check(t, err)
					if rows[0].Amount != 99 || rows[1].Amount != 101 {
						t.Fatal("failed savepoint poisoned its parent", rows)
					}
				case "primary_key_and_empty_shapes":
					check(t, exec(`DELETE FROM gdj_query_update_peer`))
					count, err := source.Update(ctx, orm.AssignExpression(fields.ID, orm.Add(orm.F(fields.ID), 10)))
					check(t, err)
					if count != 3 {
						t.Fatal(count)
					}
					rows, err := source.OrderBy(fields.ID.Asc()).All(ctx)
					check(t, err)
					if rows[0].ID != 11 || rows[2].ID != 13 {
						t.Fatal(rows)
					}
					before := len(probe.plans)
					count, err = source.Update(ctx)
					check(t, err)
					if count != 0 || len(probe.plans) != before {
						t.Fatal("empty assignments wrote")
					}
					limited, err := source.Limit(0)
					check(t, err)
					if count, err = limited.Update(ctx); count != 0 || !errors.Is(err, &query.Error{Code: query.CodeUnsupported}) {
						t.Fatal("sliced empty update accepted", count, err)
					}
				case "all_concrete_field_references":
					count, err := source.Update(ctx, orm.AssignExpression(fields.Note, orm.F(fields.Name)), orm.AssignExpression(fields.Rank, orm.F(fields.Amount)), orm.AssignExpression(fields.Score, orm.Add(orm.F(fields.Score), 0.5)), orm.AssignExpression(fields.Price, orm.F(fields.Price)), orm.AssignExpression(fields.Enabled, orm.F(fields.Enabled)), orm.AssignExpression(fields.GroupID, orm.F(fields.GroupID)))
					check(t, err)
					if count != 3 {
						t.Fatal(count)
					}
					rows, err := source.OrderBy(fields.ID.Asc()).All(ctx)
					check(t, err)
					if rows[0].Note == nil || *rows[0].Note != "one" || rows[1].Rank == nil || *rows[1].Rank != -7 || rows[0].Score != 1.75 || rows[1].Enabled || rows[2].GroupID != nil {
						t.Fatal(rows)
					}
				}
			})
		}
	})
}
