// Code generated by GoDj. DO NOT EDIT.

package project

import (
	identity "github.com/progresshans/godj/identity/models"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		identity.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_c535d5191c5a8dea5a466c1aa5840a8b602ac33e4a720f3d6ae65654375ce72b struct{}

var _ goDjProjectSnapshot_c535d5191c5a8dea5a466c1aa5840a8b602ac33e4a720f3d6ae65654375ce72b
var _ identity.GoDjProjectSnapshot_c535d5191c5a8dea5a466c1aa5840a8b602ac33e4a720f3d6ae65654375ce72b
