// Code generated by GoDj. DO NOT EDIT.

package authors

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "a4823a324f40c2598c767629714afbfafe343fe3539fb2ffc76f61701a9e34e4"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "authors",
		Models: []ir.Model{
			{
				Name:    "author",
				GoName:  "Author",
				DBTable: "authors_author",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "name",
						GoName:    "Name",
						Column:    "name",
						Kind:      ir.FieldChar,
						MaxLength: 200,
					},
				},
			},
		},
	}
}

type GoDjAppPart1_4203e017d5b0f7610fbb5b3010a4abe1295a934558d640e88f81297e8c2d38b1 struct{}

var _ GoDjProjectSnapshot_2b9e1d637f1607a754c7ca52ee86bfab32a616e834db1f1d546be8c90b6aab57
