// Code generated by GoDj. DO NOT EDIT.

package authors

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "a4823a324f40c2598c767629714afbfafe343fe3539fb2ffc76f61701a9e34e4"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "authors",
		Models: []ir.Model{
			{
				Name:    "author",
				GoName:  "Author",
				DBTable: "authors_author",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "name",
						GoName:    "Name",
						Column:    "name",
						Kind:      ir.FieldChar,
						MaxLength: 200,
					},
				},
			},
		},
	}
}

type GoDjAppPart1_07a0310cdc64db21ce0e2f1a0889d94a917f41ffd8711b33ca413ddeb88d81c9 struct{}

var _ GoDjProjectSnapshot_8b06702cdba254acbaa3690ce64116a9d5f419910e71d4baf206c9b90a00f344
