// Code generated by GoDj. DO NOT EDIT.

package authors

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/schema/ir"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v2"
const GoDjRelationObjectSchemaSHA256 = "a4823a324f40c2598c767629714afbfafe343fe3539fb2ffc76f61701a9e34e4"

var _ orm.RelationObjectDescriptor[Author] = AuthorDescriptor{}

func (AuthorDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Author] {
	return AuthorDescriptor{}
}

func (AuthorDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Author], bool) {
	return nil, false
}

var _ GoDjProjectSnapshot_6e5d1c3f227bb779117691e191e975f75de6f88a11fe47085864fd44da25766f
