package postgres

import (
	"errors"
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/query"
	"testing"

	"github.com/progresshans/godj/internal/batchtest"
)

func TestPostgresRootBatches(t *testing.T) {
	url := postgresIntegrationURL(t)
	ctx := t.Context()
	namespace := postgresMigrationIntegrationSchema(t, ctx, url)
	backend := openPostgresMigrationIntegrationBackend(t, ctx, url, namespace)
	backend.database.SetMaxOpenConns(1)
	source, _ := quoteTable(namespace, "batch_source")
	writes, _ := quoteTable(namespace, "batch_writes")
	for _, statement := range []string{"CREATE TABLE " + source + "(value BIGINT NOT NULL)", "INSERT INTO " + source + " VALUES(3),(1),(1),(4),(2)", "CREATE TABLE " + writes + "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,value BIGINT NOT NULL UNIQUE)"} {
		if _, err := backend.database.ExecContext(ctx, statement); err != nil {
			t.Fatal(err)
		}
	}
	batchtest.CheckRoot(t, backend)
	var cursors int
	if err := backend.database.QueryRowContext(ctx, "SELECT count(*) FROM pg_cursors WHERE name LIKE 'godj_batch_%'").Scan(&cursors); err != nil || cursors != 0 {
		t.Fatal("root cursor leaked to pool", cursors, err)
	}
}

func TestPostgresRootBatchUnknownCommitDiscardsCursorAndPreservesCause(t *testing.T) {
	url := postgresIntegrationURL(t)
	ctx := t.Context()
	namespace := postgresMigrationIntegrationSchema(t, ctx, url)
	backend := openPostgresMigrationIntegrationBackend(t, ctx, url, namespace)
	backend.database.SetMaxOpenConns(1)
	source, _ := quoteTable(namespace, "batch_source")
	parent, _ := quoteTable(namespace, "batch_parent")
	child, _ := quoteTable(namespace, "batch_child")
	for _, statement := range []string{"CREATE TABLE " + source + "(value BIGINT)", "INSERT INTO " + source + " VALUES(1),(2),(3)", "CREATE TABLE " + parent + "(id BIGINT PRIMARY KEY)", "CREATE TABLE " + child + "(parent_id BIGINT REFERENCES " + parent + "(id) DEFERRABLE INITIALLY DEFERRED)"} {
		if _, err := backend.database.ExecContext(ctx, statement); err != nil {
			t.Fatal(err)
		}
	}
	var originalPID int
	if err := backend.database.QueryRowContext(ctx, "SELECT pg_backend_pid()").Scan(&originalPID); err != nil {
		t.Fatal(err)
	}
	var atomicErr error
	var held db.Queryer
	scans, yields := 0, 0
	err := backend.QueryBatches(ctx, batchtest.Plan(), 2, func(row db.Row) error { scans++; var value int64; return row.Scan(&value) }, func(affinity db.Queryer) (bool, error) {
		held = affinity
		yields++
		atomicErr = affinity.(db.Atomic).Atomic(ctx, func(session db.Session) error {
			_, err := session.(*transactionSession).transaction.ExecContext(ctx, "INSERT INTO "+child+" VALUES(99)")
			return err
		})
		// Even if the caller catches the error, the failed pinned source must
		// not silently restart or report complete success.
		return true, nil
	})
	if !errors.Is(atomicErr, &query.Error{Code: query.CodeCommitOutcomeUnknown}) || !errors.Is(err, &query.Error{Code: query.CodeCommitOutcomeUnknown}) || scans != 2 || yields != 1 {
		t.Fatal("unknown commit did not stop the pinned source", scans, yields, atomicErr, err)
	}
	values, err := batchtest.Read(ctx, held, batchtest.Plan())
	if err != nil || len(values) != 3 {
		t.Fatal("retained root did not recover", values, err)
	}
	var count, pid int
	if err := backend.database.QueryRowContext(ctx, "SELECT (SELECT count(*) FROM "+child+"), pg_backend_pid()").Scan(&count, &pid); err != nil || count != 0 || pid == originalPID {
		t.Fatal("poisoned connection reused or state not reconciled", count, pid, err)
	}
}
