package postgres

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"testing"

	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/decimal"
	"github.com/progresshans/godj/duration"
	"github.com/progresshans/godj/internal/batchtest"
	"github.com/progresshans/godj/jsonvalue"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/uuid"
)

func TestPostgresSessionBatches(t *testing.T) {
	url := postgresIntegrationURL(t)
	ctx := t.Context()
	namespace := postgresMigrationIntegrationSchema(t, ctx, url)
	backend := openPostgresMigrationIntegrationBackend(t, ctx, url, namespace)
	table, _ := quoteTable(namespace, "batch_source")
	writes, _ := quoteTable(namespace, "batch_writes")
	for _, statement := range []string{
		"CREATE TABLE " + table + "(value BIGINT NOT NULL)",
		"INSERT INTO " + table + " VALUES(3),(1),(1),(4),(2)",
		"CREATE TABLE " + writes + "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value BIGINT NOT NULL)",
	} {
		if _, err := backend.database.ExecContext(ctx, statement); err != nil {
			t.Fatal(err)
		}
	}
	idle := func(borrowed db.Session) error {
		var count int
		err := borrowed.(*transactionSession).transaction.QueryRowContext(ctx, "SELECT count(*) FROM pg_cursors WHERE name LIKE 'godj_batch_%'").Scan(&count)
		if err != nil {
			return err
		}
		if count != 0 {
			return fmt.Errorf("leaked %d batch cursors", count)
		}
		return nil
	}
	for _, variant := range []struct {
		name  string
		owner batchtest.Owner
	}{
		{"ordinary", backend.Atomic}, {"coordinated", backend.CoordinatedAtomic},
		{"relation", func(ctx context.Context, callback func(db.Session) error) error {
			return backend.AtomicRelation(ctx, func(session db.RelationSession) error { return callback(session) })
		}},
		{"coordinated_relation", func(ctx context.Context, callback func(db.Session) error) error {
			return backend.CoordinatedAtomicRelation(ctx, func(session db.RelationSession) error { return callback(session) })
		}},
	} {
		t.Run(variant.name, func(t *testing.T) { batchtest.Check(t, backend, variant.owner, idle) })
	}
	t.Run("cursor_keeps_source_membership_across_writes", func(t *testing.T) {
		signal := errors.New("rollback authored source change")
		err := backend.Atomic(ctx, func(borrowed db.Session) error {
			session := borrowed.(*transactionSession)
			var got []int64
			err := session.QueryBatches(ctx, batchtest.Plan(), 2, func(row db.Row) error {
				var value int64
				if err := row.Scan(&value); err != nil {
					return err
				}
				got = append(got, value)
				return nil
			}, func(db.Queryer) (bool, error) {
				if len(got) == 2 {
					_, err := session.transaction.ExecContext(ctx, "DELETE FROM "+table+" WHERE value >= 2")
					return true, err
				}
				return true, nil
			})
			if err != nil || !reflect.DeepEqual(got, []int64{1, 1, 2, 3, 4}) {
				t.Fatalf("source was reissued: %v %v", got, err)
			}
			fresh, err := batchtest.Read(ctx, session, batchtest.Plan())
			if err != nil || !reflect.DeepEqual(fresh, []int64{1, 1}) {
				t.Fatalf("authored mutation absent: %v %v", fresh, err)
			}
			if err := idle(session); err != nil {
				return err
			}
			return signal
		})
		if !errors.Is(err, signal) {
			t.Fatal(err)
		}
	})
}

func TestPostgresBatchNativeScalarAdaptationAndParameters(t *testing.T) {
	url := postgresIntegrationURL(t)
	ctx := t.Context()
	namespace := postgresMigrationIntegrationSchema(t, ctx, url)
	backend := openPostgresMigrationIntegrationBackend(t, ctx, url, namespace)
	table, _ := quoteTable(namespace, "batch_scalars")
	for _, statement := range []string{
		"CREATE TABLE " + table + "(id BIGINT PRIMARY KEY, amount NUMERIC(30,12), elapsed INTERVAL, identifier UUID, document JSONB)",
		"INSERT INTO " + table + " VALUES(1,0,INTERVAL '0 seconds','00000000-0000-0000-0000-000000000000','null'),(2,123456789012345678.123456789012,INTERVAL '1 day 0.000002 seconds','12345678-1234-1234-1234-123456789abc','{\"items\":[null,17]}'),(3,NULL,NULL,NULL,NULL)",
	} {
		if _, err := backend.database.ExecContext(ctx, statement); err != nil {
			t.Fatal(err)
		}
	}
	id := query.NewFieldRef("id", "id", query.FieldInteger, false)
	fields := []query.FieldRef{id, query.NewDecimalFieldRef("amount", "amount", true, 30, 12), query.NewFieldRef("elapsed", "elapsed", query.FieldDuration, true), query.NewFieldRef("identifier", "identifier", query.FieldUUID, true), query.NewFieldRef("document", "document", query.FieldJSON, true)}
	plan, err := query.NewPlan("batch_scalars", fields).WithConditions(query.NewCondition(id, query.LookupGreaterThan, query.Integer(1)))
	if err != nil {
		t.Fatal(err)
	}
	plan = plan.WithOrderings(query.NewOrdering(id, query.Ascending))
	number, _ := decimal.Parse("123456789012345678.123456789012")
	elapsed, _ := duration.New(1, 2)
	identifier, _ := uuid.Parse("12345678-1234-1234-1234-123456789abc")
	document, _ := jsonvalue.Parse([]byte(`{"items":[null,17]}`))
	want := [][]any{{int64(2), number, elapsed.String(), identifier, document}, {int64(3), nil, nil, nil, nil}}
	var got [][]any
	if err := backend.Atomic(ctx, func(session db.Session) error {
		return session.(db.BatchQueryer).QueryBatches(ctx, plan, 1, func(row db.Row) error {
			values := make([]any, len(fields))
			destinations := make([]any, len(fields))
			for i := range values {
				destinations[i] = &values[i]
			}
			if err := row.Scan(destinations...); err != nil {
				return err
			}
			got = append(got, values)
			return nil
		}, func(affinity db.Queryer) (bool, error) {
			// FETCH rows must be closed before this same-connection read.
			rows, err := affinity.Query(ctx, plan)
			if err != nil {
				return false, err
			}
			return true, rows.Close()
		})
	}); err != nil || !reflect.DeepEqual(got, want) {
		t.Fatalf("cursor scalar conversion: %#v %v", got, err)
	}
}
