package postgres

import (
	"errors"
	"testing"

	"github.com/progresshans/godj/internal/bulkinserttest"
	"github.com/progresshans/godj/query"
)

func TestPostgresBulkInsertCompiler(t *testing.T) {
	bulkinserttest.CheckCompiler(t, func(plan query.BulkInsertPlan) (string, []any, error) { return compileBulkInsert("app", plan) },
		`INSERT INTO "app"."bulk_items" ("name", "amount", "parent_id", "note") VALUES ($1, $2, $3, $4), ($5, $6, $7, $8)`,
		`INSERT INTO "app"."bulk_auto" ("id") VALUES (DEFAULT), (DEFAULT) RETURNING "id"`, postgresBulkParameters)
	plan := bulkinserttest.Plan(t, [][]query.Value{bulkinserttest.Row("literal", 1)}, query.BulkConflict{})
	if statement, args, err := compileBulkInsert(`wrong"schema`, plan); statement != "" || args != nil || !errors.Is(err, &query.Error{Code: query.CodeInvalidPlan}) {
		t.Fatal("invalid schema reached SQL", statement, args, err)
	}
}

func TestPostgresNativeBulkInsertAndScope(t *testing.T) {
	url := postgresIntegrationURL(t)
	namespace := postgresMigrationIntegrationSchema(t, t.Context(), url)
	backend := openPostgresMigrationIntegrationBackend(t, t.Context(), url, namespace)
	parent, err := quoteTable(namespace, "bulk_parent")
	if err != nil {
		t.Fatal(err)
	}
	table, err := quoteTable(namespace, "bulk_items")
	if err != nil {
		t.Fatal(err)
	}
	auto, err := quoteTable(namespace, "bulk_auto")
	if err != nil {
		t.Fatal(err)
	}
	function, err := quoteTable(namespace, "bulk_skip")
	if err != nil {
		t.Fatal(err)
	}
	for _, statement := range []string{
		"CREATE TABLE " + parent + " (id BIGINT PRIMARY KEY)",
		"INSERT INTO " + parent + " VALUES (1)",
		"CREATE TABLE " + table + " (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, amount BIGINT NOT NULL CHECK(amount >= 0), parent_id BIGINT REFERENCES " + parent + "(id) DEFERRABLE INITIALLY DEFERRED, note TEXT)",
		"CREATE TABLE " + auto + " (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
		"CREATE FUNCTION " + function + "() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN IF NEW.name=''skip-native'' THEN RETURN NULL; END IF; RETURN NEW; END'",
		"CREATE TRIGGER bulk_skip BEFORE INSERT ON " + table + " FOR EACH ROW EXECUTE FUNCTION " + function + "()",
	} {
		if _, err := backend.database.ExecContext(t.Context(), statement); err != nil {
			t.Fatal(err)
		}
	}
	bulkinserttest.Check(t, backend, backend.database, table, auto, true)
}
