package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/duration"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
	"math"
	"testing"
	"time"
)

func TestPostgresDurationArgumentsCatalogAndDriverBoundaries(t *testing.T) {
	for _, elapsed := range []duration.Duration{{}, duration.FromMicroseconds(math.MinInt64), {Days: duration.MaxDays, Microseconds: duration.MicrosecondsPerDay - 1}} {
		raw, err := postgresValue(query.Duration(elapsed))
		if err != nil {
			t.Fatal(err)
		}
		interval, ok := raw.(pgtype.Interval)
		if !ok || !interval.Valid || interval.Months != 0 || interval.Days != elapsed.Days || interval.Microseconds != elapsed.Microseconds {
			t.Fatal("duration lost native interval components")
		}
	}
	for _, test := range []struct {
		raw   string
		value duration.Duration
	}{
		{"00:00:00", duration.Duration{}}, {"-00:00:00.000001", duration.FromMicroseconds(-1)},
		{"-106751992 days +19:59:05.224192", duration.FromMicroseconds(math.MinInt64)},
		{"999999999 days 23:59:59.999999", duration.Duration{Days: duration.MaxDays, Microseconds: duration.MicrosecondsPerDay - 1}},
		{"-999999999 days", duration.Duration{Days: duration.MinDays}},
		{"-2562047788:00:54.775808", duration.FromMicroseconds(math.MinInt64)},
	} {
		got, err := decodePostgresDuration(test.raw)
		if err != nil || got != test.value {
			t.Fatalf("interval %q = %v %v", test.raw, got, err)
		}
	}
	for _, raw := range []string{"1 mon", "infinity", "-infinity", "1000000000 days", "2562047788:00:54.775808", "00:00:00.0000001", "P1D", "@ 1 day", "1 day 12:60:00"} {
		scanner := orm.NullableDurationScanner{Duration: duration.FromMicroseconds(1), Valid: true}
		if err := (durationDestination{destination: &scanner}).Scan(raw); err == nil || scanner.Valid {
			t.Fatalf("unsupported interval %q published duration", raw)
		}
	}
	field := ir.Field{Name: "elapsed", GoName: "Elapsed", Column: "elapsed", Kind: ir.FieldDuration, Nullable: true, Default: &ir.Scalar{Kind: ir.ScalarDuration, Duration: "00:00:00"}}
	ddl, err := compilePostgresMigrationColumn(field)
	if err != nil || ddl != `"elapsed" INTERVAL NULL` {
		t.Fatalf("interval DDL %q %v", ddl, err)
	}
	model := postgresMigrationTestAuthorModel()
	model.Fields = append(model.Fields, field)
	exact := postgresMigrationTestCatalog(t, "product_schema", model, nil)
	if err := assertPostgresMigrationModelCatalog(exact, "product_schema", model, nil); err != nil {
		t.Fatal(err)
	}
	for _, kind := range []string{"time", "int8", "text"} {
		bad := clonePostgresMigrationTestCatalog(exact)
		bad.columns[2].typeName = kind
		if err := assertPostgresMigrationModelCatalog(bad, "product_schema", model, nil); err == nil {
			t.Fatal("interval catalog drift accepted")
		}
	}
}

func TestPostgresDurationFullRangeAndForeignIntervalRejection(t *testing.T) {
	url := postgresIntegrationURL(t)
	ctx := t.Context()
	admin, err := pgx.Connect(ctx, url)
	if err != nil {
		t.Fatal("connect duration test database")
	}
	schema := fmt.Sprintf("godj_duration_%d", time.Now().UnixNano())
	quoted := pgx.Identifier{schema}.Sanitize()
	if _, err := admin.Exec(ctx, "CREATE SCHEMA "+quoted); err != nil {
		_ = admin.Close(ctx)
		t.Fatal(err)
	}
	t.Cleanup(func() {
		cleanup, cancel := context.WithTimeout(context.Background(), 20*time.Second)
		defer cancel()
		_, err := admin.Exec(cleanup, "DROP SCHEMA "+quoted+" CASCADE")
		if err != nil {
			t.Error(err)
		}
		if err := admin.Close(cleanup); err != nil {
			t.Error(err)
		}
	})
	if _, err := admin.Exec(ctx, "CREATE TABLE "+quoted+`.durations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, elapsed INTERVAL NULL)`); err != nil {
		t.Fatal(err)
	}
	backend, err := Open(ctx, Config{URL: postgresIntegrationURLWithParameter(t, url, "intervalstyle", "iso_8601"), Schema: schema})
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if backend != nil {
			if err := backend.Close(); err != nil {
				t.Error(err)
			}
		}
	}()
	if backend.profile.intervalStyle != "postgres" {
		t.Fatal("unowned interval output style")
	}
	id := query.NewFieldRef("id", "id", query.FieldInteger, false)
	field := query.NewFieldRef("elapsed", "elapsed", query.FieldDuration, true)
	expected := []duration.Duration{{Days: duration.MinDays}, {Days: duration.MaxDays, Microseconds: duration.MicrosecondsPerDay - 1}, duration.FromMicroseconds(math.MinInt64), duration.FromMicroseconds(math.MaxInt64), duration.FromMicroseconds(-1), {}}
	for _, elapsed := range expected {
		if _, err := backend.Insert(ctx, query.NewInsertPlanReturningKey("durations", []query.Assignment{query.NewAssignment(field, query.Duration(elapsed))}, id)); err != nil {
			t.Fatal(err)
		}
	}
	if err := backend.Close(); err != nil {
		t.Fatal(err)
	}
	backend, err = Open(ctx, Config{URL: url, Schema: schema})
	if err != nil {
		t.Fatal(err)
	}
	check := func(reader db.Queryer) {
		rows, err := reader.Query(ctx, query.NewPlan("durations", []query.FieldRef{id, field}).WithOrderings(query.NewOrdering(id, query.Ascending)))
		if err != nil {
			t.Fatal(err)
		}
		index := 0
		for rows.Next() {
			var key int64
			var elapsed orm.DurationScanner
			if err := rows.Scan(&key, &elapsed); err != nil {
				_ = rows.Close()
				t.Fatal(err)
			}
			if index >= len(expected) || elapsed.Duration != expected[index] {
				t.Fatal("PostgreSQL full duration range corrupted")
			}
			index++
		}
		if err := rows.Err(); err != nil {
			t.Fatal(err)
		}
		if err := rows.Close(); err != nil {
			t.Fatal(err)
		}
		if index != len(expected) {
			t.Fatal("wide duration rows missing")
		}
	}
	sorted, err := backend.Query(ctx, query.NewPlan("durations", []query.FieldRef{field}).WithOrderings(query.NewOrdering(field, query.Ascending)))
	if err != nil {
		t.Fatal(err)
	}
	ordered := []duration.Duration{expected[0], expected[2], expected[4], expected[5], expected[3], expected[1]}
	index := 0
	for sorted.Next() {
		var value orm.DurationScanner
		if err := sorted.Scan(&value); err != nil {
			t.Fatal(err)
		}
		if index >= len(ordered) || value.Duration != ordered[index] {
			t.Fatal("native interval ordering narrowed large durations")
		}
		index++
	}
	if err := sorted.Err(); err != nil {
		t.Fatal(err)
	}
	if err := sorted.Close(); err != nil {
		t.Fatal(err)
	}
	if index != len(ordered) {
		t.Fatal("native duration ordering lost rows")
	}
	check(backend)
	if err := backend.Atomic(ctx, func(session db.Session) error { check(session); return nil }); err != nil {
		t.Fatal(err)
	}
	// Any SQL-side month or interval outside the model domain must fail closed.
	for _, literal := range []string{"1 mon", "1000000000 days", "infinity"} {
		if _, err := admin.Exec(ctx, "UPDATE "+quoted+".durations SET elapsed=$1::interval WHERE id=1", literal); err != nil {
			t.Fatal(err)
		}
		plan, err := query.NewPlan("durations", []query.FieldRef{id, field}).WithConditions(query.NewCondition(id, query.LookupExact, query.Integer(1)))
		if err != nil {
			t.Fatal(err)
		}
		rows, err := backend.Query(ctx, plan)
		if err != nil {
			t.Fatal(err)
		}
		if !rows.Next() {
			t.Fatal("bad duration row missing")
		}
		var key int64
		value := orm.NullableDurationScanner{Valid: true, Duration: duration.FromMicroseconds(1)}
		if err := rows.Scan(&key, &value); err == nil || value.Valid {
			t.Fatal("unsupported native interval escaped backend")
		}
		if err := rows.Close(); err != nil {
			t.Fatal(err)
		}
	}
	// The physical-session validator replaces a contaminated pooled connection.
	connection, err := backend.database.Conn(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := connection.ExecContext(ctx, "SET intervalstyle='sql_standard'"); err != nil {
		t.Fatal(err)
	}
	if err := connection.Close(); err != nil {
		t.Fatal(err)
	}
	var style string
	if err := backend.database.QueryRowContext(ctx, "SELECT current_setting('IntervalStyle')").Scan(&style); err != nil || style != "postgres" {
		t.Fatalf("interval profile reset %s %v", style, err)
	}
	var _ sql.Scanner = durationDestination{}
}
