package postgres

import (
	"strings"
	"testing"

	migrationbackend "github.com/progresshans/godj/migrations/backend"
	"github.com/progresshans/godj/schema/ir"
)

func TestCompilePostgresMigrationSQLUsesExplicitSchemaAndConstraints(t *testing.T) {
	t.Parallel()

	author := postgresMigrationTestAuthorModel()
	post := postgresMigrationTestPostModel(true)
	target := postgresMigrationTestTarget(post.Fields[len(post.Fields)-1], author)
	foreignKeyName, err := postgresForeignKeyConstraintName(post.DBTable, "author_id")
	if err != nil {
		t.Fatal(err)
	}
	primaryKeyName, err := postgresPrimaryKeyConstraintName(post.DBTable)
	if err != nil {
		t.Fatal(err)
	}
	sequenceName, err := postgresIdentitySequenceName(post.DBTable, "id")
	if err != nil {
		t.Fatal(err)
	}

	create, err := compilePostgresMigrationCreateModel("product_schema", post, []migrationbackend.MigrationTarget{target})
	if err != nil {
		t.Fatalf("compile CreateModel: %v", err)
	}
	wantCreate := `CREATE TABLE "product_schema"."blog_post" (` +
		`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "product_schema"."` + sequenceName +
		`" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL, ` +
		`"title" VARCHAR(200) NOT NULL, ` +
		`"published" BOOLEAN NOT NULL, ` +
		`"author_id" BIGINT NOT NULL, ` +
		`CONSTRAINT "` + foreignKeyName + `" FOREIGN KEY ("author_id") REFERENCES ` +
		`"product_schema"."authors_author" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE, ` +
		`CONSTRAINT "` + primaryKeyName + `" PRIMARY KEY ("id"))`
	if create != wantCreate {
		t.Fatalf("CreateModel SQL = %q, want %q", create, wantCreate)
	}
	if strings.Contains(create, "search_path") || strings.Contains(create, "IF ") || strings.Contains(create, "CASCADE") {
		t.Fatalf("CreateModel SQL contains an implicit or permissive clause: %q", create)
	}

	add, err := compilePostgresMigrationAddField("product_schema", postgresMigrationTestPostModel(false), target.SourceField, &target)
	if err != nil {
		t.Fatalf("compile ForeignKey AddField: %v", err)
	}
	wantAdd := `ALTER TABLE "product_schema"."blog_post" ADD COLUMN "author_id" BIGINT NOT NULL, ` +
		`ADD CONSTRAINT "` + foreignKeyName + `" FOREIGN KEY ("author_id") REFERENCES ` +
		`"product_schema"."authors_author" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE`
	if add != wantAdd {
		t.Fatalf("AddField SQL = %q, want %q", add, wantAdd)
	}

	remove, err := compilePostgresMigrationRemoveField("product_schema", post, target.SourceField)
	if err != nil {
		t.Fatalf("compile ForeignKey RemoveField: %v", err)
	}
	wantRemove := `ALTER TABLE "product_schema"."blog_post" DROP CONSTRAINT "` + foreignKeyName +
		`", DROP COLUMN "author_id" RESTRICT`
	if remove != wantRemove {
		t.Fatalf("RemoveField SQL = %q, want %q", remove, wantRemove)
	}

	deleted, err := compilePostgresMigrationDeleteModel("product_schema", post)
	if err != nil {
		t.Fatalf("compile DeleteModel: %v", err)
	}
	if want := `DROP TABLE "product_schema"."blog_post" RESTRICT`; deleted != want {
		t.Fatalf("DeleteModel SQL = %q, want %q", deleted, want)
	}
}

func TestCompilePostgresMigrationDefaultIsLogicalOnly(t *testing.T) {
	t.Parallel()

	logicalDefault := &ir.ScalarDefault{Kind: ir.ScalarBoolean}
	field := ir.Field{
		Name: "featured", GoName: "Featured", Column: "featured",
		Kind: ir.FieldBoolean, Default: logicalDefault,
	}
	statement, err := compilePostgresMigrationAddField(
		"product_schema",
		postgresMigrationTestPostModel(false),
		field,
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(strings.ToUpper(statement), "DEFAULT") {
		t.Fatalf("logical migration default leaked into persistent PostgreSQL DDL: %q", statement)
	}
	if want := `ALTER TABLE "product_schema"."blog_post" ADD COLUMN "featured" BOOLEAN NOT NULL`; statement != want {
		t.Fatalf("AddField SQL = %q, want %q", statement, want)
	}
}

func TestPostgresMigrationConstraintNamesAreFixedAndDomainSeparated(t *testing.T) {
	t.Parallel()

	longTable := "t" + strings.Repeat("a", postgresIdentifierMaxBytes-1)
	longColumn := "c" + strings.Repeat("b", postgresIdentifierMaxBytes-1)
	foreignKey, err := postgresForeignKeyConstraintName(longTable, longColumn)
	if err != nil {
		t.Fatal(err)
	}
	primaryKey, err := postgresPrimaryKeyConstraintName(longTable)
	if err != nil {
		t.Fatal(err)
	}
	sequence, err := postgresIdentitySequenceName(longTable, longColumn)
	if err != nil {
		t.Fatal(err)
	}
	if len(foreignKey) != len("godj_fk_")+postgresConstraintDigestBytes*2 || len(foreignKey) > postgresIdentifierMaxBytes {
		t.Fatalf("foreign key name length = %d, name=%q", len(foreignKey), foreignKey)
	}
	if len(primaryKey) != len("godj_pk_")+postgresConstraintDigestBytes*2 || len(primaryKey) > postgresIdentifierMaxBytes {
		t.Fatalf("primary key name length = %d, name=%q", len(primaryKey), primaryKey)
	}
	if len(sequence) != len("godj_seq_")+postgresConstraintDigestBytes*2 || len(sequence) > postgresIdentifierMaxBytes {
		t.Fatalf("identity sequence name length = %d, name=%q", len(sequence), sequence)
	}
	if foreignKey == primaryKey || foreignKey == sequence || primaryKey == sequence ||
		!strings.HasPrefix(foreignKey, "godj_fk_") || !strings.HasPrefix(primaryKey, "godj_pk_") ||
		!strings.HasPrefix(sequence, "godj_seq_") {
		t.Fatalf("derived name domains are not separated: fk=%q pk=%q sequence=%q", foreignKey, primaryKey, sequence)
	}
	again, err := postgresForeignKeyConstraintName(longTable, longColumn)
	if err != nil || again != foreignKey {
		t.Fatalf("foreign key name is not deterministic: again=%q err=%v", again, err)
	}
	other, err := postgresForeignKeyConstraintName(longTable, "other_column")
	if err != nil {
		t.Fatal(err)
	}
	if other == foreignKey {
		t.Fatalf("different source columns collided: %q", foreignKey)
	}
}

func TestCompilePostgresMigrationColumnRejectsUnsupportedShape(t *testing.T) {
	t.Parallel()

	tests := []ir.Field{
		{Kind: ir.FieldChar, MaxLength: 1},
		{Column: "value", Kind: ir.FieldChar},
		{Column: "value", Kind: ir.FieldBoolean, Nullable: true},
		{Column: "id", Kind: ir.FieldAuto},
		{Column: "value", Kind: ir.FieldKind("unknown")},
	}
	for index := range tests {
		if _, err := compilePostgresMigrationColumn(tests[index]); err == nil {
			t.Fatalf("case %d: compilePostgresMigrationColumn() error = nil", index)
		}
	}
}

func postgresMigrationTestAuthorModel() ir.Model {
	return ir.Model{
		Name: "author", GoName: "Author", DBTable: "authors_author",
		Fields: []ir.Field{
			{Name: "id", GoName: "ID", Column: "id", Kind: ir.FieldAuto, PrimaryKey: true},
			{Name: "name", GoName: "Name", Column: "name", Kind: ir.FieldChar, MaxLength: 100},
		},
	}
}

func postgresMigrationTestPostModel(withAuthor bool) ir.Model {
	model := ir.Model{
		Name: "post", GoName: "Post", DBTable: "blog_post",
		Fields: []ir.Field{
			{Name: "id", GoName: "ID", Column: "id", Kind: ir.FieldAuto, PrimaryKey: true},
			{Name: "title", GoName: "Title", Column: "title", Kind: ir.FieldChar, MaxLength: 200},
			{Name: "published", GoName: "Published", Column: "published", Kind: ir.FieldBoolean},
		},
	}
	if withAuthor {
		model.Fields = append(model.Fields, ir.Field{
			Name: "author", GoName: "Author", Column: "author_id", Kind: ir.FieldForeignKey,
			Relation: &ir.ForeignKeyRelation{
				Target:      ir.ModelIdentity{AppLabel: "authors", ModelName: "author"},
				Cardinality: ir.RelationManyToOne,
				Reverse:     ir.ReverseRelation{Name: "posts"},
				OnDelete:    ir.DeleteProtect,
			},
		})
	}
	return model
}

func postgresMigrationTestTarget(field ir.Field, model ir.Model) migrationbackend.MigrationTarget {
	return migrationbackend.MigrationTarget{
		SourceField: field.Clone(),
		TargetModel: model.Clone(),
		TargetKey:   model.Fields[0].Clone(),
	}
}
