package postgres

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/internal/savepointtest"
	"github.com/progresshans/godj/query"
)

func TestPostgresNativeSavepoints(t *testing.T) {
	url := postgresIntegrationURL(t)
	ctx := t.Context()
	namespace := postgresMigrationIntegrationSchema(t, ctx, url)
	backend := openPostgresMigrationIntegrationBackend(t, ctx, url, namespace)
	table, _ := quoteTable(namespace, "savepoint_items")
	if _, err := backend.database.ExecContext(ctx, "CREATE TABLE "+table+"(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, parent_id BIGINT REFERENCES "+table+"(id))"); err != nil {
		t.Fatal(err)
	}
	for _, variant := range []struct {
		name  string
		owner savepointtest.Owner
	}{
		{"ordinary", backend.Atomic}, {"coordinated", backend.CoordinatedAtomic},
		{"relation", func(ctx context.Context, callback func(db.Session) error) error {
			return backend.AtomicRelation(ctx, func(session db.RelationSession) error { return callback(session) })
		}},
		{"coordinated_relation", func(ctx context.Context, callback func(db.Session) error) error {
			return backend.CoordinatedAtomicRelation(ctx, func(session db.RelationSession) error { return callback(session) })
		}},
	} {
		t.Run(variant.name, func(t *testing.T) { savepointtest.Check(t, backend, variant.owner) })
	}
	streamTable, _ := quoteTable(namespace, "savepoint_stream")
	if _, err := backend.database.ExecContext(ctx, "CREATE TABLE "+streamTable+"(value BIGINT); INSERT INTO "+streamTable+" VALUES(1),(2)"); err != nil {
		t.Fatal(err)
	}
	value := query.NewFieldRef("value", "value", query.FieldInteger, false)
	plan := query.NewPlan("savepoint_stream", []query.FieldRef{value}).WithOrderings(query.NewOrdering(value, query.Ascending))
	scans, yields := 0, 0
	err := backend.QueryBatches(ctx, plan, 1, func(row db.Row) error { var value int64; scans++; return row.Scan(&value) }, func(affinity db.Queryer) (bool, error) {
		yields++
		if yields == 1 {
			t.Run("pinned_ordinary", func(t *testing.T) { savepointtest.CheckPinned(t, affinity, affinity.(db.Atomic).Atomic) })
			t.Run("pinned_coordinated_relation", func(t *testing.T) {
				savepointtest.CheckPinned(t, affinity, func(ctx context.Context, callback func(db.Session) error) error {
					return affinity.(db.CoordinatedRelationAtomic).CoordinatedAtomicRelation(ctx, func(session db.RelationSession) error { return callback(session) })
				})
			})
		}
		return true, nil
	})
	if err != nil || scans != 2 || yields != 2 {
		t.Fatalf("root stream after savepoints = %d/%d/%v", scans, yields, err)
	}
}

func TestPostgresSavepointFailurePreventsCommitAndPreservesUnknownRollback(t *testing.T) {
	t.Parallel()
	for _, failRollback := range []bool{false, true} {
		for _, stage := range []string{"SAVEPOINT ", "ROLLBACK TO ", "RELEASE "} {
			t.Run(strings.TrimSpace(stage)+map[bool]string{false: "/confirmed", true: "/unknown"}[failRollback], func(t *testing.T) {
				t.Parallel()
				controlFailure := errors.New("savepoint transport failure")
				rollbackFailure := errors.New("root rollback failure")
				var controlCalls int
				state := &transactionTestState{execHook: func(_ context.Context, statement string) error {
					if strings.HasPrefix(statement, stage) {
						controlCalls++
						return controlFailure
					}
					return nil
				}}
				if failRollback {
					state.rollbackErr = rollbackFailure
				}
				backend := newTransactionTestBackend(state)
				t.Cleanup(func() { _ = backend.Close() })
				calls := 0
				err := backend.Atomic(context.Background(), func(outer db.Session) error {
					err := db.WithSavepoint(context.Background(), outer, func(db.Session) error {
						calls++
						if stage == "ROLLBACK TO " {
							return errors.New("child error")
						}
						return nil
					})
					if !errors.Is(err, controlFailure) || !errors.Is(err, &query.Error{Code: query.CodeTransactionRollbackRequired}) {
						t.Errorf("savepoint failure = %v", err)
					}
					return nil
				})
				if !errors.Is(err, controlFailure) || !errors.Is(err, &query.Error{Code: query.CodeTransactionRollbackRequired}) {
					t.Fatalf("suppressed control failure = %v", err)
				}
				wantCalls := 1
				if stage == "SAVEPOINT " {
					wantCalls = 0
				}
				result := state.snapshot()
				if calls != wantCalls || controlCalls != 1 || result.commits != 0 || result.rollbacks != 1 {
					t.Fatalf("callback/control/commit/rollback = %d/%d/%d/%d", calls, controlCalls, result.commits, result.rollbacks)
				}
				if errors.Is(err, &query.Error{Code: query.CodeTransactionOutcomeUnknown}) != failRollback || failRollback && !errors.Is(err, rollbackFailure) {
					t.Fatalf("rollback classification = %v", err)
				}
			})
		}
	}
}
