// Code generated by GoDj. DO NOT EDIT.

package project

import (
	reports "github.com/progresshans/godj/conformance/onetoonefixture/reports"
	tickets "github.com/progresshans/godj/conformance/onetoonefixture/tickets"
	db "github.com/progresshans/godj/db"
	orm "github.com/progresshans/godj/orm"
	query "github.com/progresshans/godj/query"
	ir "github.com/progresshans/godj/schema/ir"
)

const GoDjProjectRelationReverseGeneratorVersion = "godj-codegen-rel-reverse-project-v1"

var _ orm.RelationObjectDescriptor[reports.Link] = reports.LinkDescriptor{}
var _ orm.RelationObjectDescriptor[reports.OptionalReport] = reports.OptionalReportDescriptor{}
var _ orm.RelationObjectDescriptor[reports.Report] = reports.ReportDescriptor{}
var _ orm.RelationObjectDescriptor[tickets.Ticket] = tickets.TicketDescriptor{}
var _ orm.PrimaryKeyObjectDescriptor[tickets.Ticket] = tickets.TicketDescriptor{}

type TicketsTicketLinksReverseRelation struct {
	ID    orm.RelatedIntegerField[tickets.Ticket]
	Label orm.RelatedStringField[tickets.Ticket]
}

type TicketsTicketOptionalReportReverseRelation struct {
	ID   orm.RelatedIntegerField[tickets.Ticket]
	Note orm.RelatedStringField[tickets.Ticket]
}

type TicketsTicketReportReverseRelation struct {
	ID   orm.RelatedIntegerField[tickets.Ticket]
	Note orm.RelatedStringField[tickets.Ticket]
}

type TicketsTicketReverseRelations struct {
	Links          TicketsTicketLinksReverseRelation
	OptionalReport TicketsTicketOptionalReportReverseRelation
	Report         TicketsTicketReportReverseRelation
	model          orm.BoundModel[tickets.Ticket]
}

func (_relations TicketsTicketReverseRelations) ParseDynamic(
	_policy orm.LookupPolicy,
	_inputs []orm.LookupInput,
) ([]orm.Predicate[tickets.Ticket], error) {
	return orm.ParseDynamicReverseRelations(_relations.model, _policy, _inputs)
}

type ReverseRelations struct {
	TicketsTicket TicketsTicketReverseRelations
}

func BindReverseRelations() (ReverseRelations, error) {
	_binding, _err := Bind()
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model0, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "otoreports", ModelName: "link"},
		reports.LinkDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model1, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "otoreports", ModelName: "optional_report"},
		reports.OptionalReportDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model2, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "otoreports", ModelName: "report"},
		reports.ReportDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model3, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "ototickets", ModelName: "ticket"},
		tickets.TicketDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_relation0, _err := orm.BindReverse(_model3, "links", _model0)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal0, _err := _relation0.Integer(reports.LinkFields.ID)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal1, _err := _relation0.String(reports.LinkFields.Label)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_relation1, _err := orm.BindReverse(_model3, "optional_report", _model1)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal2, _err := _relation1.Integer(reports.OptionalReportFields.ID)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal3, _err := _relation1.String(reports.OptionalReportFields.Note)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_relation2, _err := orm.BindReverse(_model3, "report", _model2)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal4, _err := _relation2.Integer(reports.ReportFields.ID)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal5, _err := _relation2.String(reports.ReportFields.Note)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	return ReverseRelations{
		TicketsTicket: TicketsTicketReverseRelations{
			Links: TicketsTicketLinksReverseRelation{
				ID:    _terminal0,
				Label: _terminal1,
			},
			OptionalReport: TicketsTicketOptionalReportReverseRelation{
				ID:   _terminal2,
				Note: _terminal3,
			},
			Report: TicketsTicketReportReverseRelation{
				ID:   _terminal4,
				Note: _terminal5,
			},
			model: _model3,
		},
	}, nil
}

type TicketsTicketReverseObjectFactory struct {
	links          orm.ReverseObject[tickets.Ticket, reports.Link]
	optionalReport orm.ReverseOneToOneObject[tickets.Ticket, reports.OptionalReport]
	report         orm.ReverseOneToOneObject[tickets.Ticket, reports.Report]
}

func (_factory TicketsTicketReverseObjectFactory) From(_backend db.Queryer, _value tickets.Ticket) (*TicketsTicketReverseObject, error) {
	_snapshot := (tickets.TicketDescriptor{}).CloneModel(_value)
	_related0, _err := _factory.links.From(_backend, _snapshot)
	if _err != nil {
		return nil, _err
	}
	_related1, _err := _factory.optionalReport.From(_backend, _snapshot)
	if _err != nil {
		return nil, _err
	}
	_related2, _err := _factory.report.From(_backend, _snapshot)
	if _err != nil {
		return nil, _err
	}
	_result := &TicketsTicketReverseObject{
		model:          _snapshot,
		factory:        _factory,
		backend:        _backend,
		links:          _related0,
		optionalReport: _related1,
		report:         _related2,
	}
	_result._self = _result
	return _result, nil
}

type TicketsTicketReverseObject struct {
	model          tickets.Ticket
	factory        TicketsTicketReverseObjectFactory
	backend        db.Queryer
	links          *orm.RelatedSet[reports.Link]
	optionalReport *orm.RelatedObject[reports.OptionalReport]
	report         *orm.RelatedObject[reports.Report]
	_self          *TicketsTicketReverseObject
}

func (_object *TicketsTicketReverseObject) _validate() error {
	if _object == nil || _object._self != _object {
		return &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated reverse relation object is nil, zero, or copied",
		}
	}
	return nil
}

func (_object *TicketsTicketReverseObject) Model() (tickets.Ticket, error) {
	if _err := _object._validate(); _err != nil {
		return tickets.Ticket{}, _err
	}
	return (tickets.TicketDescriptor{}).CloneModel(_object.model), nil
}

func (_object *TicketsTicketReverseObject) Links() (*orm.RelatedSet[reports.Link], error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.links, nil
}

func (_object *TicketsTicketReverseObject) OptionalReport() (*orm.RelatedObject[reports.OptionalReport], error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.optionalReport, nil
}

func (_object *TicketsTicketReverseObject) Report() (*orm.RelatedObject[reports.Report], error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.report, nil
}

func (_object *TicketsTicketReverseObject) Fresh() (*TicketsTicketReverseObject, error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.factory.From(_object.backend, _object.model)
}

type ReverseObjects struct {
	TicketsTicket TicketsTicketReverseObjectFactory
}

func BindReverseObjects() (ReverseObjects, error) {
	_binding, _err := Bind()
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model0, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "otoreports", ModelName: "link"},
		reports.LinkDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model1, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "otoreports", ModelName: "optional_report"},
		reports.OptionalReportDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model2, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "otoreports", ModelName: "report"},
		reports.ReportDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model3, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "ototickets", ModelName: "ticket"},
		tickets.TicketDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_relation0, _err := orm.BindReverseObject(_model3, "links", _model0)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_relation1, _err := orm.BindReverseOneToOneObject(_model3, "optional_report", _model1)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_relation2, _err := orm.BindReverseOneToOneObject(_model3, "report", _model2)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	return ReverseObjects{
		TicketsTicket: TicketsTicketReverseObjectFactory{
			links:          _relation0,
			optionalReport: _relation1,
			report:         _relation2,
		},
	}, nil
}

var _ goDjProjectSnapshot_b47a9399b87c8c316792141e4066fd45b59e7e9a76cc7d1aa2c75d96d30c2b0c
