// Code generated by GoDj. DO NOT EDIT.

package project

import (
	tickets "github.com/progresshans/godj/conformance/onetoonefixture/tickets"
	orm "github.com/progresshans/godj/orm"
	query "github.com/progresshans/godj/query"
	ir "github.com/progresshans/godj/schema/ir"
)

const GoDjProjectRelationDeleteGeneratorVersion = "godj-codegen-rel-delete-project-v1"

var _ orm.WriteDescriptor[tickets.Ticket] = tickets.TicketDescriptor{}

type RelationDeleters struct {
	TicketsTicket orm.RelationDeleter[tickets.Ticket]
}

func BindRelationDeleters() (RelationDeleters, error) {
	_binding, _err := Bind()
	if _err != nil {
		return RelationDeleters{}, _err
	}
	_targets := make(map[ir.ModelIdentity]struct{})
	for _, _relation := range _binding.ForwardRelations() {
		_targets[_relation.Target] = struct{}{}
	}
	if len(_targets) != 1 {
		return RelationDeleters{}, &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated relation deleter target set does not match project binding",
		}
	}
	if _, _ok := _targets[ir.ModelIdentity{AppLabel: "ototickets", ModelName: "ticket"}]; !_ok {
		return RelationDeleters{}, &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated relation deleter target set does not match project binding",
		}
	}
	_deleter0, _err := orm.BindRelationDeleter(
		_binding,
		ir.ModelIdentity{AppLabel: "ototickets", ModelName: "ticket"},
		tickets.TicketDescriptor{},
		"871f8d224ecbcaaeebe61b83be716b42e58dc567040cc88579c004389b429ad1",
	)
	if _err != nil {
		return RelationDeleters{}, _err
	}
	return RelationDeleters{
		TicketsTicket: _deleter0,
	}, nil
}

var _ goDjProjectSnapshot_1e0adcfbb25788b5dc7b0d36e3cf9825b62db75777d2bc04a18f6e72febd2ae0
