// Code generated by GoDj. DO NOT EDIT.

package project

import (
	context "context"
	reports "github.com/progresshans/godj/conformance/onetoonefixture/reports"
	tickets "github.com/progresshans/godj/conformance/onetoonefixture/tickets"
	orm "github.com/progresshans/godj/orm"
	query "github.com/progresshans/godj/query"
	strings "strings"
)

const GoDjProjectRelationSelectRelatedGeneratorVersion = "godj-codegen-rel-select-related-project-current-v4"

var _ orm.ProjectionDescriptor[reports.Link] = reports.LinkDescriptor{}
var _ orm.ProjectionDescriptor[reports.OptionalReport] = reports.OptionalReportDescriptor{}
var _ orm.ProjectionDescriptor[reports.Report] = reports.ReportDescriptor{}
var _ orm.ProjectionDescriptor[tickets.Ticket] = tickets.TicketDescriptor{}

type relationSelectQuery[O any] interface {
	All(context.Context) ([]*O, error)
	Count(context.Context) (int64, error)
	First(context.Context) (*O, bool, error)
}

type ReportsLinkSelectRelatedQuery struct {
	factory          ReportsLinkObjectFactory
	source           orm.QuerySet[reports.Link]
	query            orm.ForwardSelectQuery[reports.Link]
	selections       []orm.ForwardSelection[reports.Link]
	configurationErr error
}

func (_factory ReportsLinkObjectFactory) SelectRelated(_source orm.QuerySet[reports.Link]) ReportsLinkSelectRelatedQuery {
	return ReportsLinkSelectRelatedQuery{factory: _factory, source: _source, query: orm.SelectForward(_source)}
}
func (_query ReportsLinkSelectRelatedQuery) WithSelections(_selections ...orm.ForwardSelection[reports.Link]) ReportsLinkSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_owned := append([]orm.ForwardSelection[reports.Link](nil), _query.selections...)
	_query.selections = append(_owned, _selections...)
	return _query.rebuild()
}
func (_factory ReportsLinkObjectFactory) SelectTicket(_children ...orm.ForwardSelection[tickets.Ticket]) orm.ForwardSelect[reports.Link, tickets.Ticket] {
	return orm.SelectRequiredForward(_factory.ticket).WithChildren(_children...)
}
func (_query ReportsLinkSelectRelatedQuery) WithTicket(_children ...orm.ForwardSelection[tickets.Ticket]) ReportsLinkSelectRelatedQuery {
	return _query.WithSelections(_query.factory.SelectTicket(_children...))
}
func (_factory ReportsLinkObjectFactory) selectionInputs(_paths []string) ([]orm.ForwardSelection[reports.Link], error) {
	if len(_paths) == 0 || len(_paths) > orm.MaximumForwardSelectionNodes {
		return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Detail: "forward selection requires a bounded nonempty path list"}
	}
	_result := make([]orm.ForwardSelection[reports.Link], 0, len(_paths))
	for _, _path := range _paths {
		_parts := strings.Split(_path, "__")
		if len(_parts) > query.MaximumRelationHops {
			return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "forward selection exceeds its path bound"}
		}
		for _, _part := range _parts {
			if _part == "" {
				return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "forward selection contains an empty path segment"}
			}
		}
		switch _parts[0] {
		case "ticket":
			_selection := _factory.SelectTicket()
			if len(_parts) > 1 {
				return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "selected target has no further forward relation"}
			}
			_result = append(_result, _selection)
		default:
			return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "unknown forward selection path"}
		}
	}
	return _result, nil
}
func (_query ReportsLinkSelectRelatedQuery) ParseDynamic(_paths ...string) (ReportsLinkSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsLinkSelectRelatedQuery{}, _query.configurationErr
	}
	_selections, _err := _query.factory.selectionInputs(_paths)
	if _err != nil {
		return ReportsLinkSelectRelatedQuery{}, _err
	}
	_result := _query.WithSelections(_selections...)
	if _result.configurationErr != nil {
		return ReportsLinkSelectRelatedQuery{}, _result.configurationErr
	}
	return _result, nil
}
func (_query ReportsLinkSelectRelatedQuery) rebuild() ReportsLinkSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_query.query = orm.SelectForward(_query.source, _query.selections...).WithSourceBinding(_query.factory.model)
	if len(_query.selections) > 0 {
		_query.configurationErr = _query.query.ConfigurationError()
	}
	return _query
}
func (_query ReportsLinkSelectRelatedQuery) Filter(_values ...orm.Predicate[reports.Link]) ReportsLinkSelectRelatedQuery {
	_query.source = _query.source.Filter(_values...)
	return _query.rebuild()
}
func (_query ReportsLinkSelectRelatedQuery) OrderBy(_values ...orm.Ordering[reports.Link]) ReportsLinkSelectRelatedQuery {
	_query.source = _query.source.OrderBy(_values...)
	return _query.rebuild()
}
func (_query ReportsLinkSelectRelatedQuery) Distinct() ReportsLinkSelectRelatedQuery {
	_query.source = _query.source.Distinct()
	return _query.rebuild()
}
func (_query ReportsLinkSelectRelatedQuery) Fresh() ReportsLinkSelectRelatedQuery {
	_query.source = _query.source.Fresh()
	return _query.rebuild()
}
func (_query ReportsLinkSelectRelatedQuery) Limit(_value int) (ReportsLinkSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsLinkSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Limit(_value)
	if _err != nil {
		return ReportsLinkSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ReportsLinkSelectRelatedQuery) Offset(_value int) (ReportsLinkSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsLinkSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Offset(_value)
	if _err != nil {
		return ReportsLinkSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ReportsLinkSelectRelatedQuery) All(_ctx context.Context) ([]*ReportsLinkObject, error) {
	_selected, _err := _query.query.WithConfigurationError(_query.configurationErr).All(_ctx)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*ReportsLinkObject, len(_selected))
	for _index := range _selected {
		_results[_index], _err = _query.wrap(_selected[_index])
		if _err != nil {
			return nil, _err
		}
	}
	return _results, nil
}
func (_query ReportsLinkSelectRelatedQuery) First(_ctx context.Context) (*ReportsLinkObject, bool, error) {
	_selected, _found, _err := _query.query.WithConfigurationError(_query.configurationErr).First(_ctx)
	if _err != nil || !_found {
		return nil, false, _err
	}
	_object, _err := _query.wrap(_selected)
	return _object, _err == nil, _err
}
func (_query ReportsLinkSelectRelatedQuery) Count(_ctx context.Context) (int64, error) {
	return _query.query.WithConfigurationError(_query.configurationErr).Count(_ctx)
}
func (_query ReportsLinkSelectRelatedQuery) wrap(_selected *orm.ForwardSelected[reports.Link]) (*ReportsLinkObject, error) {
	return _query.factory.FromSelected(_selected)
}
func (_factory ReportsLinkObjectFactory) FromSelected(_selected *orm.ForwardSelected[reports.Link]) (*ReportsLinkObject, error) {
	if _err := _selected.ValidateSourceBinding(_factory.model); _err != nil {
		return nil, _err
	}
	_source, _err := _selected.Source()
	if _err != nil {
		return nil, _err
	}
	_backend, _err := _selected.Backend()
	if _err != nil {
		return nil, _err
	}
	_object, _err := _factory.From(_backend, _source)
	if _err != nil {
		return nil, _err
	}
	if _has, _err := _selected.HasSelection("ticket"); _err != nil {
		return nil, _err
	} else if _has {
		_related, _err := _factory.SelectTicket().Related(_selected)
		if _err != nil {
			return nil, _err
		}
		_object.ticket = _related
	}
	_object._selectedGraph = _selected
	return _object, nil
}

type ReportsOptionalReportSelectRelatedQuery struct {
	factory          ReportsOptionalReportObjectFactory
	source           orm.QuerySet[reports.OptionalReport]
	query            orm.ForwardSelectQuery[reports.OptionalReport]
	selections       []orm.ForwardSelection[reports.OptionalReport]
	configurationErr error
}

func (_factory ReportsOptionalReportObjectFactory) SelectRelated(_source orm.QuerySet[reports.OptionalReport]) ReportsOptionalReportSelectRelatedQuery {
	return ReportsOptionalReportSelectRelatedQuery{factory: _factory, source: _source, query: orm.SelectForward(_source)}
}
func (_query ReportsOptionalReportSelectRelatedQuery) WithSelections(_selections ...orm.ForwardSelection[reports.OptionalReport]) ReportsOptionalReportSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_owned := append([]orm.ForwardSelection[reports.OptionalReport](nil), _query.selections...)
	_query.selections = append(_owned, _selections...)
	return _query.rebuild()
}
func (_factory ReportsOptionalReportObjectFactory) SelectTicket(_children ...orm.ForwardSelection[tickets.Ticket]) orm.ForwardSelect[reports.OptionalReport, tickets.Ticket] {
	return orm.SelectNullableForward(_factory.ticket).WithChildren(_children...)
}
func (_query ReportsOptionalReportSelectRelatedQuery) WithTicket(_children ...orm.ForwardSelection[tickets.Ticket]) ReportsOptionalReportSelectRelatedQuery {
	return _query.WithSelections(_query.factory.SelectTicket(_children...))
}
func (_factory ReportsOptionalReportObjectFactory) selectionInputs(_paths []string) ([]orm.ForwardSelection[reports.OptionalReport], error) {
	if len(_paths) == 0 || len(_paths) > orm.MaximumForwardSelectionNodes {
		return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Detail: "forward selection requires a bounded nonempty path list"}
	}
	_result := make([]orm.ForwardSelection[reports.OptionalReport], 0, len(_paths))
	for _, _path := range _paths {
		_parts := strings.Split(_path, "__")
		if len(_parts) > query.MaximumRelationHops {
			return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "forward selection exceeds its path bound"}
		}
		for _, _part := range _parts {
			if _part == "" {
				return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "forward selection contains an empty path segment"}
			}
		}
		switch _parts[0] {
		case "ticket":
			_selection := _factory.SelectTicket()
			if len(_parts) > 1 {
				return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "selected target has no further forward relation"}
			}
			_result = append(_result, _selection)
		default:
			return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "unknown forward selection path"}
		}
	}
	return _result, nil
}
func (_query ReportsOptionalReportSelectRelatedQuery) ParseDynamic(_paths ...string) (ReportsOptionalReportSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _query.configurationErr
	}
	_selections, _err := _query.factory.selectionInputs(_paths)
	if _err != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _err
	}
	_result := _query.WithSelections(_selections...)
	if _result.configurationErr != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _result.configurationErr
	}
	return _result, nil
}
func (_query ReportsOptionalReportSelectRelatedQuery) rebuild() ReportsOptionalReportSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_query.query = orm.SelectForward(_query.source, _query.selections...).WithSourceBinding(_query.factory.model)
	if len(_query.selections) > 0 {
		_query.configurationErr = _query.query.ConfigurationError()
	}
	return _query
}
func (_query ReportsOptionalReportSelectRelatedQuery) Filter(_values ...orm.Predicate[reports.OptionalReport]) ReportsOptionalReportSelectRelatedQuery {
	_query.source = _query.source.Filter(_values...)
	return _query.rebuild()
}
func (_query ReportsOptionalReportSelectRelatedQuery) OrderBy(_values ...orm.Ordering[reports.OptionalReport]) ReportsOptionalReportSelectRelatedQuery {
	_query.source = _query.source.OrderBy(_values...)
	return _query.rebuild()
}
func (_query ReportsOptionalReportSelectRelatedQuery) Distinct() ReportsOptionalReportSelectRelatedQuery {
	_query.source = _query.source.Distinct()
	return _query.rebuild()
}
func (_query ReportsOptionalReportSelectRelatedQuery) Fresh() ReportsOptionalReportSelectRelatedQuery {
	_query.source = _query.source.Fresh()
	return _query.rebuild()
}
func (_query ReportsOptionalReportSelectRelatedQuery) Limit(_value int) (ReportsOptionalReportSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Limit(_value)
	if _err != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ReportsOptionalReportSelectRelatedQuery) Offset(_value int) (ReportsOptionalReportSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Offset(_value)
	if _err != nil {
		return ReportsOptionalReportSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ReportsOptionalReportSelectRelatedQuery) All(_ctx context.Context) ([]*ReportsOptionalReportObject, error) {
	_selected, _err := _query.query.WithConfigurationError(_query.configurationErr).All(_ctx)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*ReportsOptionalReportObject, len(_selected))
	for _index := range _selected {
		_results[_index], _err = _query.wrap(_selected[_index])
		if _err != nil {
			return nil, _err
		}
	}
	return _results, nil
}
func (_query ReportsOptionalReportSelectRelatedQuery) First(_ctx context.Context) (*ReportsOptionalReportObject, bool, error) {
	_selected, _found, _err := _query.query.WithConfigurationError(_query.configurationErr).First(_ctx)
	if _err != nil || !_found {
		return nil, false, _err
	}
	_object, _err := _query.wrap(_selected)
	return _object, _err == nil, _err
}
func (_query ReportsOptionalReportSelectRelatedQuery) Count(_ctx context.Context) (int64, error) {
	return _query.query.WithConfigurationError(_query.configurationErr).Count(_ctx)
}
func (_query ReportsOptionalReportSelectRelatedQuery) wrap(_selected *orm.ForwardSelected[reports.OptionalReport]) (*ReportsOptionalReportObject, error) {
	return _query.factory.FromSelected(_selected)
}
func (_factory ReportsOptionalReportObjectFactory) FromSelected(_selected *orm.ForwardSelected[reports.OptionalReport]) (*ReportsOptionalReportObject, error) {
	if _err := _selected.ValidateSourceBinding(_factory.model); _err != nil {
		return nil, _err
	}
	_source, _err := _selected.Source()
	if _err != nil {
		return nil, _err
	}
	_backend, _err := _selected.Backend()
	if _err != nil {
		return nil, _err
	}
	_object, _err := _factory.From(_backend, _source)
	if _err != nil {
		return nil, _err
	}
	if _has, _err := _selected.HasSelection("ticket"); _err != nil {
		return nil, _err
	} else if _has {
		_related, _err := _factory.SelectTicket().Related(_selected)
		if _err != nil {
			return nil, _err
		}
		_object.ticket = _related
	}
	_object._selectedGraph = _selected
	return _object, nil
}

type ReportsReportSelectRelatedQuery struct {
	factory          ReportsReportObjectFactory
	source           orm.QuerySet[reports.Report]
	query            orm.ForwardSelectQuery[reports.Report]
	selections       []orm.ForwardSelection[reports.Report]
	configurationErr error
}

func (_factory ReportsReportObjectFactory) SelectRelated(_source orm.QuerySet[reports.Report]) ReportsReportSelectRelatedQuery {
	return ReportsReportSelectRelatedQuery{factory: _factory, source: _source, query: orm.SelectForward(_source)}
}
func (_query ReportsReportSelectRelatedQuery) WithSelections(_selections ...orm.ForwardSelection[reports.Report]) ReportsReportSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_owned := append([]orm.ForwardSelection[reports.Report](nil), _query.selections...)
	_query.selections = append(_owned, _selections...)
	return _query.rebuild()
}
func (_factory ReportsReportObjectFactory) SelectTicket(_children ...orm.ForwardSelection[tickets.Ticket]) orm.ForwardSelect[reports.Report, tickets.Ticket] {
	return orm.SelectRequiredForward(_factory.ticket).WithChildren(_children...)
}
func (_query ReportsReportSelectRelatedQuery) WithTicket(_children ...orm.ForwardSelection[tickets.Ticket]) ReportsReportSelectRelatedQuery {
	return _query.WithSelections(_query.factory.SelectTicket(_children...))
}
func (_factory ReportsReportObjectFactory) selectionInputs(_paths []string) ([]orm.ForwardSelection[reports.Report], error) {
	if len(_paths) == 0 || len(_paths) > orm.MaximumForwardSelectionNodes {
		return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Detail: "forward selection requires a bounded nonempty path list"}
	}
	_result := make([]orm.ForwardSelection[reports.Report], 0, len(_paths))
	for _, _path := range _paths {
		_parts := strings.Split(_path, "__")
		if len(_parts) > query.MaximumRelationHops {
			return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "forward selection exceeds its path bound"}
		}
		for _, _part := range _parts {
			if _part == "" {
				return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "forward selection contains an empty path segment"}
			}
		}
		switch _parts[0] {
		case "ticket":
			_selection := _factory.SelectTicket()
			if len(_parts) > 1 {
				return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "selected target has no further forward relation"}
			}
			_result = append(_result, _selection)
		default:
			return nil, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Field: _path, Detail: "unknown forward selection path"}
		}
	}
	return _result, nil
}
func (_query ReportsReportSelectRelatedQuery) ParseDynamic(_paths ...string) (ReportsReportSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsReportSelectRelatedQuery{}, _query.configurationErr
	}
	_selections, _err := _query.factory.selectionInputs(_paths)
	if _err != nil {
		return ReportsReportSelectRelatedQuery{}, _err
	}
	_result := _query.WithSelections(_selections...)
	if _result.configurationErr != nil {
		return ReportsReportSelectRelatedQuery{}, _result.configurationErr
	}
	return _result, nil
}
func (_query ReportsReportSelectRelatedQuery) rebuild() ReportsReportSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_query.query = orm.SelectForward(_query.source, _query.selections...).WithSourceBinding(_query.factory.model)
	if len(_query.selections) > 0 {
		_query.configurationErr = _query.query.ConfigurationError()
	}
	return _query
}
func (_query ReportsReportSelectRelatedQuery) Filter(_values ...orm.Predicate[reports.Report]) ReportsReportSelectRelatedQuery {
	_query.source = _query.source.Filter(_values...)
	return _query.rebuild()
}
func (_query ReportsReportSelectRelatedQuery) OrderBy(_values ...orm.Ordering[reports.Report]) ReportsReportSelectRelatedQuery {
	_query.source = _query.source.OrderBy(_values...)
	return _query.rebuild()
}
func (_query ReportsReportSelectRelatedQuery) Distinct() ReportsReportSelectRelatedQuery {
	_query.source = _query.source.Distinct()
	return _query.rebuild()
}
func (_query ReportsReportSelectRelatedQuery) Fresh() ReportsReportSelectRelatedQuery {
	_query.source = _query.source.Fresh()
	return _query.rebuild()
}
func (_query ReportsReportSelectRelatedQuery) Limit(_value int) (ReportsReportSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsReportSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Limit(_value)
	if _err != nil {
		return ReportsReportSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ReportsReportSelectRelatedQuery) Offset(_value int) (ReportsReportSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ReportsReportSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Offset(_value)
	if _err != nil {
		return ReportsReportSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ReportsReportSelectRelatedQuery) All(_ctx context.Context) ([]*ReportsReportObject, error) {
	_selected, _err := _query.query.WithConfigurationError(_query.configurationErr).All(_ctx)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*ReportsReportObject, len(_selected))
	for _index := range _selected {
		_results[_index], _err = _query.wrap(_selected[_index])
		if _err != nil {
			return nil, _err
		}
	}
	return _results, nil
}
func (_query ReportsReportSelectRelatedQuery) First(_ctx context.Context) (*ReportsReportObject, bool, error) {
	_selected, _found, _err := _query.query.WithConfigurationError(_query.configurationErr).First(_ctx)
	if _err != nil || !_found {
		return nil, false, _err
	}
	_object, _err := _query.wrap(_selected)
	return _object, _err == nil, _err
}
func (_query ReportsReportSelectRelatedQuery) Count(_ctx context.Context) (int64, error) {
	return _query.query.WithConfigurationError(_query.configurationErr).Count(_ctx)
}
func (_query ReportsReportSelectRelatedQuery) wrap(_selected *orm.ForwardSelected[reports.Report]) (*ReportsReportObject, error) {
	return _query.factory.FromSelected(_selected)
}
func (_factory ReportsReportObjectFactory) FromSelected(_selected *orm.ForwardSelected[reports.Report]) (*ReportsReportObject, error) {
	if _err := _selected.ValidateSourceBinding(_factory.model); _err != nil {
		return nil, _err
	}
	_source, _err := _selected.Source()
	if _err != nil {
		return nil, _err
	}
	_backend, _err := _selected.Backend()
	if _err != nil {
		return nil, _err
	}
	_object, _err := _factory.From(_backend, _source)
	if _err != nil {
		return nil, _err
	}
	if _has, _err := _selected.HasSelection("ticket"); _err != nil {
		return nil, _err
	} else if _has {
		_related, _err := _factory.SelectTicket().Related(_selected)
		if _err != nil {
			return nil, _err
		}
		_object.ticket = _related
	}
	_object._selectedGraph = _selected
	return _object, nil
}

var _ goDjProjectSnapshot_b47a9399b87c8c316792141e4066fd45b59e7e9a76cc7d1aa2c75d96d30c2b0c
