// Code generated by GoDj. DO NOT EDIT.

package parents

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "bdc690c19ffaf2819741211cb2c985a3d347399b767962789fade6f32d07ae42"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "cascadeparents",
		Models: []ir.Model{
			{
				Name:    "label",
				GoName:  "Label",
				DBTable: "cascade_label",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "name",
						GoName:    "Name",
						Column:    "name",
						Kind:      ir.FieldChar,
						MaxLength: 64,
					},
				},
			},
			{
				Name:    "root",
				GoName:  "Root",
				DBTable: "cascade_root",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "name",
						GoName:    "Name",
						Column:    "name",
						Kind:      ir.FieldChar,
						MaxLength: 64,
					},
				},
			},
			{
				Name:    "node",
				GoName:  "Node",
				DBTable: "cascade_node",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:     "parent",
						GoName:   "ParentID",
						Column:   "parent_id",
						Kind:     ir.FieldForeignKey,
						Nullable: true,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "node"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Disabled: true},
							OnDelete:    ir.DeleteCascade,
						},
					},
				},
			},
			{
				Name:    "left",
				GoName:  "Left",
				DBTable: "cascade_left",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:     "right",
						GoName:   "RightID",
						Column:   "right_id",
						Kind:     ir.FieldForeignKey,
						Nullable: true,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "cascadedetails", ModelName: "right"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Disabled: true},
							OnDelete:    ir.DeleteCascade,
						},
					},
				},
			},
			{
				Name:    "required_left",
				GoName:  "RequiredLeft",
				DBTable: "cascade_required_left",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:   "right",
						GoName: "RightID",
						Column: "right_id",
						Kind:   ir.FieldForeignKey,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "cascadedetails", ModelName: "required_right"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Disabled: true},
							OnDelete:    ir.DeleteCascade,
						},
					},
				},
			},
			{
				Name:    "root_labels",
				GoName:  "RootLabels",
				DBTable: "cascade_root_labels",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:   "root",
						GoName: "RootID",
						Column: "root_id",
						Kind:   ir.FieldForeignKey,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "root"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Disabled: true},
							OnDelete:    ir.DeleteCascade,
						},
					},
					{
						Name:   "label",
						GoName: "LabelID",
						Column: "label_id",
						Kind:   ir.FieldForeignKey,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "cascadeparents", ModelName: "label"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Disabled: true},
							OnDelete:    ir.DeleteCascade,
						},
					},
				},
				UniqueConstraints: []ir.UniqueConstraint{
					{Name: "root_label", Fields: []string{"root", "label"}},
				},
			},
		},
	}
}

var _ GoDjProjectSnapshot_ea0973ed3504351be5d891ff30d8d4deb4e49cc243d0e436c644ce3fb29b7359
