// Code generated by GoDj. DO NOT EDIT.

package project

import (
	models "github.com/progresshans/godj/examples/helpdesk/models"
	identity "github.com/progresshans/godj/identity/models"
	"github.com/progresshans/godj/orm"
)

const GoDjProjectBindingGeneratorVersion = "godj-codegen-rel-project-v1"

func Bind() (orm.ProjectBinding, error) {
	return orm.BindProject(
		identity.GoDjRelationSchema(),
		models.GoDjRelationSchema(),
	)
}

type goDjProjectSnapshot_9e0e9d865bd4e5b0bac2917b130a6e17c36e91f77d90ccbe29479337c65acda2 struct{}

var _ goDjProjectSnapshot_9e0e9d865bd4e5b0bac2917b130a6e17c36e91f77d90ccbe29479337c65acda2
var _ identity.GoDjAppPart0_6f7db3055d02f9876abe3643e4d2ae973fc198051acff11353218653353146e4
var _ identity.GoDjAppPart1_6f7db3055d02f9876abe3643e4d2ae973fc198051acff11353218653353146e4
var _ identity.GoDjAppPart2_6f7db3055d02f9876abe3643e4d2ae973fc198051acff11353218653353146e4
var _ identity.GoDjAppPart3_6f7db3055d02f9876abe3643e4d2ae973fc198051acff11353218653353146e4
var _ models.GoDjProjectSnapshot_9e0e9d865bd4e5b0bac2917b130a6e17c36e91f77d90ccbe29479337c65acda2
