// Code generated by GoDj. DO NOT EDIT.

package project

import (
	db "github.com/progresshans/godj/db"
	models "github.com/progresshans/godj/examples/helpdesk/models"
	orm "github.com/progresshans/godj/orm"
	query "github.com/progresshans/godj/query"
	ir "github.com/progresshans/godj/schema/ir"
)

const GoDjProjectRelationReverseGeneratorVersion = "godj-codegen-rel-reverse-project-v3"

var _ orm.RelationObjectDescriptor[models.Category] = models.CategoryDescriptor{}
var _ orm.PrimaryKeyObjectDescriptor[models.Category] = models.CategoryDescriptor{}
var _ orm.RelationObjectDescriptor[models.Label] = models.LabelDescriptor{}
var _ orm.RelationObjectDescriptor[models.ServiceReport] = models.ServiceReportDescriptor{}
var _ orm.RelationObjectDescriptor[models.Ticket] = models.TicketDescriptor{}
var _ orm.PrimaryKeyObjectDescriptor[models.Ticket] = models.TicketDescriptor{}

type ModelsCategoryLabelsReverseRelation struct {
	ID   orm.RelatedIntegerField[models.Category]
	Name orm.RelatedStringField[models.Category]
}

type ModelsCategoryTicketsReverseRelation struct {
	ID      orm.RelatedIntegerField[models.Category]
	Subject orm.RelatedStringField[models.Category]
}

type ModelsCategoryReverseRelations struct {
	Labels  ModelsCategoryLabelsReverseRelation
	Tickets ModelsCategoryTicketsReverseRelation
	model   orm.BoundModel[models.Category]
}

func (_relations ModelsCategoryReverseRelations) ParseDynamic(
	_policy orm.LookupPolicy,
	_inputs []orm.LookupInput,
) ([]orm.Predicate[models.Category], error) {
	return orm.ParseDynamicReverseRelations(_relations.model, _policy, _inputs)
}

type ModelsTicketServiceReportReverseRelation struct {
	relation  orm.ReverseRelation[models.Ticket, models.ServiceReport]
	ID        orm.RelatedIntegerField[models.Ticket]
	Summary   orm.RelatedStringField[models.Ticket]
	Completed orm.RelatedBooleanField[models.Ticket]
}

func (_relation ModelsTicketServiceReportReverseRelation) IsNull(_value bool) orm.Predicate[models.Ticket] {
	return _relation.relation.IsNull(_value)
}

type ModelsTicketReverseRelations struct {
	ServiceReport ModelsTicketServiceReportReverseRelation
	model         orm.BoundModel[models.Ticket]
}

func (_relations ModelsTicketReverseRelations) ParseDynamic(
	_policy orm.LookupPolicy,
	_inputs []orm.LookupInput,
) ([]orm.Predicate[models.Ticket], error) {
	return orm.ParseDynamicReverseRelations(_relations.model, _policy, _inputs)
}

type ReverseRelations struct {
	ModelsCategory ModelsCategoryReverseRelations
	ModelsTicket   ModelsTicketReverseRelations
}

func BindReverseRelations() (ReverseRelations, error) {
	_binding, _err := Bind()
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model0, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
		models.CategoryDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model1, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "label"},
		models.LabelDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model2, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "service_report"},
		models.ServiceReportDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_model3, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "ticket"},
		models.TicketDescriptor{},
	)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_relation0, _err := orm.BindReverse(_model0, "labels", _model1)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal0, _err := _relation0.Integer(models.LabelFields.ID)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal1, _err := _relation0.String(models.LabelFields.Name)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_relation1, _err := orm.BindReverse(_model0, "tickets", _model3)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal2, _err := _relation1.Integer(models.TicketFields.ID)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal3, _err := _relation1.String(models.TicketFields.Subject)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_relation2, _err := orm.BindReverse(_model3, "service_report", _model2)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal4, _err := _relation2.Integer(models.ServiceReportFields.ID)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal5, _err := _relation2.String(models.ServiceReportFields.Summary)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	_terminal6, _err := _relation2.Boolean(models.ServiceReportFields.Completed)
	if _err != nil {
		return ReverseRelations{}, _err
	}
	return ReverseRelations{
		ModelsCategory: ModelsCategoryReverseRelations{
			Labels: ModelsCategoryLabelsReverseRelation{
				ID:   _terminal0,
				Name: _terminal1,
			},
			Tickets: ModelsCategoryTicketsReverseRelation{
				ID:      _terminal2,
				Subject: _terminal3,
			},
			model: _model0,
		},
		ModelsTicket: ModelsTicketReverseRelations{
			ServiceReport: ModelsTicketServiceReportReverseRelation{
				relation:  _relation2,
				ID:        _terminal4,
				Summary:   _terminal5,
				Completed: _terminal6,
			},
			model: _model3,
		},
	}, nil
}

type ModelsCategoryReverseObjectFactory struct {
	model   orm.BoundModel[models.Category]
	labels  orm.ReverseObject[models.Category, models.Label]
	tickets orm.ReverseObject[models.Category, models.Ticket]
}

func (_factory ModelsCategoryReverseObjectFactory) From(_backend db.Queryer, _value models.Category) (*ModelsCategoryReverseObject, error) {
	_snapshot := (models.CategoryDescriptor{}).CloneModel(_value)
	_related0, _err := _factory.labels.From(_backend, _snapshot)
	if _err != nil {
		return nil, _err
	}
	_related1, _err := _factory.tickets.From(_backend, _snapshot)
	if _err != nil {
		return nil, _err
	}
	_result := &ModelsCategoryReverseObject{
		model:   _snapshot,
		factory: _factory,
		backend: _backend,
		labels:  _related0,
		tickets: _related1,
	}
	_result._self = _result
	return _result, nil
}

type ModelsCategoryReverseObject struct {
	model   models.Category
	factory ModelsCategoryReverseObjectFactory
	backend db.Queryer
	labels  *orm.RelatedSet[models.Label]
	tickets *orm.RelatedSet[models.Ticket]
	_self   *ModelsCategoryReverseObject
}

func (_object *ModelsCategoryReverseObject) _validate() error {
	if _object == nil || _object._self != _object {
		return &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated reverse relation object is nil, zero, or copied",
		}
	}
	return nil
}

func (_object *ModelsCategoryReverseObject) Model() (models.Category, error) {
	if _err := _object._validate(); _err != nil {
		return models.Category{}, _err
	}
	return (models.CategoryDescriptor{}).CloneModel(_object.model), nil
}

func (_object *ModelsCategoryReverseObject) Labels() (*orm.RelatedSet[models.Label], error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.labels, nil
}

func (_object *ModelsCategoryReverseObject) Tickets() (*orm.RelatedSet[models.Ticket], error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.tickets, nil
}

func (_object *ModelsCategoryReverseObject) Fresh() (*ModelsCategoryReverseObject, error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.factory.From(_object.backend, _object.model)
}

type ModelsTicketReverseObjectFactory struct {
	model         orm.BoundModel[models.Ticket]
	serviceReport orm.ReverseOneToOneObject[models.Ticket, models.ServiceReport]
}

func (_factory ModelsTicketReverseObjectFactory) From(_backend db.Queryer, _value models.Ticket) (*ModelsTicketReverseObject, error) {
	_snapshot := (models.TicketDescriptor{}).CloneModel(_value)
	_related2, _err := _factory.serviceReport.From(_backend, _snapshot)
	if _err != nil {
		return nil, _err
	}
	_result := &ModelsTicketReverseObject{
		model:         _snapshot,
		factory:       _factory,
		backend:       _backend,
		serviceReport: _related2,
	}
	_result._self = _result
	return _result, nil
}

func (_factory ModelsTicketReverseObjectFactory) SelectServiceReport(_children ...orm.RelatedSelection[models.ServiceReport]) orm.RelatedSelect[models.Ticket, models.ServiceReport] {
	return orm.SelectReverseOneToOne(_factory.serviceReport).WithChildren(_children...)
}
func (_factory ModelsTicketReverseObjectFactory) FromSelected(_selected *orm.RelatedSelected[models.Ticket]) (*ModelsTicketReverseObject, error) {
	if _err := _selected.ValidateSourceBinding(_factory.model); _err != nil {
		return nil, _err
	}
	_value, _err := _selected.Source()
	if _err != nil {
		return nil, _err
	}
	_backend, _err := _selected.Backend()
	if _err != nil {
		return nil, _err
	}
	_object, _err := _factory.From(_backend, _value)
	if _err != nil {
		return nil, _err
	}
	if _has, _err := _selected.HasSelection("service_report"); _err != nil {
		return nil, _err
	} else if _has {
		_object.serviceReport, _err = _factory.SelectServiceReport().Related(_selected)
		if _err != nil {
			return nil, _err
		}
	}
	return _object, nil
}

type ModelsTicketReverseObject struct {
	model         models.Ticket
	factory       ModelsTicketReverseObjectFactory
	backend       db.Queryer
	serviceReport *orm.RelatedObject[models.ServiceReport]
	_self         *ModelsTicketReverseObject
}

func (_object *ModelsTicketReverseObject) _validate() error {
	if _object == nil || _object._self != _object {
		return &query.Error{
			Category: query.CategoryQuery,
			Code:     query.CodeInvalidPlan,
			Detail:   "generated reverse relation object is nil, zero, or copied",
		}
	}
	return nil
}

func (_object *ModelsTicketReverseObject) Model() (models.Ticket, error) {
	if _err := _object._validate(); _err != nil {
		return models.Ticket{}, _err
	}
	return (models.TicketDescriptor{}).CloneModel(_object.model), nil
}

func (_object *ModelsTicketReverseObject) ServiceReport() (*orm.RelatedObject[models.ServiceReport], error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.serviceReport, nil
}

func (_object *ModelsTicketReverseObject) Fresh() (*ModelsTicketReverseObject, error) {
	if _err := _object._validate(); _err != nil {
		return nil, _err
	}
	return _object.factory.From(_object.backend, _object.model)
}

type ReverseObjects struct {
	ModelsCategory ModelsCategoryReverseObjectFactory
	ModelsTicket   ModelsTicketReverseObjectFactory
}

func BindReverseObjects() (ReverseObjects, error) {
	_binding, _err := Bind()
	if _err != nil {
		return ReverseObjects{}, _err
	}
	return BindReverseObjectsIn(_binding)
}

// BindReverseObjectsIn composes typed relation factories in one caller-owned project binding.
func BindReverseObjectsIn(_binding orm.ProjectBinding) (ReverseObjects, error) {
	_model0, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
		models.CategoryDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model1, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "label"},
		models.LabelDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model2, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "service_report"},
		models.ServiceReportDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_model3, _err := orm.BindModel(
		_binding,
		ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "ticket"},
		models.TicketDescriptor{},
	)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_relation0, _err := orm.BindReverseObject(_model0, "labels", _model1)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_relation1, _err := orm.BindReverseObject(_model0, "tickets", _model3)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	_relation2, _err := orm.BindReverseOneToOneObject(_model3, "service_report", _model2)
	if _err != nil {
		return ReverseObjects{}, _err
	}
	return ReverseObjects{
		ModelsCategory: ModelsCategoryReverseObjectFactory{
			model:   _model0,
			labels:  _relation0,
			tickets: _relation1,
		},
		ModelsTicket: ModelsTicketReverseObjectFactory{
			model:         _model3,
			serviceReport: _relation2,
		},
	}, nil
}

var _ goDjProjectSnapshot_711be948e04bb39ffb7d1723ac96bac850e435bea11d9833f3598392def492d0
