// Code generated by GoDj. DO NOT EDIT.

package project

import (
	context "context"
	models "github.com/progresshans/godj/examples/helpdesk/models"
	orm "github.com/progresshans/godj/orm"
	query "github.com/progresshans/godj/query"
)

const GoDjProjectRelationSelectRelatedGeneratorVersion = "godj-codegen-rel-select-related-project-current-v3"

var _ orm.ProjectionDescriptor[models.Category] = models.CategoryDescriptor{}
var _ orm.ProjectionDescriptor[models.Ticket] = models.TicketDescriptor{}

type relationSelectQuery[O any] interface {
	All(context.Context) ([]*O, error)
	Count(context.Context) (int64, error)
	First(context.Context) (*O, bool, error)
}

type ModelsTicketSelectRelatedQuery struct {
	factory          ModelsTicketObjectFactory
	source           orm.QuerySet[models.Ticket]
	query            orm.ForwardSelectQuery[models.Ticket]
	selections       []orm.ForwardSelection[models.Ticket]
	configurationErr error
	_selectCategory  orm.ForwardSelect[models.Ticket, models.Category]
}

func (_factory ModelsTicketObjectFactory) SelectRelated(_source orm.QuerySet[models.Ticket]) ModelsTicketSelectRelatedQuery {
	return ModelsTicketSelectRelatedQuery{factory: _factory, source: _source, query: orm.SelectForward(_source)}
}
func (_query ModelsTicketSelectRelatedQuery) WithCategory() ModelsTicketSelectRelatedQuery {
	if _query.configurationErr != nil {
		return _query
	}
	_path, _err := orm.ResolveForwardSelectPath(_query.factory.model, "category")
	if _err != nil {
		_query.configurationErr = _err
		return _query
	}
	_selection, _err := orm.BindRequiredForwardSelect(_path, _query.factory.category)
	if _err != nil {
		_query.configurationErr = _err
		return _query
	}
	_query._selectCategory = _selection
	_targets := append([]orm.ForwardSelection[models.Ticket](nil), _query.selections...)
	_query.selections = append(_targets, _selection)
	_query.query = orm.SelectForward(_query.source, _query.selections...)
	return _query
}
func (_query ModelsTicketSelectRelatedQuery) ParseDynamic(_paths ...string) (ModelsTicketSelectRelatedQuery, error) {
	if len(_paths) == 0 {
		return ModelsTicketSelectRelatedQuery{}, &query.Error{Category: query.CategoryField, Code: query.CodeInvalidRelatedPath, Detail: "select-related requires at least one direct relation name"}
	}
	if _query.configurationErr != nil {
		return ModelsTicketSelectRelatedQuery{}, _query.configurationErr
	}
	for _, _path := range _paths {
		switch _path {
		case "category":
			_query = _query.WithCategory()
		default:
			if _, _err := orm.ResolveForwardSelectPath(_query.factory.model, _path); _err != nil {
				return ModelsTicketSelectRelatedQuery{}, _err
			}
			return ModelsTicketSelectRelatedQuery{}, &query.Error{Category: query.CategoryQuery, Code: query.CodeInvalidPlan, Detail: "resolved forward selection is missing generated dispatch"}
		}
		if _query.configurationErr != nil {
			return ModelsTicketSelectRelatedQuery{}, _query.configurationErr
		}
	}
	return _query, nil
}
func (_query ModelsTicketSelectRelatedQuery) rebuild() ModelsTicketSelectRelatedQuery {
	_query.query = orm.SelectForward(_query.source, _query.selections...)
	return _query
}
func (_query ModelsTicketSelectRelatedQuery) Filter(_values ...orm.Predicate[models.Ticket]) ModelsTicketSelectRelatedQuery {
	_query.source = _query.source.Filter(_values...)
	return _query.rebuild()
}
func (_query ModelsTicketSelectRelatedQuery) OrderBy(_values ...orm.Ordering[models.Ticket]) ModelsTicketSelectRelatedQuery {
	_query.source = _query.source.OrderBy(_values...)
	return _query.rebuild()
}
func (_query ModelsTicketSelectRelatedQuery) Distinct() ModelsTicketSelectRelatedQuery {
	_query.source = _query.source.Distinct()
	return _query.rebuild()
}
func (_query ModelsTicketSelectRelatedQuery) Fresh() ModelsTicketSelectRelatedQuery {
	_query.source = _query.source.Fresh()
	return _query.rebuild()
}
func (_query ModelsTicketSelectRelatedQuery) Limit(_value int) (ModelsTicketSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ModelsTicketSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Limit(_value)
	if _err != nil {
		return ModelsTicketSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ModelsTicketSelectRelatedQuery) Offset(_value int) (ModelsTicketSelectRelatedQuery, error) {
	if _query.configurationErr != nil {
		return ModelsTicketSelectRelatedQuery{}, _query.configurationErr
	}
	_source, _err := _query.source.Offset(_value)
	if _err != nil {
		return ModelsTicketSelectRelatedQuery{}, _err
	}
	_query.source = _source
	return _query.rebuild(), nil
}
func (_query ModelsTicketSelectRelatedQuery) All(_ctx context.Context) ([]*ModelsTicketObject, error) {
	_selected, _err := _query.query.WithConfigurationError(_query.configurationErr).All(_ctx)
	if _err != nil {
		return nil, _err
	}
	_results := make([]*ModelsTicketObject, len(_selected))
	for _index := range _selected {
		_results[_index], _err = _query.wrap(_selected[_index])
		if _err != nil {
			return nil, _err
		}
	}
	return _results, nil
}
func (_query ModelsTicketSelectRelatedQuery) First(_ctx context.Context) (*ModelsTicketObject, bool, error) {
	_selected, _found, _err := _query.query.WithConfigurationError(_query.configurationErr).First(_ctx)
	if _err != nil || !_found {
		return nil, false, _err
	}
	_object, _err := _query.wrap(_selected)
	return _object, _err == nil, _err
}
func (_query ModelsTicketSelectRelatedQuery) Count(_ctx context.Context) (int64, error) {
	return _query.query.WithConfigurationError(_query.configurationErr).Count(_ctx)
}
func (_query ModelsTicketSelectRelatedQuery) wrap(_selected *orm.ForwardSelected[models.Ticket]) (*ModelsTicketObject, error) {
	_source, _err := _selected.Source()
	if _err != nil {
		return nil, _err
	}
	_object, _err := _query.factory.From(_query.query.Backend(), _source)
	if _err != nil {
		return nil, _err
	}
	if _has, _err := _selected.HasSelection("category"); _err != nil {
		return nil, _err
	} else if _has {
		_related, _err := _query._selectCategory.Related(_selected)
		if _err != nil {
			return nil, _err
		}
		_object.category = _related
	}
	return _object, nil
}

var _ goDjProjectSnapshot_41fb8043313deb900f92e07e6f03c44e279b95f5fce5533200ee8a06765e2cb1
