// Code generated by GoDj. DO NOT EDIT.

package models

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "29a15b0d8731e9341ea621a745ce0c2a0cb5ecb0fc78823b528fcbbec75a7371"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "helpdesk",
		Models: []ir.Model{
			{
				Name:    "category",
				GoName:  "Category",
				DBTable: "helpdesk_category",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "name",
						GoName:    "Name",
						Column:    "name",
						Kind:      ir.FieldChar,
						MaxLength: 60,
					},
				},
			},
			{
				Name:    "ticket",
				GoName:  "Ticket",
				DBTable: "helpdesk_ticket",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "subject",
						GoName:    "Subject",
						Column:    "subject",
						Kind:      ir.FieldChar,
						MaxLength: 120,
					},
					{
						Name:      "details",
						GoName:    "Details",
						Column:    "details",
						Kind:      ir.FieldChar,
						Nullable:  true,
						MaxLength: 400,
					},
					{
						Name:    "closed",
						GoName:  "Closed",
						Column:  "closed",
						Kind:    ir.FieldBoolean,
						Default: &ir.Scalar{Kind: ir.ScalarBoolean, Boolean: false},
					},
					{
						Name:   "category",
						GoName: "CategoryID",
						Column: "category_id",
						Kind:   ir.FieldForeignKey,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Name: "tickets"},
							OnDelete:    ir.DeleteProtect,
						},
					},
					{
						Name:     "priority",
						GoName:   "Priority",
						Column:   "priority",
						Kind:     ir.FieldInteger,
						Nullable: true,
						Choices: []ir.Choice{
							{Value: ir.Scalar{Kind: ir.ScalarInteger, Integer: 1}, Label: "Urgent"},
							{Value: ir.Scalar{Kind: ir.ScalarInteger, Integer: 0}, Label: "Normal"},
							{Value: ir.Scalar{Kind: ir.ScalarInteger, Integer: -1}, Label: "Low"},
						},
					},
					{
						Name:     "resolution",
						GoName:   "Resolution",
						Column:   "resolution",
						Kind:     ir.FieldText,
						Nullable: true,
					},
					{
						Name:     "due_at",
						GoName:   "DueAt",
						Column:   "due_at",
						Kind:     ir.FieldDateTime,
						Nullable: true,
					},
					{
						Name:     "reviewed",
						GoName:   "Reviewed",
						Column:   "reviewed",
						Kind:     ir.FieldBoolean,
						Nullable: true,
					},
					{
						Name:     "service_on",
						GoName:   "ServiceOn",
						Column:   "service_on",
						Kind:     ir.FieldDate,
						Nullable: true,
					},
				},
			},
		},
	}
}

var _ GoDjProjectSnapshot_dfd944da001338ab1c78aecd18e7f8ca6b65420cbdcdc5c94b174933ba62a296
