// Code generated by GoDj. DO NOT EDIT.

package models

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
	"reflect"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v1"
const GoDjRelationObjectSchemaSHA256 = "eb59105d62af118882f3951491ff1934fefdeb530bec42e446384083cc1da786"

var _ orm.RelationObjectDescriptor[Category] = CategoryDescriptor{}

func (CategoryDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Category] {
	return CategoryDescriptor{}
}

func (CategoryDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Category], bool) {
	return nil, false
}

var _ orm.RelationObjectDescriptor[Ticket] = TicketDescriptor{}

func (TicketDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Ticket] {
	return TicketDescriptor{}
}

func (TicketDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Ticket], bool) {
	switch {
	case reflect.DeepEqual(field, (ticketCategoryIDRelationStorage{}).Field()):
		return ticketCategoryIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type ticketCategoryIDRelationStorage struct{}

var _ orm.RelationStorage[Ticket] = ticketCategoryIDRelationStorage{}

func (ticketCategoryIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "category",
		GoName: "CategoryID",
		Column: "category_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "tickets"},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (ticketCategoryIDRelationStorage) Value(value Ticket) (query.Value, bool) {
	return query.Integer(value.CategoryID), true
}

var _ GoDjProjectSnapshot_258eb010b1b5ac237fc882f1e6c5d4eb1f69a94a16ebe0c386bda77cfb4566ab
