// Code generated by GoDj. DO NOT EDIT.

package models

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "aaa9e2604e3c124bc223445379f19c9696df71b60b4f38cbee853e571b6962f2"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "helpdesk",
		Models: []ir.Model{
			{
				Name:    "category",
				GoName:  "Category",
				DBTable: "helpdesk_category",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "name",
						GoName:    "Name",
						Column:    "name",
						Kind:      ir.FieldChar,
						MaxLength: 60,
					},
				},
			},
			{
				Name:    "ticket",
				GoName:  "Ticket",
				DBTable: "helpdesk_ticket",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "subject",
						GoName:    "Subject",
						Column:    "subject",
						Kind:      ir.FieldChar,
						MaxLength: 120,
					},
					{
						Name:      "details",
						GoName:    "Details",
						Column:    "details",
						Kind:      ir.FieldChar,
						Nullable:  true,
						MaxLength: 400,
					},
					{
						Name:    "closed",
						GoName:  "Closed",
						Column:  "closed",
						Kind:    ir.FieldBoolean,
						Default: &ir.Scalar{Kind: ir.ScalarBoolean, Boolean: false},
					},
					{
						Name:   "category",
						GoName: "CategoryID",
						Column: "category_id",
						Kind:   ir.FieldForeignKey,
						Relation: &ir.ForeignKeyRelation{
							Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
							Cardinality: ir.RelationManyToOne,
							Reverse:     ir.ReverseRelation{Name: "tickets"},
							OnDelete:    ir.DeleteProtect,
						},
					},
					{
						Name:     "priority",
						GoName:   "Priority",
						Column:   "priority",
						Kind:     ir.FieldInteger,
						Nullable: true,
						Choices: []ir.Choice{
							{Value: ir.Scalar{Kind: ir.ScalarInteger, Integer: 1}, Label: "Urgent"},
							{Value: ir.Scalar{Kind: ir.ScalarInteger, Integer: 0}, Label: "Normal"},
							{Value: ir.Scalar{Kind: ir.ScalarInteger, Integer: -1}, Label: "Low"},
						},
					},
					{
						Name:     "resolution",
						GoName:   "Resolution",
						Column:   "resolution",
						Kind:     ir.FieldText,
						Nullable: true,
					},
					{
						Name:     "due_at",
						GoName:   "DueAt",
						Column:   "due_at",
						Kind:     ir.FieldDateTime,
						Nullable: true,
					},
					{
						Name:     "reviewed",
						GoName:   "Reviewed",
						Column:   "reviewed",
						Kind:     ir.FieldBoolean,
						Nullable: true,
					},
					{
						Name:     "service_on",
						GoName:   "ServiceOn",
						Column:   "service_on",
						Kind:     ir.FieldDate,
						Nullable: true,
					},
					{
						Name:     "service_at",
						GoName:   "ServiceAt",
						Column:   "service_at",
						Kind:     ir.FieldTime,
						Nullable: true,
					},
				},
			},
		},
	}
}

var _ GoDjProjectSnapshot_536c681a9e1e19bb1e360c1bc87482f9d4c63fc328a1e0782c88f8c6fd9256c0
