// Code generated by GoDj. DO NOT EDIT.

package models

import (
	"database/sql"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
)

const GoDjRelationProjectionGeneratorVersion = "godj-codegen-rel-projection-v1"
const GoDjRelationProjectionSchemaSHA256 = "01ef17b1156f01dd42d93fd8ce56cea1ba26b102e07e47ea29e5b5a3fdeec865"

var _ orm.ProjectionDescriptor[Category] = CategoryDescriptor{}

func (CategoryDescriptor) NewProjectionScan() orm.ProjectionScan[Category] {
	return &categoryProjectionScan{}
}

type categoryProjectionScan struct {
	scanID   sql.NullInt64
	scanName sql.NullString
}

func (_scan *categoryProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanName,
	}
}

func (_scan *categoryProjectionScan) Decode() (Category, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Category{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanName.Valid {
		return Category{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Category{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanName.Valid {
		return Category{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Category{}
	_value.ID = _scan.scanID.Int64
	_value.Name = _scan.scanName.String
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ orm.ProjectionDescriptor[Ticket] = TicketDescriptor{}

func (TicketDescriptor) NewProjectionScan() orm.ProjectionScan[Ticket] {
	return &ticketProjectionScan{scanExpectedCost: orm.NewNullableDecimalScanner(14, 2)}
}

type ticketProjectionScan struct {
	scanID                sql.NullInt64
	scanSubject           sql.NullString
	scanDetails           sql.NullString
	scanClosed            sql.NullBool
	scanCategoryID        sql.NullInt64
	scanPriority          sql.NullInt64
	scanResolution        sql.NullString
	scanDueAt             orm.NullableDateTimeScanner
	scanReviewed          sql.NullBool
	scanServiceOn         orm.NullableDateScanner
	scanServiceAt         orm.NullableTimeScanner
	scanElapsed           orm.NullableDurationScanner
	scanEffort            orm.NullableFloatScanner
	scanExpectedCost      orm.NullableDecimalScanner
	scanExternalReference orm.NullableUUIDScanner
}

func (_scan *ticketProjectionScan) Destinations() []any {
	if _scan == nil {
		return nil
	}
	return []any{
		&_scan.scanID,
		&_scan.scanSubject,
		&_scan.scanDetails,
		&_scan.scanClosed,
		&_scan.scanCategoryID,
		&_scan.scanPriority,
		&_scan.scanResolution,
		&_scan.scanDueAt,
		&_scan.scanReviewed,
		&_scan.scanServiceOn,
		&_scan.scanServiceAt,
		&_scan.scanElapsed,
		&_scan.scanEffort,
		&_scan.scanExpectedCost,
		&_scan.scanExternalReference,
	}
}

func (_scan *ticketProjectionScan) Decode() (Ticket, query.Value, orm.ProjectionPresence) {
	if _scan == nil {
		return Ticket{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanID.Valid && !_scan.scanSubject.Valid && !_scan.scanDetails.Valid && !_scan.scanClosed.Valid && !_scan.scanCategoryID.Valid && !_scan.scanPriority.Valid && !_scan.scanResolution.Valid && !_scan.scanDueAt.Valid && !_scan.scanReviewed.Valid && !_scan.scanServiceOn.Valid && !_scan.scanServiceAt.Valid && !_scan.scanElapsed.Valid && !_scan.scanEffort.Valid && !_scan.scanExpectedCost.Valid && !_scan.scanExternalReference.Valid {
		return Ticket{}, query.Null(), orm.ProjectionAbsent
	}
	if !_scan.scanID.Valid {
		return Ticket{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanSubject.Valid {
		return Ticket{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanClosed.Valid {
		return Ticket{}, query.Value{}, orm.ProjectionInvalid
	}
	if !_scan.scanCategoryID.Valid {
		return Ticket{}, query.Value{}, orm.ProjectionInvalid
	}
	_value := Ticket{}
	_value.ID = _scan.scanID.Int64
	_value.Subject = _scan.scanSubject.String
	if _scan.scanDetails.Valid {
		_scanned := _scan.scanDetails.String
		_value.Details = &_scanned
	}
	_value.Closed = _scan.scanClosed.Bool
	_value.CategoryID = _scan.scanCategoryID.Int64
	if _scan.scanPriority.Valid {
		_scanned := _scan.scanPriority.Int64
		_value.Priority = &_scanned
	}
	if _scan.scanResolution.Valid {
		_scanned := _scan.scanResolution.String
		_value.Resolution = &_scanned
	}
	if _scan.scanDueAt.Valid {
		_scanned := _scan.scanDueAt.Time
		_value.DueAt = &_scanned
	}
	if _scan.scanReviewed.Valid {
		_scanned := _scan.scanReviewed.Bool
		_value.Reviewed = &_scanned
	}
	if _scan.scanServiceOn.Valid {
		_scanned := _scan.scanServiceOn.Date
		_value.ServiceOn = &_scanned
	}
	if _scan.scanServiceAt.Valid {
		_scanned := _scan.scanServiceAt.Time
		_value.ServiceAt = &_scanned
	}
	if _scan.scanElapsed.Valid {
		_scanned := _scan.scanElapsed.Duration
		_value.Elapsed = &_scanned
	}
	if _scan.scanEffort.Valid {
		_scanned := _scan.scanEffort.Float
		_value.Effort = &_scanned
	}
	if _scan.scanExpectedCost.Valid {
		_scanned := _scan.scanExpectedCost.Decimal
		_value.ExpectedCost = &_scanned
	}
	if _scan.scanExternalReference.Valid {
		_scanned := _scan.scanExternalReference.UUID
		_value.ExternalReference = &_scanned
	}
	_value.godjPrimaryKeyPresent = true
	return _value, query.Integer(_scan.scanID.Int64), orm.ProjectionPresent
}

var _ GoDjProjectSnapshot_42928d3e7a9d5f616bdf7b1f2be94a84a1c745bf324c328699e310de9b979cc5
