// Code generated by GoDj. DO NOT EDIT.

package models

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
	"reflect"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v2"
const GoDjRelationObjectSchemaSHA256 = "e9c1d9c7cbb5bf6e6a84963653497a4f608c3cac105a74aee21362ca36bd6eb4"

var _ orm.RelationObjectDescriptor[Category] = CategoryDescriptor{}

func (CategoryDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Category] {
	return CategoryDescriptor{}
}

func (CategoryDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Category], bool) {
	return nil, false
}

var _ orm.RelationObjectDescriptor[Ticket] = TicketDescriptor{}

func (TicketDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Ticket] {
	return TicketDescriptor{}
}

func (TicketDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Ticket], bool) {
	switch {
	case reflect.DeepEqual(field, (ticketCategoryIDRelationStorage{}).Field()):
		return ticketCategoryIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type ticketCategoryIDRelationStorage struct{}

var _ orm.RelationStorage[Ticket] = ticketCategoryIDRelationStorage{}

func (ticketCategoryIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "category",
		GoName: "CategoryID",
		Column: "category_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "tickets"},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (ticketCategoryIDRelationStorage) Value(value Ticket) (query.Value, bool) {
	return query.Integer(value.CategoryID), true
}

var _ orm.RelationObjectDescriptor[ServiceReport] = ServiceReportDescriptor{}

func (ServiceReportDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[ServiceReport] {
	return ServiceReportDescriptor{}
}

func (ServiceReportDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[ServiceReport], bool) {
	switch {
	case reflect.DeepEqual(field, (serviceReportTicketIDRelationStorage{}).Field()):
		return serviceReportTicketIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type serviceReportTicketIDRelationStorage struct{}

var _ orm.RelationStorage[ServiceReport] = serviceReportTicketIDRelationStorage{}

func (serviceReportTicketIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "ticket",
		GoName: "TicketID",
		Column: "ticket_id",
		Kind:   ir.FieldForeignKey,
		Unique: true,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "ticket"},
			Cardinality: ir.RelationOneToOne,
			Reverse:     ir.ReverseRelation{Name: "service_report"},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (serviceReportTicketIDRelationStorage) Value(value ServiceReport) (query.Value, bool) {
	return query.Integer(value.TicketID), true
}

var _ orm.RelationObjectDescriptor[Label] = LabelDescriptor{}

func (LabelDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Label] {
	return LabelDescriptor{}
}

func (LabelDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Label], bool) {
	switch {
	case reflect.DeepEqual(field, (labelCategoryIDRelationStorage{}).Field()):
		return labelCategoryIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type labelCategoryIDRelationStorage struct{}

var _ orm.RelationStorage[Label] = labelCategoryIDRelationStorage{}

func (labelCategoryIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "category",
		GoName: "CategoryID",
		Column: "category_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "category"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "labels"},
			OnDelete:    ir.DeleteProtect,
		},
	}
}

func (labelCategoryIDRelationStorage) Value(value Label) (query.Value, bool) {
	return query.Integer(value.CategoryID), true
}

var _ orm.RelationObjectDescriptor[TicketLabel] = TicketLabelDescriptor{}

func (TicketLabelDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[TicketLabel] {
	return TicketLabelDescriptor{}
}

func (TicketLabelDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[TicketLabel], bool) {
	switch {
	case reflect.DeepEqual(field, (ticketLabelTicketIDRelationStorage{}).Field()):
		return ticketLabelTicketIDRelationStorage{}, true
	case reflect.DeepEqual(field, (ticketLabelLabelIDRelationStorage{}).Field()):
		return ticketLabelLabelIDRelationStorage{}, true
	default:
		return nil, false
	}
}

type ticketLabelTicketIDRelationStorage struct{}

var _ orm.RelationStorage[TicketLabel] = ticketLabelTicketIDRelationStorage{}

func (ticketLabelTicketIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "ticket",
		GoName: "TicketID",
		Column: "ticket_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "ticket"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "label_links"},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (ticketLabelTicketIDRelationStorage) Value(value TicketLabel) (query.Value, bool) {
	return query.Integer(value.TicketID), true
}

type ticketLabelLabelIDRelationStorage struct{}

var _ orm.RelationStorage[TicketLabel] = ticketLabelLabelIDRelationStorage{}

func (ticketLabelLabelIDRelationStorage) Field() ir.Field {
	return ir.Field{
		Name:   "label",
		GoName: "LabelID",
		Column: "label_id",
		Kind:   ir.FieldForeignKey,
		Relation: &ir.ForeignKeyRelation{
			Target:      ir.ModelIdentity{AppLabel: "helpdesk", ModelName: "label"},
			Cardinality: ir.RelationManyToOne,
			Reverse:     ir.ReverseRelation{Name: "ticket_links"},
			OnDelete:    ir.DeleteCascade,
		},
	}
}

func (ticketLabelLabelIDRelationStorage) Value(value TicketLabel) (query.Value, bool) {
	return query.Integer(value.LabelID), true
}

func (TicketLabelDescriptor) ManyToManyCreateInput() orm.ManyToManyInput[TicketLabel] {
	return TicketLabelCreate{}
}

var _ orm.ManyToManyDescriptor[TicketLabel] = TicketLabelDescriptor{}

func (input TicketLabelCreate) BuildManyToManyCreate(source, target ir.Field, sourceKey, targetKey int64) orm.Mutation[TicketLabel] {
	invalid := func() orm.Mutation[TicketLabel] {
		return orm.InvalidMutation[TicketLabel](&query.Error{Category: query.CategoryQuery, Code: query.CodeInvalidPlan, Detail: "collection endpoints must be distinct canonical ForeignKeys omitted from through defaults"})
	}
	if source.Name == target.Name {
		return invalid()
	}
	for index, field := range []ir.Field{source, target} {
		key := sourceKey
		if index == 1 {
			key = targetKey
		}
		switch {
		case reflect.DeepEqual(field, (ticketLabelTicketIDRelationStorage{}).Field()):
			if _, set := input.ticketID.Get(); set {
				return invalid()
			}
			input = input.WithTicketID(key)
		case reflect.DeepEqual(field, (ticketLabelLabelIDRelationStorage{}).Field()):
			if _, set := input.labelID.Get(); set {
				return invalid()
			}
			input = input.WithLabelID(key)
		default:
			return invalid()
		}
	}
	return input.BuildCreate()
}

type GoDjAppPart2_5f42928abb0fb813592b966c9b1b9789e769333be7a003a856368dc1a5aa06db struct{}

var _ GoDjProjectSnapshot_01efd02b97c148b997a6bac28221395d42f9498242cb45508c950a2d50926966
