// Code generated by GoDj. DO NOT EDIT.

package tickets

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "955fb5aa2506fb06f360557f3b50285cee4f8c00bab1468d3ec5872356cbb817"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "ototickets",
		Models: []ir.Model{
			{
				Name:    "ticket",
				GoName:  "Ticket",
				DBTable: "ototickets_ticket",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "subject",
						GoName:    "Subject",
						Column:    "subject",
						Kind:      ir.FieldChar,
						MaxLength: 80,
					},
				},
			},
		},
	}
}

var _ GoDjProjectSnapshot_b059cfd7580b4400ac9f250875f3fa95fdaf949f3c6e3c2ad6cad753f4b4a592
