// Code generated by GoDj. DO NOT EDIT.

package tickets

import (
	"github.com/progresshans/godj/db"
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/query"
	"github.com/progresshans/godj/schema/ir"
)

const GoDjGeneratorVersion = "godj-codegen-current-v1"
const GoDjSchemaSHA256 = "955fb5aa2506fb06f360557f3b50285cee4f8c00bab1468d3ec5872356cbb817"

type Ticket struct {
	ID                    int64
	Subject               string
	godjPrimaryKeyPresent bool
}

type TicketDescriptor struct{}

var _ orm.ModelDescriptor[Ticket] = TicketDescriptor{}

var _ orm.WriteDescriptor[Ticket] = TicketDescriptor{}

func (TicketDescriptor) Metadata() ir.Model {
	return ticketMetadata()
}

func (TicketDescriptor) Scan(row db.Row) (Ticket, error) {
	var value Ticket
	if err := row.Scan(&value.ID, &value.Subject); err != nil {
		return Ticket{}, err
	}
	value.godjPrimaryKeyPresent = true
	return value, nil
}

func (TicketDescriptor) PrimaryKey(value Ticket) (query.Value, bool) {
	return query.Integer(value.ID), value.godjPrimaryKeyPresent
}

func (TicketDescriptor) SetPrimaryKey(value *Ticket, key int64) {
	value.ID = key
	value.godjPrimaryKeyPresent = true
}

func (TicketDescriptor) ClearPrimaryKey(value *Ticket) {
	value.ID = 0
	value.godjPrimaryKeyPresent = false
}

func (TicketDescriptor) CloneModel(value Ticket) Ticket {
	clone := value
	return clone
}

func (descriptor TicketDescriptor) CloneWriteModel(value Ticket) Ticket {
	return descriptor.CloneModel(value)
}

func (TicketDescriptor) WriteFieldValue(value Ticket, field ir.Field) (query.Value, bool) {
	switch field.Name {
	case "id":
		return query.Integer(value.ID), true
	case "subject":
		return query.String(value.Subject), true
	default:
		return query.Value{}, false
	}
}

type TicketFieldSet struct {
	ID      orm.AutoField[Ticket]
	Subject orm.StringField[Ticket]
}

var TicketFields = func() TicketFieldSet {
	metadata := ticketMetadata()
	return TicketFieldSet{
		ID:      orm.NewAutoField[Ticket](metadata.Fields[0]),
		Subject: orm.NewStringField[Ticket](metadata.Fields[1]),
	}
}()

var TicketObjects = orm.NewManager[Ticket](TicketDescriptor{})

func NewTicketWithID(key int64) Ticket {
	return Ticket{ID: key, godjPrimaryKeyPresent: true}
}

func TicketUpdateFields(fields ...orm.WritableField[Ticket]) orm.SaveOption[Ticket] {
	return orm.UpdateFields(fields...)
}

func TicketUpdateFieldNames(names ...string) orm.SaveOption[Ticket] {
	return orm.UpdateFieldNames[Ticket](names...)
}

func TicketForceInsert() orm.SaveOption[Ticket] {
	return orm.ForceInsert[Ticket]()
}

func TicketForceUpdate() orm.SaveOption[Ticket] {
	return orm.ForceUpdate[Ticket]()
}

type TicketCreate struct {
	subject orm.Change[string]
}

func NewTicketCreate(subject string) TicketCreate {
	return TicketCreate{
		subject: orm.Set(subject),
	}
}

func (input TicketCreate) WithSubject(value string) TicketCreate {
	input.subject = orm.Set(value)
	return input
}

func (input TicketCreate) BuildCreate() orm.Mutation[Ticket] {
	var value Ticket
	assignments := make([]query.Assignment, 0, 1)
	changedSubject, changedSubjectSet := input.subject.Get()
	if !changedSubjectSet {
		return orm.InvalidMutation[Ticket](&query.Error{
			Category: query.CategoryField,
			Code:     query.CodeRequiredField,
			Field:    "subject",
			Detail:   "required create field is omitted",
		})
	}
	value.Subject = changedSubject
	assignments = append(assignments, query.NewAssignment(query.NewFieldRef("subject", "subject", query.FieldString, false), query.String(changedSubject)))
	return orm.NewCreateMutation(value, "ototickets_ticket", assignments)
}

type TicketPatch struct {
	subject orm.Change[string]
}

func (input TicketPatch) WithSubject(value string) TicketPatch {
	input.subject = orm.Set(value)
	return input
}

func (input TicketPatch) BuildPatch(current Ticket) orm.Mutation[Ticket] {
	value := current
	assignments := make([]query.Assignment, 0, 1)
	if changedSubject, ok := input.subject.Get(); ok {
		value.Subject = changedSubject
		assignments = append(assignments, query.NewAssignment(query.NewFieldRef("subject", "subject", query.FieldString, false), query.String(changedSubject)))
	}
	return orm.NewPatchMutation(value, "ototickets_ticket", assignments)
}

func ticketMetadata() ir.Model {
	return ir.Model{
		Name:    "ticket",
		GoName:  "Ticket",
		DBTable: "ototickets_ticket",
		Fields: []ir.Field{
			{
				Name:       "id",
				GoName:     "ID",
				Column:     "id",
				Kind:       ir.FieldAuto,
				PrimaryKey: true,
			},
			{
				Name:      "subject",
				GoName:    "Subject",
				Column:    "subject",
				Kind:      ir.FieldChar,
				MaxLength: 80,
			},
		},
	}
}

type GoDjProjectSnapshot_485a268a23b9a93273af0500ae0bff7006c2a6e7d3021644c91a83be5af3a40a struct{}
