// Code generated by GoDj. DO NOT EDIT.

package tickets

import "github.com/progresshans/godj/schema/ir"

const GoDjRelationMetadataGeneratorVersion = "godj-codegen-rel-metadata-current-v1"
const GoDjRelationSchemaSHA256 = "955fb5aa2506fb06f360557f3b50285cee4f8c00bab1468d3ec5872356cbb817"

func GoDjRelationSchema() ir.Schema {
	return ir.Schema{
		FormatVersion: ir.CurrentFormatVersion,
		AppLabel:      "ototickets",
		Models: []ir.Model{
			{
				Name:    "ticket",
				GoName:  "Ticket",
				DBTable: "ototickets_ticket",
				Fields: []ir.Field{
					{
						Name:       "id",
						GoName:     "ID",
						Column:     "id",
						Kind:       ir.FieldAuto,
						PrimaryKey: true,
					},
					{
						Name:      "subject",
						GoName:    "Subject",
						Column:    "subject",
						Kind:      ir.FieldChar,
						MaxLength: 80,
					},
				},
			},
		},
	}
}

type GoDjAppPart1_1c78b39b7807df204d08f060ff604fdc3e7659e6f6ff228c6a5777a88c714ac8 struct{}

var _ GoDjProjectSnapshot_42a639519df299826f4864a6748c8726f5ab769f06d7c0fe7b37ba59fa952001
