package relationbinding

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

const externalModule = "example.com/godj-relationbinding-external"

func TestExternalMutualAndSelfRelationModuleCompilesWithoutAppImportEdges(t *testing.T) {
	project := copyExternalFixture(t)
	outputPath := filepath.Join(project, "bridge", "zz_bindings.go")
	initial := readTestFile(t, outputPath)

	if err := generateAndPublishExternalBindings(relationFixture(), outputPath, project, false); err != nil {
		t.Fatalf("publish valid generated binding: %v", err)
	}
	first := readTestFile(t, outputPath)
	if bytes.Equal(initial, first) || !bytes.Contains(first, []byte("authors.author.favorite_post")) || !bytes.Contains(first, []byte("blog.post.author")) {
		t.Fatalf("valid generation did not publish mutual/self bindings:\n%s", first)
	}
	if err := generateAndPublishExternalBindings(relationFixture(), outputPath, project, false); err != nil {
		t.Fatalf("repeat valid generation: %v", err)
	}
	if second := readTestFile(t, outputPath); !bytes.Equal(first, second) {
		t.Fatalf("same binding generated different bytes\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	missing := relationFixture()
	missing[1].Relations[0].Target = modelKey{App: "missing", Model: "target"}
	if err := generateAndPublishExternalBindings(missing, outputPath, project, false); err == nil {
		t.Fatal("unresolved target unexpectedly generated output")
	}
	if after := readTestFile(t, outputPath); !bytes.Equal(first, after) {
		t.Fatal("binding failure changed last-good generated bytes")
	}

	if err := generateAndPublishExternalBindings(relationFixture(), outputPath, project, true); err == nil || !strings.Contains(err.Error(), "candidate compile") {
		t.Fatalf("compile-poisoned candidate error = %v, want candidate compile failure", err)
	}
	if after := readTestFile(t, outputPath); !bytes.Equal(first, after) {
		t.Fatal("candidate compile failure changed last-good generated bytes")
	}
	if candidates, err := filepath.Glob(filepath.Join(project, "bridge", ".godj-relation-candidate-*.go")); err != nil || len(candidates) != 0 {
		t.Fatalf("candidate files remain after failure: %v, err=%v", candidates, err)
	}

	assertExternalImportGraph(t, project)
	runExternalGo(t, project, "test", "-count=1", "./...")
}

func generateAndPublishExternalBindings(models []modelDescriptor, outputPath, moduleRoot string, poisonCompile bool) error {
	set, err := bindProject(models)
	if err != nil {
		return fmt.Errorf("bind before generation: %w", err)
	}
	source, err := renderExternalBindings(set, poisonCompile)
	if err != nil {
		return err
	}

	absoluteOutput, err := filepath.Abs(outputPath)
	if err != nil {
		return fmt.Errorf("resolve last-good output: %w", err)
	}
	if _, err := os.Stat(absoluteOutput); err != nil {
		return fmt.Errorf("stat last-good output: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(absoluteOutput); err == nil {
		absoluteOutput = resolved
	}
	candidate, err := os.CreateTemp(filepath.Dir(absoluteOutput), ".godj-relation-candidate-*.go")
	if err != nil {
		return fmt.Errorf("create generated candidate: %w", err)
	}
	candidatePath := candidate.Name()
	if resolved, err := filepath.EvalSymlinks(candidatePath); err == nil {
		candidatePath = resolved
	}
	defer os.Remove(candidatePath)
	if err := candidate.Chmod(0o644); err != nil {
		candidate.Close()
		return fmt.Errorf("chmod generated candidate: %w", err)
	}
	if _, err := candidate.Write(source); err != nil {
		candidate.Close()
		return fmt.Errorf("write generated candidate: %w", err)
	}
	if err := candidate.Sync(); err != nil {
		candidate.Close()
		return fmt.Errorf("sync generated candidate: %w", err)
	}
	if err := candidate.Close(); err != nil {
		return fmt.Errorf("close generated candidate: %w", err)
	}

	overlayFile, err := os.CreateTemp(moduleRoot, ".godj-relation-overlay-*.json")
	if err != nil {
		return fmt.Errorf("create candidate overlay: %w", err)
	}
	overlayPath := overlayFile.Name()
	defer os.Remove(overlayPath)
	if err := json.NewEncoder(overlayFile).Encode(struct {
		Replace map[string]string
	}{Replace: map[string]string{absoluteOutput: candidatePath}}); err != nil {
		overlayFile.Close()
		return fmt.Errorf("encode candidate overlay: %w", err)
	}
	if err := overlayFile.Close(); err != nil {
		return fmt.Errorf("close candidate overlay: %w", err)
	}
	buildDirectory, err := os.MkdirTemp(moduleRoot, ".godj-relation-build-*")
	if err != nil {
		return fmt.Errorf("create candidate build directory: %w", err)
	}
	defer os.RemoveAll(buildDirectory)
	command := externalGoCommand(moduleRoot, "test", "-c", "-overlay", overlayPath, "-o", filepath.Join(buildDirectory, "candidate.test"), "./bridge")
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("candidate compile: %w\n%s", err, output)
	}
	if err := os.Rename(candidatePath, absoluteOutput); err != nil {
		return fmt.Errorf("publish generated candidate: %w", err)
	}
	return nil
}

func renderExternalBindings(set bindingSet, poisonCompile bool) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by the relation-binding test-only fixture. DO NOT EDIT.\n\n")
	source.WriteString("package bridge\n\n")
	source.WriteString("import \"example.com/godj-relationbinding-external/meta\"\n\n")
	source.WriteString("var BoundRelations = []meta.BoundRelation{\n")
	for _, relation := range set.Forward() {
		fmt.Fprintf(&source, "\t{Source: meta.ModelKey{App: %q, Model: %q}, Field: %q, Column: %q, Target: meta.ModelKey{App: %q, Model: %q}, Nullable: %t, Delete: %q, ReverseName: %q}, // %s\n",
			relation.Identity.Source.App, relation.Identity.Source.Model,
			relation.Identity.Field, relation.Column,
			relation.Target.App, relation.Target.Model,
			relation.Nullable, relation.Delete, relation.ReverseName, relation.Identity.String())
	}
	source.WriteString("}\n")
	if poisonCompile {
		source.WriteString("\nvar _ = relationBindingCandidateMustNotCompile\n")
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated bindings: %w", err)
	}
	return formatted, nil
}

func assertExternalImportGraph(t *testing.T, project string) {
	t.Helper()
	output := runExternalGo(t, project, "list", "-f", `{{.ImportPath}}|{{join .Imports ","}}`, "./...")
	importsByPackage := make(map[string][]string)
	for _, line := range strings.Split(strings.TrimSpace(output), "\n") {
		path, imports, ok := strings.Cut(line, "|")
		if !ok {
			t.Fatalf("malformed go list line %q", line)
		}
		if imports == "" {
			importsByPackage[path] = nil
		} else {
			importsByPackage[path] = strings.Split(imports, ",")
		}
	}
	authorsPath := externalModule + "/authors"
	blogPath := externalModule + "/blog"
	bridgePath := externalModule + "/bridge"
	for _, pair := range [][2]string{{authorsPath, blogPath}, {blogPath, authorsPath}} {
		if containsString(importsByPackage[pair[0]], pair[1]) {
			t.Fatalf("app-to-app import edge exists: %s -> %s (%v)", pair[0], pair[1], importsByPackage[pair[0]])
		}
	}
	for _, required := range []string{authorsPath, blogPath} {
		if !containsString(importsByPackage[bridgePath], required) {
			t.Fatalf("project bridge imports %v, missing %s", importsByPackage[bridgePath], required)
		}
	}

	packages := make([]string, 0, len(importsByPackage))
	for path := range importsByPackage {
		if strings.HasPrefix(path, externalModule) {
			packages = append(packages, path)
		}
	}
	sort.Strings(packages)
	if got, want := packages, []string{externalModule + "/authors", externalModule + "/blog", externalModule + "/bridge", externalModule + "/meta"}; !equalStrings(got, want) {
		t.Fatalf("external packages = %v, want %v", got, want)
	}
}

func copyExternalFixture(t *testing.T) string {
	t.Helper()
	source := filepath.Join("testdata", "external")
	destination := filepath.Join(t.TempDir(), "external")
	if err := filepath.WalkDir(source, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relative, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		target := filepath.Join(destination, relative)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, contents, 0o644)
	}); err != nil {
		t.Fatalf("copy external fixture: %v", err)
	}
	return destination
}

func runExternalGo(t *testing.T, directory string, args ...string) string {
	t.Helper()
	command := externalGoCommand(directory, args...)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("go %s failed: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func externalGoCommand(directory string, args ...string) *exec.Cmd {
	command := exec.Command("go", args...)
	command.Dir = directory
	command.Env = closedExternalGoEnv()
	return command
}

func closedExternalGoEnv() []string {
	blocked := []string{"GOENV=", "GOPROXY=", "GOSUMDB=", "GOTOOLCHAIN=", "GOWORK="}
	environment := make([]string, 0, len(os.Environ())+5)
	for _, value := range os.Environ() {
		skip := false
		for _, prefix := range blocked {
			if strings.HasPrefix(value, prefix) {
				skip = true
				break
			}
		}
		if !skip {
			environment = append(environment, value)
		}
	}
	return append(environment, "GOENV=off", "GOPROXY=off", "GOSUMDB=off", "GOTOOLCHAIN=local", "GOWORK=off")
}

func readTestFile(t *testing.T, path string) []byte {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return contents
}

func containsString(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func equalStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}
	return true
}
