// Code generated by GoDj. DO NOT EDIT.

package authors

import (
	"github.com/progresshans/godj/orm"
	"github.com/progresshans/godj/schema/ir"
)

const GoDjRelationObjectGeneratorVersion = "godj-codegen-rel-object-v1"
const GoDjRelationObjectSchemaSHA256 = "a4823a324f40c2598c767629714afbfafe343fe3539fb2ffc76f61701a9e34e4"

var _ orm.RelationObjectDescriptor[Author] = AuthorDescriptor{}

func (AuthorDescriptor) SnapshotRelationObjectDescriptor() orm.RelationObjectDescriptor[Author] {
	return AuthorDescriptor{}
}

func (AuthorDescriptor) BindRelationStorage(field ir.Field) (orm.RelationStorage[Author], bool) {
	return nil, false
}

var _ GoDjProjectSnapshot_4b618261fcdec4fb126e8b20714700343543613390d1187439a315455ef5f775
